/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingBankFeedAccountsCreate } from "../../funcs/accountingBankFeedAccountsCreate.js";
import { AccountingBankFeedAccountsAddRequest$zodSchema } from "../../models/accountingbankfeedaccountsaddop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AccountingBankFeedAccountsAddRequest$zodSchema,
};

export const tool$accountingBankFeedAccountsCreate: ToolDefinition<
  typeof args
> = {
  name: "accounting-bank-feed-accounts-create",
  description: `Create Bank Feed Account

Create Bank Feed Account`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await accountingBankFeedAccountsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
