/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingPaymentsDelete } from "../../funcs/accountingPaymentsDelete.js";
import { AccountingPaymentsDeleteRequest$zodSchema } from "../../models/accountingpaymentsdeleteop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AccountingPaymentsDeleteRequest$zodSchema,
};

export const tool$accountingPaymentsDelete: ToolDefinition<typeof args> = {
  name: "accounting-payments-delete",
  description: `Delete Payment

Delete Payment`,
  scopes: ["destructive"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await accountingPaymentsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
