/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingLedgerAccountsDelete } from "../../funcs/accountingLedgerAccountsDelete.js";
import { AccountingLedgerAccountsDeleteRequest$zodSchema } from "../../models/accountingledgeraccountsdeleteop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AccountingLedgerAccountsDeleteRequest$zodSchema,
};

export const tool$accountingLedgerAccountsDelete: ToolDefinition<typeof args> =
  {
    name: "accounting-ledger-accounts-delete",
    description: `Delete Ledger Account

Delete Ledger Account`,
    scopes: ["destructive"],
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await accountingLedgerAccountsDelete(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
