/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingQuotesList } from "../../funcs/accountingQuotesList.js";
import { AccountingQuotesAllRequest$zodSchema } from "../../models/accountingquotesallop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AccountingQuotesAllRequest$zodSchema.optional(),
};

export const tool$accountingQuotesList: ToolDefinition<typeof args> = {
  name: "accounting-quotes-list",
  description: `List Quotes

List Quotes`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await accountingQuotesList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
