/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingBillsUpdate } from "../../funcs/accountingBillsUpdate.js";
import { AccountingBillsUpdateRequest$zodSchema } from "../../models/accountingbillsupdateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AccountingBillsUpdateRequest$zodSchema,
};

export const tool$accountingBillsUpdate: ToolDefinition<typeof args> = {
  name: "accounting-bills-update",
  description: `Update Bill

Update Bill`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await accountingBillsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
