/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingRefundsUpdate } from "../../funcs/accountingRefundsUpdate.js";
import { AccountingRefundsUpdateRequest$zodSchema } from "../../models/accountingrefundsupdateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AccountingRefundsUpdateRequest$zodSchema,
};

export const tool$accountingRefundsUpdate: ToolDefinition<typeof args> = {
  name: "accounting-refunds-update",
  description: `Update Refund

Update Refund`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await accountingRefundsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
