/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingBillPaymentsGet } from "../../funcs/accountingBillPaymentsGet.js";
import { AccountingBillPaymentsOneRequest$zodSchema } from "../../models/accountingbillpaymentsoneop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AccountingBillPaymentsOneRequest$zodSchema,
};

export const tool$accountingBillPaymentsGet: ToolDefinition<typeof args> = {
  name: "accounting-bill-payments-get",
  description: `Get Bill Payment

Get Bill Payment`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await accountingBillPaymentsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
