/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingBankFeedStatementsUpdate } from "../../funcs/accountingBankFeedStatementsUpdate.js";
import { AccountingBankFeedStatementsUpdateRequest$zodSchema } from "../../models/accountingbankfeedstatementsupdateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AccountingBankFeedStatementsUpdateRequest$zodSchema,
};

export const tool$accountingBankFeedStatementsUpdate: ToolDefinition<
  typeof args
> = {
  name: "accounting-bank-feed-statements-update",
  description: `Update Bank Feed Statement

Update Bank Feed Statement`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await accountingBankFeedStatementsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
