/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { atsApplicantsUpdate } from "../../funcs/atsApplicantsUpdate.js";
import { AtsApplicantsUpdateRequest$zodSchema } from "../../models/atsapplicantsupdateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AtsApplicantsUpdateRequest$zodSchema,
};

export const tool$atsApplicantsUpdate: ToolDefinition<typeof args> = {
  name: "ats-applicants-update",
  description: `Update Applicant

Update Applicant`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await atsApplicantsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
