/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { crmCompaniesUpdate } from "../../funcs/crmCompaniesUpdate.js";
import { CrmCompaniesUpdateRequest$zodSchema } from "../../models/crmcompaniesupdateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CrmCompaniesUpdateRequest$zodSchema,
};

export const tool$crmCompaniesUpdate: ToolDefinition<typeof args> = {
  name: "crm-companies-update",
  description: `Update company

Update company`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await crmCompaniesUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
