/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { crmContactsCreate } from "../../funcs/crmContactsCreate.js";
import { CrmContactsAddRequest$zodSchema } from "../../models/crmcontactsaddop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CrmContactsAddRequest$zodSchema,
};

export const tool$crmContactsCreate: ToolDefinition<typeof args> = {
  name: "crm-contacts-create",
  description: `Create contact

Create contact`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await crmContactsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
