/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { crmCustomObjectsUpdate } from "../../funcs/crmCustomObjectsUpdate.js";
import { CrmCustomObjectsUpdateRequest$zodSchema } from "../../models/crmcustomobjectsupdateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CrmCustomObjectsUpdateRequest$zodSchema,
};

export const tool$crmCustomObjectsUpdate: ToolDefinition<typeof args> = {
  name: "crm-custom-objects-update",
  description: `Update custom object

Update custom object`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await crmCustomObjectsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
