/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { crmCustomObjectSchemasGet } from "../../funcs/crmCustomObjectSchemasGet.js";
import { CrmCustomObjectSchemasOneRequest$zodSchema } from "../../models/crmcustomobjectschemasoneop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CrmCustomObjectSchemasOneRequest$zodSchema,
};

export const tool$crmCustomObjectSchemasGet: ToolDefinition<typeof args> = {
  name: "crm-custom-object-schemas-get",
  description: `Get custom object schema

Get custom object schema`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await crmCustomObjectSchemasGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
