/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { crmCompaniesGet } from "../../funcs/crmCompaniesGet.js";
import { CrmCompaniesOneRequest$zodSchema } from "../../models/crmcompaniesoneop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CrmCompaniesOneRequest$zodSchema,
};

export const tool$crmCompaniesGet: ToolDefinition<typeof args> = {
  name: "crm-companies-get",
  description: `Get company

Get company`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await crmCompaniesGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
