/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { crmCustomObjectSchemasCreate } from "../../funcs/crmCustomObjectSchemasCreate.js";
import { CrmCustomObjectSchemasAddRequest$zodSchema } from "../../models/crmcustomobjectschemasaddop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CrmCustomObjectSchemasAddRequest$zodSchema,
};

export const tool$crmCustomObjectSchemasCreate: ToolDefinition<typeof args> = {
  name: "crm-custom-object-schemas-create",
  description: `Create custom object schema

Create custom object schema`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await crmCustomObjectSchemasCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
