/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { crmCustomObjectsCreate } from "../../funcs/crmCustomObjectsCreate.js";
import { CrmCustomObjectsAddRequest$zodSchema } from "../../models/crmcustomobjectsaddop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CrmCustomObjectsAddRequest$zodSchema,
};

export const tool$crmCustomObjectsCreate: ToolDefinition<typeof args> = {
  name: "crm-custom-objects-create",
  description: `Create custom object

Create custom object`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await crmCustomObjectsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
