/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { crmOpportunitiesUpdate } from "../../funcs/crmOpportunitiesUpdate.js";
import { CrmOpportunitiesUpdateRequest$zodSchema } from "../../models/crmopportunitiesupdateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CrmOpportunitiesUpdateRequest$zodSchema,
};

export const tool$crmOpportunitiesUpdate: ToolDefinition<typeof args> = {
  name: "crm-opportunities-update",
  description: `Update opportunity

Update opportunity`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await crmOpportunitiesUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
