/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { crmPipelinesUpdate } from "../../funcs/crmPipelinesUpdate.js";
import { CrmPipelinesUpdateRequest$zodSchema } from "../../models/crmpipelinesupdateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CrmPipelinesUpdateRequest$zodSchema,
};

export const tool$crmPipelinesUpdate: ToolDefinition<typeof args> = {
  name: "crm-pipelines-update",
  description: `Update pipeline

Update pipeline`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await crmPipelinesUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
