/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ecommerceOrdersList } from "../../funcs/ecommerceOrdersList.js";
import { EcommerceOrdersAllRequest$zodSchema } from "../../models/ecommerceordersallop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: EcommerceOrdersAllRequest$zodSchema.optional(),
};

export const tool$ecommerceOrdersList: ToolDefinition<typeof args> = {
  name: "ecommerce-orders-list",
  description: `List Orders

List Orders`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await ecommerceOrdersList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
