/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ecommerceProductsGet } from "../../funcs/ecommerceProductsGet.js";
import { EcommerceProductsOneRequest$zodSchema } from "../../models/ecommerceproductsoneop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: EcommerceProductsOneRequest$zodSchema,
};

export const tool$ecommerceProductsGet: ToolDefinition<typeof args> = {
  name: "ecommerce-products-get",
  description: `Get Product

Get Product`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await ecommerceProductsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
