/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fileStorageFoldersUpdate } from "../../funcs/fileStorageFoldersUpdate.js";
import { FileStorageFoldersUpdateRequest$zodSchema } from "../../models/filestoragefoldersupdateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FileStorageFoldersUpdateRequest$zodSchema,
};

export const tool$fileStorageFoldersUpdate: ToolDefinition<typeof args> = {
  name: "file-storage-folders-update",
  description: `Rename or move Folder

Rename or move Folder`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await fileStorageFoldersUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
