/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fileStorageFilesList } from "../../funcs/fileStorageFilesList.js";
import { FileStorageFilesAllRequest$zodSchema } from "../../models/filestoragefilesallop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FileStorageFilesAllRequest$zodSchema.optional(),
};

export const tool$fileStorageFilesList: ToolDefinition<typeof args> = {
  name: "file-storage-files-list",
  description: `List Files

List Files`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await fileStorageFilesList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
