/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fileStorageSharedLinksUpdate } from "../../funcs/fileStorageSharedLinksUpdate.js";
import { FileStorageSharedLinksUpdateRequest$zodSchema } from "../../models/filestoragesharedlinksupdateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FileStorageSharedLinksUpdateRequest$zodSchema,
};

export const tool$fileStorageSharedLinksUpdate: ToolDefinition<typeof args> = {
  name: "file-storage-shared-links-update",
  description: `Update Shared Link

Update Shared Link`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await fileStorageSharedLinksUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
