/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { fileStorageUploadSessionsGet } from "../../funcs/fileStorageUploadSessionsGet.js";
import { FileStorageUploadSessionsOneRequest$zodSchema } from "../../models/filestorageuploadsessionsoneop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: FileStorageUploadSessionsOneRequest$zodSchema,
};

export const tool$fileStorageUploadSessionsGet: ToolDefinition<typeof args> = {
  name: "file-storage-upload-sessions-get",
  description: `Get Upload Session

Get Upload Session. Use the \`part_size\` to split your file into parts. Upload the parts to the [Upload part of File](#operation/uploadSessionsUpload) endpoint. Note that the base URL is upload.apideck.com instead of unify.apideck.com. For more information on uploads, refer to the [file upload guide](/guides/file-upload).`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await fileStorageUploadSessionsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
