/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { vaultConnectionsDelete } from "../../funcs/vaultConnectionsDelete.js";
import { VaultConnectionsDeleteRequest$zodSchema } from "../../models/vaultconnectionsdeleteop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: VaultConnectionsDeleteRequest$zodSchema,
};

export const tool$vaultConnectionsDelete: ToolDefinition<typeof args> = {
  name: "vault-connections-delete",
  description: `Deletes a connection

Deletes a connection`,
  scopes: ["destructive"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await vaultConnectionsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
