/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { vaultConnectionsUpdate } from "../../funcs/vaultConnectionsUpdate.js";
import { VaultConnectionsUpdateRequest$zodSchema } from "../../models/vaultconnectionsupdateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: VaultConnectionsUpdateRequest$zodSchema,
};

export const tool$vaultConnectionsUpdate: ToolDefinition<typeof args> = {
  name: "vault-connections-update",
  description: `Update connection

Update a connection`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await vaultConnectionsUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
