/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { vaultConnectionConsentUpdate } from "../../funcs/vaultConnectionConsentUpdate.js";
import { VaultConnectionConsentUpdateRequest$zodSchema } from "../../models/vaultconnectionconsentupdateop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: VaultConnectionConsentUpdateRequest$zodSchema,
};

export const tool$vaultConnectionConsentUpdate: ToolDefinition<typeof args> = {
  name: "vault-connection-consent-update",
  description: `Update consent state

Update the consent state of a connection`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await vaultConnectionConsentUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
