/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { vaultConnectionsImports } from "../../funcs/vaultConnectionsImports.js";
import { VaultConnectionsImportRequest$zodSchema } from "../../models/vaultconnectionsimportop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: VaultConnectionsImportRequest$zodSchema,
};

export const tool$vaultConnectionsImports: ToolDefinition<typeof args> = {
  name: "vault-connections-imports",
  description: `Import connection

Import an authorized connection.
`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await vaultConnectionsImports(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
