/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { vaultLogsList } from "../../funcs/vaultLogsList.js";
import { VaultLogsAllRequest$zodSchema } from "../../models/vaultlogsallop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: VaultLogsAllRequest$zodSchema.optional(),
};

export const tool$vaultLogsList: ToolDefinition<typeof args> = {
  name: "vault-logs-list",
  description: `Get all consumer request logs

This endpoint includes all consumer request logs.
`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await vaultLogsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
