blank_issues_enabled: false
contact_links:
  - name: Apideck Support
    url: https://www.apideck.com/support
    about: For account-related issues or general support questions, contact Apideck Support.
