/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
import { PassThroughBody$zodSchema, } from "./passthroughbody.js";
import { SubsidiaryReference$zodSchema, } from "./subsidiaryreference.js";
import { SubsidiaryReferenceInput$zodSchema, } from "./subsidiaryreferenceinput.js";
/**
 * Based on the status some functionality is enabled or disabled.
 */
export const DepartmentStatus = {
    Active: "active",
    Inactive: "inactive",
};
export const DepartmentStatus$zodSchema = z.union([
    z.enum([
        "active",
        "inactive",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("Based on the status some functionality is enabled or disabled.");
export const AccountingDepartment$zodSchema = z
    .object({
    code: z.string().optional().describe("The code of the department."),
    created_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was created."),
    created_by: z.string().nullable().optional().describe("The user who created the object."),
    custom_mappings: z.record(z.string(), z.any()).nullable().optional()
        .describe("When custom mappings are configured on the resource, the result is included here."),
    display_id: z.string().nullable().optional().describe("Id to be displayed."),
    downstream_id: z.string().nullable().optional().describe("The third-party API ID of original entity"),
    id: z.string().optional().describe("A unique identifier for an object."),
    name: z.string().nullable().optional().describe("The name of the department."),
    parent_id: z.string().nullable().optional().describe("A unique identifier for an object."),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    row_version: z.string().nullable().optional().describe("A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."),
    status: DepartmentStatus$zodSchema.optional().describe("Based on the status some functionality is enabled or disabled."),
    subsidiaries: z.array(SubsidiaryReference$zodSchema).optional(),
    updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was last updated."),
    updated_by: z.string().nullable().optional().describe("The user who last updated the object."),
});
export const AccountingDepartmentInput$zodSchema = z.object({
    code: z.string().optional().describe("The code of the department."),
    display_id: z.string().nullable().optional().describe("Id to be displayed."),
    name: z.string().nullable().optional().describe("The name of the department."),
    parent_id: z.string().nullable().optional().describe("A unique identifier for an object."),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    row_version: z.string().nullable().optional().describe("A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."),
    status: DepartmentStatus$zodSchema.optional().describe("Based on the status some functionality is enabled or disabled."),
    subsidiaries: z.array(SubsidiaryReferenceInput$zodSchema).optional(),
});
//# sourceMappingURL=accountingdepartment.js.map