/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { BadRequestResponse$zodSchema, } from "./badrequestresponse.js";
import { GetInvoiceItemResponse$zodSchema, } from "./getinvoiceitemresponse.js";
import { InvoiceItemFilter$zodSchema, } from "./invoiceitemfilter.js";
import { NotFoundResponse$zodSchema, } from "./notfoundresponse.js";
import { PaymentRequiredResponse$zodSchema, } from "./paymentrequiredresponse.js";
import { UnauthorizedResponse$zodSchema, } from "./unauthorizedresponse.js";
import { UnexpectedErrorResponse$zodSchema, } from "./unexpectederrorresponse.js";
import { UnprocessableResponse$zodSchema, } from "./unprocessableresponse.js";
export const AccountingInvoiceItemsOneGlobals$zodSchema = z.object({
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
});
export const AccountingInvoiceItemsOneRequest$zodSchema = z.object({
    fields: z.string().describe("The 'fields' parameter allows API users to specify the fields they want to include in the API response. If this parameter is not present, the API will return all available fields. If this parameter is present, only the fields specified in the comma-separated string will be included in the response. Nested properties can also be requested by using a dot notation. <br /><br />Example: `fields=name,email,addresses.city`<br /><br />In the example above, the response will only include the fields \"name\", \"email\" and \"addresses.city\". If any other fields are available, they will be excluded.").nullable().optional(),
    filter: InvoiceItemFilter$zodSchema.optional().describe("Apply filters"),
    id: z.string().describe("ID of the record you are acting upon."),
    raw: z.boolean().default(false).describe("Include raw response. Mostly used for debugging purposes"),
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckCompanyId: z.string().describe("The ID of the company to scope requests to. For connectors that support multi-company, this overrides the default company configured in connection settings.").optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
    xApideckServiceId: z.string().describe("Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.").optional(),
});
export const AccountingInvoiceItemsOneResponse$zodSchema = z.union([
    GetInvoiceItemResponse$zodSchema,
    BadRequestResponse$zodSchema,
    UnauthorizedResponse$zodSchema,
    PaymentRequiredResponse$zodSchema,
    NotFoundResponse$zodSchema,
    UnprocessableResponse$zodSchema,
    UnexpectedErrorResponse$zodSchema,
]);
//# sourceMappingURL=accountinginvoiceitemsoneop.js.map