/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
import { Address$zodSchema } from "./address.js";
import { BankAccount$zodSchema } from "./bankaccount.js";
import { Currency$zodSchema } from "./currency.js";
import { CustomFieldUnion$zodSchema, } from "./customfieldunion.js";
import { Email$zodSchema } from "./email.js";
import { Gender$zodSchema } from "./gender.js";
import { LinkedDepartment$zodSchema, } from "./linkeddepartment.js";
import { LinkedDepartmentInput$zodSchema, } from "./linkeddepartmentinput.js";
import { LinkedLocation$zodSchema } from "./linkedlocation.js";
import { LinkedLocationInput$zodSchema, } from "./linkedlocationinput.js";
import { LinkedSubsidiary$zodSchema, } from "./linkedsubsidiary.js";
import { LinkedSubsidiaryInput$zodSchema, } from "./linkedsubsidiaryinput.js";
import { LinkedTrackingCategory$zodSchema, } from "./linkedtrackingcategory.js";
import { PassThroughBody$zodSchema, } from "./passthroughbody.js";
import { PhoneNumber$zodSchema } from "./phonenumber.js";
/**
 * The status of the employee.
 */
export const EmployeeStatus = {
    Active: "active",
    Inactive: "inactive",
    Terminated: "terminated",
};
export const EmployeeStatus$zodSchema = z.union([
    z.enum([
        "active",
        "inactive",
        "terminated",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("The status of the employee.");
export const AccountingEmployeeManager$zodSchema = z.object({
    id: z.string().optional().describe("A unique identifier for the manager."),
    name: z.string().nullable().optional().describe("The name of the manager."),
}).describe("The manager of the employee.");
export const AccountingEmployee$zodSchema = z
    .object({
    addresses: z.array(Address$zodSchema).optional().describe("Addresses of the employee."),
    bank_account: BankAccount$zodSchema.optional(),
    birth_date: z.string().date().nullable().optional().describe("The date of birth of the employee."),
    created_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was created."),
    currency: Currency$zodSchema.nullable().optional().describe("Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)."),
    custom_fields: z.array(CustomFieldUnion$zodSchema).optional(),
    custom_mappings: z.record(z.string(), z.any()).nullable().optional()
        .describe("When custom mappings are configured on the resource, the result is included here."),
    department: LinkedDepartment$zodSchema.nullable().optional(),
    display_id: z.string().nullable().optional().describe("Id to be displayed."),
    display_name: z.string().nullable().optional().describe("The display name of the employee."),
    downstream_id: z.string().nullable().optional().describe("The third-party API ID of original entity"),
    emails: z.array(Email$zodSchema).optional().describe("Email addresses of the employee."),
    employee_number: z.string().nullable().optional().describe("The employee number or identifier."),
    first_name: z.string().nullable().optional().describe("The first name of the employee."),
    gender: Gender$zodSchema.nullable().optional().describe("The gender represents the gender identity of a person."),
    hire_date: z.string().date().nullable().optional().describe("The date the employee was hired."),
    id: z.string().optional().describe("A unique identifier for an object."),
    is_contractor: z.boolean().nullable().optional().describe("Whether the employee is a contractor."),
    job_title: z.string().nullable().optional().describe("The job title of the employee."),
    last_name: z.string().nullable().optional().describe("The last name of the employee."),
    location: LinkedLocation$zodSchema.nullable().optional(),
    manager: z.lazy(() => AccountingEmployeeManager$zodSchema).optional()
        .describe("The manager of the employee."),
    notes: z.string().nullable().optional().describe("Notes about the employee."),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    phone_numbers: z.array(PhoneNumber$zodSchema).optional().describe("Phone numbers of the employee."),
    row_version: z.string().nullable().optional().describe("A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."),
    status: EmployeeStatus$zodSchema.nullable().optional().describe("The status of the employee."),
    subsidiary: LinkedSubsidiary$zodSchema.nullable().optional(),
    termination_date: z.string().date().nullable().optional().describe("The date the employee was terminated."),
    tracking_categories: z.array(LinkedTrackingCategory$zodSchema.nullable())
        .nullable().optional().describe("A list of linked tracking categories."),
    updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was last updated."),
});
export const AccountingEmployeeInput$zodSchema = z.object({
    addresses: z.array(Address$zodSchema).optional().describe("Addresses of the employee."),
    bank_account: BankAccount$zodSchema.optional(),
    birth_date: z.string().date().nullable().optional().describe("The date of birth of the employee."),
    currency: Currency$zodSchema.nullable().optional().describe("Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)."),
    custom_fields: z.array(CustomFieldUnion$zodSchema).optional(),
    department: LinkedDepartmentInput$zodSchema.nullable().optional(),
    display_id: z.string().nullable().optional().describe("Id to be displayed."),
    display_name: z.string().nullable().optional().describe("The display name of the employee."),
    emails: z.array(Email$zodSchema).optional().describe("Email addresses of the employee."),
    employee_number: z.string().nullable().optional().describe("The employee number or identifier."),
    first_name: z.string().nullable().optional().describe("The first name of the employee."),
    gender: Gender$zodSchema.nullable().optional().describe("The gender represents the gender identity of a person."),
    hire_date: z.string().date().nullable().optional().describe("The date the employee was hired."),
    is_contractor: z.boolean().nullable().optional().describe("Whether the employee is a contractor."),
    job_title: z.string().nullable().optional().describe("The job title of the employee."),
    last_name: z.string().nullable().optional().describe("The last name of the employee."),
    location: LinkedLocationInput$zodSchema.nullable().optional(),
    manager: z.lazy(() => AccountingEmployeeManager$zodSchema).optional()
        .describe("The manager of the employee."),
    notes: z.string().nullable().optional().describe("Notes about the employee."),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    phone_numbers: z.array(PhoneNumber$zodSchema).optional().describe("Phone numbers of the employee."),
    row_version: z.string().nullable().optional().describe("A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."),
    status: EmployeeStatus$zodSchema.nullable().optional().describe("The status of the employee."),
    subsidiary: LinkedSubsidiaryInput$zodSchema.nullable().optional(),
    termination_date: z.string().date().nullable().optional().describe("The date the employee was terminated."),
    tracking_categories: z.array(LinkedTrackingCategory$zodSchema.nullable())
        .nullable().optional().describe("A list of linked tracking categories."),
});
//# sourceMappingURL=accountingemployee.js.map