/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { BadRequestResponse$zodSchema, } from "./badrequestresponse.js";
import { InvoiceInput$zodSchema } from "./invoice.js";
import { NotFoundResponse$zodSchema, } from "./notfoundresponse.js";
import { PaymentRequiredResponse$zodSchema, } from "./paymentrequiredresponse.js";
import { UnauthorizedResponse$zodSchema, } from "./unauthorizedresponse.js";
import { UnexpectedErrorResponse$zodSchema, } from "./unexpectederrorresponse.js";
import { UnprocessableResponse$zodSchema, } from "./unprocessableresponse.js";
import { UpdateInvoiceResponse$zodSchema, } from "./updateinvoiceresponse.js";
export const AccountingInvoicesUpdateGlobals$zodSchema = z.object({
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
});
export const AccountingInvoicesUpdateRequest$zodSchema = z.object({
    body: InvoiceInput$zodSchema,
    id: z.string().describe("ID of the record you are acting upon."),
    raw: z.boolean().default(false).describe("Include raw response. Mostly used for debugging purposes"),
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
    xApideckServiceId: z.string().describe("Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.").optional(),
});
export const AccountingInvoicesUpdateResponse$zodSchema = z.union([
    UpdateInvoiceResponse$zodSchema,
    BadRequestResponse$zodSchema,
    UnauthorizedResponse$zodSchema,
    PaymentRequiredResponse$zodSchema,
    NotFoundResponse$zodSchema,
    UnprocessableResponse$zodSchema,
    UnexpectedErrorResponse$zodSchema,
]);
//# sourceMappingURL=accountinginvoicesupdateop.js.map