/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import * as b64$ from "../lib/base64.js";
import { AttachmentReferenceType$zodSchema, } from "./attachmentreferencetype.js";
import { BadRequestResponse$zodSchema, } from "./badrequestresponse.js";
import { CreateAttachmentResponse$zodSchema, } from "./createattachmentresponse.js";
import { NotFoundResponse$zodSchema, } from "./notfoundresponse.js";
import { PaymentRequiredResponse$zodSchema, } from "./paymentrequiredresponse.js";
import { UnauthorizedResponse$zodSchema, } from "./unauthorizedresponse.js";
import { UnexpectedErrorResponse$zodSchema, } from "./unexpectederrorresponse.js";
import { UnprocessableResponse$zodSchema, } from "./unprocessableresponse.js";
export const AccountingAttachmentsUploadOpServerList = [
    "https://upload.apideck.com",
];
export const AccountingAttachmentsUploadGlobals$zodSchema = z.object({
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
});
export const AccountingAttachmentsUploadRequest$zodSchema = z.object({
    body: z.string().describe("Base64-encoded binary content").transform(b64$.bytesFromBase64),
    raw: z.boolean().default(false).describe("Include raw response. Mostly used for debugging purposes"),
    reference_id: z.string().describe("The reference id of the object to retrieve."),
    reference_type: AttachmentReferenceType$zodSchema.describe("The reference type of the document."),
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
    xApideckMetadata: z.string().describe("Metadata to attach to the attachment file (JSON string)").optional(),
    xApideckServiceId: z.string().describe("Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.").optional(),
});
export const AccountingAttachmentsUploadResponse$zodSchema = z.union([
    CreateAttachmentResponse$zodSchema,
    BadRequestResponse$zodSchema,
    UnauthorizedResponse$zodSchema,
    PaymentRequiredResponse$zodSchema,
    NotFoundResponse$zodSchema,
    UnprocessableResponse$zodSchema,
    UnexpectedErrorResponse$zodSchema,
]);
//# sourceMappingURL=accountingattachmentsuploadop.js.map