/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
/**
 * Status of the attendee
 */
export const ActivityAttendeeStatus = {
    Accepted: "accepted",
    Tentative: "tentative",
    Declined: "declined",
};
export const ActivityAttendeeStatus$zodSchema = z.union([
    z.enum([
        "accepted",
        "tentative",
        "declined",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("Status of the attendee");
export const ActivityAttendee$zodSchema = z.object({
    contact_id: z.string().nullable().optional().describe("The identifier for a related contact"),
    created_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The time the attendee was created (ISO 8601)"),
    email_address: z.string().nullable().optional().describe("Email address of the attendee"),
    first_name: z.string().nullable().optional().describe("First name of the attendee"),
    id: z.string().nullable().optional().describe("Unique identifier for the attendee"),
    is_organizer: z.boolean().nullable().optional().describe("Whether the attendee is the organizer of the activity"),
    last_name: z.string().nullable().optional().describe("Last name of the attendee"),
    middle_name: z.string().nullable().optional().describe("Middle name of the attendee"),
    name: z.string().nullable().optional().describe("Full name of the attendee"),
    prefix: z.string().nullable().optional().describe("Prefix of the attendee"),
    status: ActivityAttendeeStatus$zodSchema.nullable().optional().describe("Status of the attendee"),
    suffix: z.string().nullable().optional().describe("Suffix of the attendee"),
    updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The last time the attendee was updated (ISO 8601)"),
    user_id: z.string().nullable().optional().describe("The identifier for a related user"),
});
export const ActivityAttendeeInput$zodSchema = z.object({
    email_address: z.string().nullable().optional().describe("Email address of the attendee"),
    first_name: z.string().nullable().optional().describe("First name of the attendee"),
    is_organizer: z.boolean().nullable().optional().describe("Whether the attendee is the organizer of the activity"),
    last_name: z.string().nullable().optional().describe("Last name of the attendee"),
    middle_name: z.string().nullable().optional().describe("Middle name of the attendee"),
    name: z.string().nullable().optional().describe("Full name of the attendee"),
    prefix: z.string().nullable().optional().describe("Prefix of the attendee"),
    status: ActivityAttendeeStatus$zodSchema.nullable().optional().describe("Status of the attendee"),
    suffix: z.string().nullable().optional().describe("Suffix of the attendee"),
});
//# sourceMappingURL=activityattendee.js.map