/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
/**
 * Type of entity this payment should be attributed to.
 */
export const AllocationAllocationType = {
    Invoice: "invoice",
    Order: "order",
    Expense: "expense",
    CreditMemo: "credit_memo",
    OverPayment: "over_payment",
    PrePayment: "pre_payment",
    JournalEntry: "journal_entry",
    Other: "other",
    Bill: "bill",
};
export const AllocationAllocationType$zodSchema = z.union([
    z.enum([
        "invoice",
        "order",
        "expense",
        "credit_memo",
        "over_payment",
        "pre_payment",
        "journal_entry",
        "other",
        "bill",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("Type of entity this payment should be attributed to.");
export const Allocation$zodSchema = z.object({
    allocation_id: z.string().optional().describe("Unique identifier of the allocation"),
    amount: z.number().nullable().optional().describe("Amount of payment that should be attributed to this allocation. If null, the total_amount will be used."),
    code: z.string().optional(),
    id: z.string().optional().describe("Unique identifier of entity this payment should be attributed to."),
    type: AllocationAllocationType$zodSchema.optional().describe("Type of entity this payment should be attributed to."),
});
export const AllocationInput$zodSchema = z.object({
    allocation_id: z.string().optional().describe("Unique identifier of the allocation"),
    amount: z.number().nullable().optional().describe("Amount of payment that should be attributed to this allocation. If null, the total_amount will be used."),
    id: z.string().optional().describe("Unique identifier of entity this payment should be attributed to."),
    type: AllocationAllocationType$zodSchema.optional().describe("Type of entity this payment should be attributed to."),
});
//# sourceMappingURL=allocation.js.map