/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
import { PassThroughBody$zodSchema, } from "./passthroughbody.js";
export const ApplicationStatus = {
    Open: "open",
    Rejected: "rejected",
    Hired: "hired",
    Converted: "converted",
    Other: "other",
};
export const ApplicationStatus$zodSchema = z.union([
    z.enum([
        "open",
        "rejected",
        "hired",
        "converted",
        "other",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]);
export const ApplicationStage$zodSchema = z.object({
    id: z.string().nullable().optional().describe("Stage the candidate should be in. If omitted, the default stage for this job will be used."),
    name: z.string().nullable().optional(),
});
export const Application$zodSchema = z.object({
    applicant_id: z.string().nullable(),
    created_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was created."),
    created_by: z.string().nullable().optional().describe("The user who created the object."),
    custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe("When custom mappings are configured on the resource, the result is included here."),
    id: z.string().optional().describe("A unique identifier for an object."),
    job_id: z.string().nullable(),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    stage: z.lazy(() => ApplicationStage$zodSchema).optional(),
    status: ApplicationStatus$zodSchema.nullable().optional(),
    updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was last updated."),
    updated_by: z.string().nullable().optional().describe("The user who last updated the object."),
});
export const ApplicationInput$zodSchema = z.object({
    applicant_id: z.string().nullable(),
    job_id: z.string().nullable(),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    stage: z.lazy(() => ApplicationStage$zodSchema).optional(),
    status: ApplicationStatus$zodSchema.nullable().optional(),
});
//# sourceMappingURL=application.js.map