/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
/**
 * The type of period to include in the resource: month, quarter, year.
 */
export const PeriodType = {
    Month: "month",
    Quarter: "quarter",
    Year: "year",
};
export const PeriodType$zodSchema = z.union([
    z.enum([
        "month",
        "quarter",
        "year",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("The type of period to include in the resource: month, quarter, year.");
/**
 * The accounting method used for the report: cash or accrual.
 */
export const BalanceSheetFilterAccountingMethod = {
    Cash: "cash",
    Accrual: "accrual",
};
export const BalanceSheetFilterAccountingMethod$zodSchema = z.union([
    z.enum([
        "cash",
        "accrual",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("The accounting method used for the report: cash or accrual.");
export const BalanceSheetFilter$zodSchema = z
    .object({
    accounting_method: BalanceSheetFilterAccountingMethod$zodSchema.optional()
        .describe("The accounting method used for the report: cash or accrual."),
    end_date: z.string().optional().describe("The end date of the period to include in the resource."),
    location_id: z.string().optional().describe("The ID of the location to include in the resource."),
    period_count: z.int().optional().describe("The number of periods to include in the resource."),
    period_type: PeriodType$zodSchema.optional().describe("The type of period to include in the resource: month, quarter, year."),
    start_date: z.string().optional().describe("The start date of the period to include in the resource."),
});
//# sourceMappingURL=balancesheetfilter.js.map