/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { Currency$zodSchema } from "./currency.js";
export const BalanceSheetAssetsAccount$zodSchema = z.object({
    account_id: z.string().optional().describe("The unique identifier for the account."),
    code: z.string().optional().describe("The account code of the account"),
    items: z.any().optional().describe("A list of balance sheet accounts"),
    name: z.string().optional().describe("The name of the account."),
    value: z.number().optional().describe("The amount or value of the item"),
}).describe("A balance sheet assets account represents the financial position of a company at a specific point in time.");
export const BalanceSheetLiabilitiesAccount$zodSchema = z.object({
    account_id: z.string().optional().describe("The unique identifier for the account."),
    code: z.string().optional().describe("The account code of the account"),
    items: z.any().optional().describe("A list of balance sheet accounts"),
    name: z.string().optional().describe("The name of the account."),
    value: z.number().optional().describe("The amount or value of the item"),
}).describe("A balance sheet liabilities account represents the financial position of a company at a specific point in time.");
export const BalanceSheetEquityAccount$zodSchema = z.object({
    account_id: z.string().optional().describe("The unique identifier for the account."),
    code: z.string().optional().describe("The account code of the account"),
    items: z.any().optional().describe("A list of balance sheet accounts"),
    name: z.string().optional().describe("The name of the account."),
    value: z.number().optional().describe("The amount or value of the item"),
}).describe("A balance sheet equity account represents the financial position of a company at a specific point in time.");
export const BalanceSheetUncategorizedItemsAccount$zodSchema = z.object({
    account_id: z.string().optional().describe("The unique identifier for the account."),
    code: z.string().optional().describe("The account code of the account"),
    items: z.any().optional().describe("A list of balance sheet accounts"),
    name: z.string().optional().describe("The name of the account."),
    value: z.number().optional().describe("The amount or value of the item"),
}).describe("A balance sheet uncategorized items account represents the financial position of a company at a specific point in time.");
export const Report$zodSchema = z.object({
    assets: z.lazy(() => BalanceSheetAssetsAccount$zodSchema).describe("A balance sheet assets account represents the financial position of a company at a specific point in time."),
    created_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was created."),
    created_by: z.string().nullable().optional().describe("The user who created the object."),
    currency: Currency$zodSchema.nullable().optional().describe("Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)."),
    custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe("When custom mappings are configured on the resource, the result is included here."),
    end_date: z.string().describe("The start date of the report"),
    equity: z.lazy(() => BalanceSheetEquityAccount$zodSchema).describe("A balance sheet equity account represents the financial position of a company at a specific point in time."),
    id: z.string().optional().describe("A unique identifier for an object."),
    liabilities: z.lazy(() => BalanceSheetLiabilitiesAccount$zodSchema).describe("A balance sheet liabilities account represents the financial position of a company at a specific point in time."),
    net_assets: z.number().optional().describe("The net assets of the balance sheet"),
    report_name: z.string().optional().describe("The name of the report"),
    start_date: z.string().optional().describe("The start date of the report"),
    uncategorized_items: z.lazy(() => BalanceSheetUncategorizedItemsAccount$zodSchema).optional().describe("A balance sheet uncategorized items account represents the financial position of a company at a specific point in time."),
    updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was last updated."),
    updated_by: z.string().nullable().optional().describe("The user who last updated the object."),
});
export const BalanceSheet$zodSchema = z.object({
    reports: z.array(z.lazy(() => Report$zodSchema)),
});
//# sourceMappingURL=balancesheet.js.map