/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const Benefit$zodSchema = z.object({
    employee_deduction: z.number().nullable().optional().describe("The amount deducted for benefit."),
    employer_contribution: z.number().nullable().optional().describe("The amount of employer contribution."),
    name: z.string().nullable().optional().describe("The name of the benefit."),
});
//# sourceMappingURL=benefit.js.map