import * as z from "zod";
import { LineItemType } from "./lineitemtype.js";
import { LinkedCustomer } from "./linkedcustomer.js";
import { LinkedInvoiceItem } from "./linkedinvoiceitem.js";
import { LinkedLedgerAccount } from "./linkedledgeraccount.js";
import { LinkedPurchaseOrder } from "./linkedpurchaseorder.js";
import { LinkedTaxRate } from "./linkedtaxrate.js";
import { LinkedTrackingCategory } from "./linkedtrackingcategory.js";
import { LinkedWorktag } from "./linkedworktag.js";
import { Rebilling } from "./rebilling.js";
export type BillLineItem = {
    id?: string | undefined;
    row_id?: string | undefined;
    code?: string | null | undefined;
    line_number?: number | null | undefined;
    description?: string | null | undefined;
    type?: LineItemType | null | undefined;
    tax_amount?: number | null | undefined;
    total_amount?: number | null | undefined;
    quantity?: number | null | undefined;
    unit_price?: number | null | undefined;
    unit_of_measure?: string | null | undefined;
    discount_percentage?: number | null | undefined;
    discount_amount?: number | null | undefined;
    location_id?: string | null | undefined;
    department_id?: string | null | undefined;
    subsidiary_id?: string | null | undefined;
    category_id?: string | null | undefined;
    shipping_id?: string | null | undefined;
    memo?: string | null | undefined;
    prepaid?: boolean | null | undefined;
    tax_applicable_on?: string | null | undefined;
    tax_recoverability?: string | null | undefined;
    tax_method?: string | null | undefined;
    retention_amount?: number | null | undefined;
    payment_amount?: number | null | undefined;
    item?: LinkedInvoiceItem | undefined;
    tax_rate?: LinkedTaxRate | undefined;
    ledger_account?: LinkedLedgerAccount | null | undefined;
    purchase_order?: LinkedPurchaseOrder | null | undefined;
    tracking_categories?: Array<LinkedTrackingCategory | null> | null | undefined;
    customer?: LinkedCustomer | null | undefined;
    rebilling?: Rebilling | null | undefined;
    row_version?: string | null | undefined;
    updated_by?: string | null | undefined;
    created_by?: string | null | undefined;
    created_at?: string | null | undefined;
    updated_at?: string | null | undefined;
    worktags?: Array<LinkedWorktag | null> | undefined;
};
export declare const BillLineItem$zodSchema: z.ZodType<BillLineItem>;
//# sourceMappingURL=billlineitem.d.ts.map