/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
import { SortDirection$zodSchema } from "./sortdirection.js";
/**
 * The field on which to sort the Bills
 */
export const BillsSortBy = {
    UpdatedAt: "updated_at",
    CreatedAt: "created_at",
};
export const BillsSortBy$zodSchema = z.union([
    z.enum([
        "updated_at",
        "created_at",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("The field on which to sort the Bills");
export const BillsSort$zodSchema = z.object({
    by: BillsSortBy$zodSchema.optional().describe("The field on which to sort the Bills"),
    direction: SortDirection$zodSchema.default("asc").describe("The direction in which to sort the results"),
});
//# sourceMappingURL=billssort.js.map