/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { LineItemType$zodSchema } from "./lineitemtype.js";
import { LinkedCustomerInput$zodSchema, } from "./linkedcustomerinput.js";
import { LinkedInvoiceItem$zodSchema, } from "./linkedinvoiceitem.js";
import { LinkedLedgerAccount$zodSchema, } from "./linkedledgeraccount.js";
import { LinkedPurchaseOrder$zodSchema, } from "./linkedpurchaseorder.js";
import { LinkedTaxRateInput$zodSchema, } from "./linkedtaxrateinput.js";
import { LinkedTrackingCategory$zodSchema, } from "./linkedtrackingcategory.js";
import { LinkedWorktag$zodSchema } from "./linkedworktag.js";
import { Rebilling$zodSchema } from "./rebilling.js";
export const BillLineItemInput$zodSchema = z
    .object({
    category_id: z.string().nullable().optional().describe("ID of the category of the line item"),
    code: z.string().nullable().optional().describe("User defined item code"),
    customer: LinkedCustomerInput$zodSchema.nullable().optional().describe("The customer this entity is linked to."),
    department_id: z.string().nullable().optional().describe("The ID of the department"),
    description: z.string().nullable().optional().describe("User defined description"),
    discount_amount: z.number().nullable().optional().describe("Discount amount applied to the line item when supported downstream."),
    discount_percentage: z.number().nullable().optional().describe("Discount percentage applied to the line item when supported downstream."),
    item: LinkedInvoiceItem$zodSchema.optional(),
    ledger_account: LinkedLedgerAccount$zodSchema.nullable().optional(),
    line_number: z.int().nullable().optional().describe("Line number of the resource"),
    location_id: z.string().nullable().optional().describe("The ID of the location"),
    memo: z.string().nullable().optional().describe("Memo"),
    payment_amount: z.number().nullable().optional().describe("Payment amount"),
    prepaid: z.boolean().nullable().optional().describe("Whether the line item is prepaid"),
    purchase_order: LinkedPurchaseOrder$zodSchema.nullable().optional(),
    quantity: z.number().nullable().optional(),
    rebilling: Rebilling$zodSchema.nullable().optional().describe("Rebilling metadata for this line item."),
    retention_amount: z.number().nullable().optional().describe("Retention amount"),
    row_id: z.string().optional().describe("Row ID"),
    row_version: z.string().nullable().optional().describe("A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."),
    shipping_id: z.string().nullable().optional().describe("ID of the shipping of the line item"),
    subsidiary_id: z.string().nullable().optional().describe("The ID of the subsidiary"),
    tax_amount: z.number().nullable().optional().describe("Tax amount"),
    tax_applicable_on: z.string().nullable().optional().describe("Tax applicable on"),
    tax_method: z.string().nullable().optional().describe("Method of tax calculation"),
    tax_rate: LinkedTaxRateInput$zodSchema.optional(),
    tax_recoverability: z.string().nullable().optional().describe("Tax recoverability"),
    total_amount: z.number().nullable().optional().describe("Total amount of the line item"),
    tracking_categories: z.array(LinkedTrackingCategory$zodSchema.nullable())
        .nullable().optional().describe("A list of linked tracking categories."),
    type: LineItemType$zodSchema.nullable().optional().describe("Line Item type"),
    unit_of_measure: z.string().nullable().optional().describe("Description of the unit type the item is sold as, ie: kg, hour."),
    unit_price: z.number().nullable().optional(),
    worktags: z.array(LinkedWorktag$zodSchema.nullable()).optional().describe("A list of linked worktags. This is only supported for Workday."),
});
//# sourceMappingURL=billlineiteminput.js.map