/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
import { SortDirection$zodSchema } from "./sortdirection.js";
/**
 * The field on which to sort the Collections
 */
export const CollectionsSortBy = {
    Name: "name",
    CreatedAt: "created_at",
    UpdatedAt: "updated_at",
};
export const CollectionsSortBy$zodSchema = z.union([
    z.enum([
        "name",
        "created_at",
        "updated_at",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("The field on which to sort the Collections");
export const CollectionsSort$zodSchema = z.object({
    by: CollectionsSortBy$zodSchema.optional().describe("The field on which to sort the Collections"),
    direction: SortDirection$zodSchema.default("asc").describe("The direction in which to sort the results"),
});
//# sourceMappingURL=collectionssort.js.map