/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const CollectionUser$zodSchema = z.object({
    created_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was created."),
    custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe("When custom mappings are configured on the resource, the result is included here."),
    email: z.string().nullable().optional().describe("Email address of the user"),
    first_name: z.string().nullable().optional().describe("First name of the user"),
    id: z.string().nullable().optional().describe("A unique identifier for an object."),
    last_name: z.string().nullable().optional().describe("Last name of the user"),
    name: z.string().nullable().optional().describe("Full name of the user"),
    photo_url: z.string().nullable().optional().describe("The URL of the photo of a person."),
    updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was last updated."),
});
//# sourceMappingURL=collectionuser.js.map