import * as z from "zod";
import { Address } from "./address.js";
import { BankAccount1 } from "./bankaccount1.js";
import { Currency } from "./currency.js";
import { CustomFieldUnion } from "./customfieldunion.js";
import { Email } from "./email.js";
import { PassThroughBody } from "./passthroughbody.js";
import { PhoneNumber } from "./phonenumber.js";
import { SocialLink } from "./sociallink.js";
import { Website } from "./website.js";
export type CompanyRowType = {
    id?: string | null | undefined;
    name?: string | null | undefined;
};
export declare const CompanyRowType$zodSchema: z.ZodType<CompanyRowType>;
export type Company1 = {
    id?: string | undefined;
    name: string | null;
    interaction_count?: number | null | undefined;
    owner_id?: string | null | undefined;
    image?: string | null | undefined;
    description?: string | null | undefined;
    vat_number?: string | null | undefined;
    currency?: Currency | null | undefined;
    status?: string | null | undefined;
    fax?: string | null | undefined;
    annual_revenue?: string | null | undefined;
    number_of_employees?: string | null | undefined;
    industry?: string | null | undefined;
    ownership?: string | null | undefined;
    sales_tax_number?: string | null | undefined;
    payee_number?: string | null | undefined;
    abn_or_tfn?: string | null | undefined;
    abn_branch?: string | null | undefined;
    acn?: string | null | undefined;
    first_name?: string | null | undefined;
    last_name?: string | null | undefined;
    parent_id?: string | null | undefined;
    bank_accounts?: Array<BankAccount1> | undefined;
    websites?: Array<Website> | undefined;
    addresses?: Array<Address> | undefined;
    social_links?: Array<SocialLink> | undefined;
    phone_numbers?: Array<PhoneNumber> | undefined;
    emails?: Array<Email> | undefined;
    row_type?: CompanyRowType | undefined;
    custom_fields?: Array<CustomFieldUnion> | undefined;
    tags?: Array<string> | null | undefined;
    read_only?: boolean | null | undefined;
    last_activity_at?: string | null | undefined;
    deleted?: boolean | undefined;
    salutation?: string | null | undefined;
    birthday?: string | null | undefined;
    custom_mappings?: {
        [k: string]: any;
    } | null | undefined;
    updated_by?: string | null | undefined;
    created_by?: string | null | undefined;
    updated_at?: string | null | undefined;
    created_at?: string | null | undefined;
    pass_through?: Array<PassThroughBody> | undefined;
};
export declare const Company1$zodSchema: z.ZodType<Company1>;
export type Company1Input = {
    name: string | null;
    owner_id?: string | null | undefined;
    image?: string | null | undefined;
    description?: string | null | undefined;
    vat_number?: string | null | undefined;
    currency?: Currency | null | undefined;
    status?: string | null | undefined;
    fax?: string | null | undefined;
    annual_revenue?: string | null | undefined;
    number_of_employees?: string | null | undefined;
    industry?: string | null | undefined;
    ownership?: string | null | undefined;
    sales_tax_number?: string | null | undefined;
    payee_number?: string | null | undefined;
    abn_or_tfn?: string | null | undefined;
    abn_branch?: string | null | undefined;
    acn?: string | null | undefined;
    first_name?: string | null | undefined;
    last_name?: string | null | undefined;
    bank_accounts?: Array<BankAccount1> | undefined;
    websites?: Array<Website> | undefined;
    addresses?: Array<Address> | undefined;
    social_links?: Array<SocialLink> | undefined;
    phone_numbers?: Array<PhoneNumber> | undefined;
    emails?: Array<Email> | undefined;
    row_type?: CompanyRowType | undefined;
    custom_fields?: Array<CustomFieldUnion> | undefined;
    tags?: Array<string> | null | undefined;
    read_only?: boolean | null | undefined;
    salutation?: string | null | undefined;
    birthday?: string | null | undefined;
    pass_through?: Array<PassThroughBody> | undefined;
};
export declare const Company1Input$zodSchema: z.ZodType<Company1Input>;
//# sourceMappingURL=company1.d.ts.map