/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { GetApiResourceResponse$zodSchema, } from "./getapiresourceresponse.js";
import { NotFoundResponse$zodSchema, } from "./notfoundresponse.js";
import { PaymentRequiredResponse$zodSchema, } from "./paymentrequiredresponse.js";
import { UnauthorizedResponse$zodSchema, } from "./unauthorizedresponse.js";
import { UnexpectedErrorResponse$zodSchema, } from "./unexpectederrorresponse.js";
export const ConnectorApiResourcesOneGlobals$zodSchema = z.object({
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
});
export const ConnectorApiResourcesOneRequest$zodSchema = z.object({
    id: z.string().describe("ID of the record you are acting upon."),
    resource_id: z.string().describe("ID of the resource you are acting upon."),
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
});
export const ConnectorApiResourcesOneResponse$zodSchema = z.union([
    GetApiResourceResponse$zodSchema,
    UnauthorizedResponse$zodSchema,
    PaymentRequiredResponse$zodSchema,
    NotFoundResponse$zodSchema,
    UnexpectedErrorResponse$zodSchema,
]);
//# sourceMappingURL=connectorapiresourcesoneop.js.map