/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { PaginationCoverage$zodSchema, } from "./paginationcoverage.js";
import { ResourceStatus$zodSchema } from "./resourcestatus.js";
import { SupportedProperty$zodSchema, } from "./supportedproperty.js";
export const ConnectorResource$zodSchema = z
    .object({
    custom_fields_supported: z.boolean().optional().describe("Indicates if custom fields are supported on this resource."),
    downstream_id: z.string().optional().describe("ID of the resource in the Connector's API (downstream)"),
    downstream_name: z.string().optional().describe("Name of the resource in the Connector's API (downstream)"),
    downstream_unsupported_operations: z.array(z.string()).optional().describe("List of operations that are not supported on the downstream."),
    id: z.string().optional().describe("ID of the resource, typically a lowercased version of name."),
    name: z.string().optional().describe("Name of the resource (plural)"),
    pagination: PaginationCoverage$zodSchema.optional(),
    pagination_supported: z.boolean().optional().describe("Indicates if pagination (cursor and limit parameters) is supported on the list endpoint of the resource."),
    status: ResourceStatus$zodSchema.optional().describe("Status of the resource. Resources with status live or beta are callable."),
    supported_fields: z.array(SupportedProperty$zodSchema).optional().describe("Supported fields on the detail endpoint."),
    supported_filters: z.array(z.string()).optional().describe("Supported filters on the list endpoint of the resource."),
    supported_list_fields: z.array(SupportedProperty$zodSchema).optional()
        .describe("Supported fields on the list endpoint."),
    supported_operations: z.array(z.string()).optional().describe("List of supported operations on the resource."),
    supported_sort_by: z.array(z.string()).optional().describe("Supported sorting properties on the list endpoint of the resource."),
});
//# sourceMappingURL=connectorresource.js.map