/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const ConsumerMetadata$zodSchema = z.object({
    account_name: z.string().optional().describe("The name of the account as shown in the sidebar."),
    email: z.string().optional().describe("The email of the user as shown in the sidebar."),
    image: z.string().optional().describe("The avatar of the user in the sidebar. Must be a valid URL"),
    user_name: z.string().optional().describe("The name of the user as shown in the sidebar."),
}).describe("The metadata of the consumer. This is used to display the consumer in the sidebar. This is optional, but recommended.");
//# sourceMappingURL=consumermetadata.js.map