/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
import { Address$zodSchema } from "./address.js";
import { CustomFieldUnion$zodSchema, } from "./customfieldunion.js";
import { Email$zodSchema } from "./email.js";
import { PassThroughBody$zodSchema, } from "./passthroughbody.js";
import { PhoneNumber$zodSchema } from "./phonenumber.js";
import { SocialLink$zodSchema } from "./sociallink.js";
import { Website$zodSchema } from "./website.js";
/**
 * The type of the contact.
 */
export const ContactType = {
    Customer: "customer",
    Supplier: "supplier",
    Employee: "employee",
    Personal: "personal",
};
export const ContactType$zodSchema = z.union([
    z.enum([
        "customer",
        "supplier",
        "employee",
        "personal",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("The type of the contact.");
/**
 * The gender of the contact.
 */
export const ContactGender = {
    Male: "male",
    Female: "female",
    Unisex: "unisex",
};
export const ContactGender$zodSchema = z.union([
    z.enum([
        "male",
        "female",
        "unisex",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("The gender of the contact.");
export const Contact$zodSchema = z.object({
    active: z.boolean().nullable().optional().describe("The active status of the contact."),
    addresses: z.array(Address$zodSchema).optional(),
    birthday: z.string().nullable().optional().describe("The birthday of the contact."),
    company_id: z.string().nullable().optional().describe("The company the contact is associated with."),
    company_name: z.string().nullable().optional().describe("The name of the company the contact is associated with."),
    created_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The creation date of the contact."),
    current_balance: z.number().nullable().optional().describe("The current balance of the contact."),
    custom_fields: z.array(CustomFieldUnion$zodSchema).nullable().optional(),
    custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe("When custom mappings are configured on the resource, the result is included here."),
    department: z.string().nullable().optional().describe("The department of the contact."),
    description: z.string().nullable().optional().describe("The description of the contact."),
    email_domain: z.string().nullable().optional(),
    emails: z.array(Email$zodSchema).optional(),
    fax: z.string().nullable().optional().describe("The fax number of the contact."),
    first_call_at: z.iso.datetime({ offset: true }).nullable().optional()
        .describe("The first call date of the contact."),
    first_email_at: z.iso.datetime({ offset: true }).nullable().optional()
        .describe("The first email date of the contact."),
    first_name: z.string().nullable().optional().describe("The first name of the contact."),
    gender: ContactGender$zodSchema.nullable().optional().describe("The gender of the contact."),
    id: z.string().optional().describe("Unique identifier for the contact."),
    image: z.string().nullable().optional(),
    language: z.string().nullable().optional().describe("language code according to ISO 639-1. For the United States - EN"),
    last_activity_at: z.iso.datetime({ offset: true }).nullable().optional()
        .describe("The last activity date of the contact."),
    last_name: z.string().nullable().optional().describe("The last name of the contact."),
    lead_id: z.string().nullable().optional().describe("The lead the contact is associated with."),
    lead_source: z.string().nullable().optional().describe("The lead source of the contact."),
    middle_name: z.string().nullable().optional().describe("The middle name of the contact."),
    name: z.string().nullable().optional().describe("Full name of the contact."),
    opportunity_ids: z.array(z.string()).optional().describe("The opportunity ids of the contact."),
    owner_id: z.string().nullable().optional().describe("The owner of the contact."),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    phone_numbers: z.array(PhoneNumber$zodSchema).optional(),
    photo_url: z.string().nullable().optional().describe("The URL of the photo of a person."),
    prefix: z.string().nullable().optional().describe("The prefix of the contact."),
    social_links: z.array(SocialLink$zodSchema).optional(),
    status: z.string().nullable().optional().describe("The status of the contact."),
    suffix: z.string().nullable().optional().describe("The suffix of the contact."),
    tags: z.array(z.string()).nullable().optional(),
    title: z.string().nullable().optional().describe("The job title of the contact."),
    type: ContactType$zodSchema.nullable().optional().describe("The type of the contact."),
    updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The last update date of the contact."),
    websites: z.array(Website$zodSchema).optional(),
});
export const ContactInput$zodSchema = z.object({
    active: z.boolean().nullable().optional().describe("The active status of the contact."),
    addresses: z.array(Address$zodSchema).optional(),
    birthday: z.string().nullable().optional().describe("The birthday of the contact."),
    company_id: z.string().nullable().optional().describe("The company the contact is associated with."),
    company_name: z.string().nullable().optional().describe("The name of the company the contact is associated with."),
    current_balance: z.number().nullable().optional().describe("The current balance of the contact."),
    custom_fields: z.array(CustomFieldUnion$zodSchema).nullable().optional(),
    department: z.string().nullable().optional().describe("The department of the contact."),
    description: z.string().nullable().optional().describe("The description of the contact."),
    email_domain: z.string().nullable().optional(),
    emails: z.array(Email$zodSchema).optional(),
    fax: z.string().nullable().optional().describe("The fax number of the contact."),
    first_name: z.string().nullable().optional().describe("The first name of the contact."),
    gender: ContactGender$zodSchema.nullable().optional().describe("The gender of the contact."),
    image: z.string().nullable().optional(),
    language: z.string().nullable().optional().describe("language code according to ISO 639-1. For the United States - EN"),
    last_name: z.string().nullable().optional().describe("The last name of the contact."),
    lead_id: z.string().nullable().optional().describe("The lead the contact is associated with."),
    lead_source: z.string().nullable().optional().describe("The lead source of the contact."),
    middle_name: z.string().nullable().optional().describe("The middle name of the contact."),
    name: z.string().nullable().optional().describe("Full name of the contact."),
    opportunity_ids: z.array(z.string()).optional().describe("The opportunity ids of the contact."),
    owner_id: z.string().nullable().optional().describe("The owner of the contact."),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    phone_numbers: z.array(PhoneNumber$zodSchema).optional(),
    photo_url: z.string().nullable().optional().describe("The URL of the photo of a person."),
    prefix: z.string().nullable().optional().describe("The prefix of the contact."),
    social_links: z.array(SocialLink$zodSchema).optional(),
    status: z.string().nullable().optional().describe("The status of the contact."),
    suffix: z.string().nullable().optional().describe("The suffix of the contact."),
    tags: z.array(z.string()).nullable().optional(),
    title: z.string().nullable().optional().describe("The job title of the contact."),
    type: ContactType$zodSchema.nullable().optional().describe("The type of the contact."),
    websites: z.array(Website$zodSchema).optional(),
});
//# sourceMappingURL=contact.js.map