import * as z from "zod";
import { OpenEnum } from "../types/enums.js";
/**
 * Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
 */
export declare const Currency: {
    readonly UnknownCurrency: "UNKNOWN_CURRENCY";
    readonly Aed: "AED";
    readonly Afn: "AFN";
    readonly All: "ALL";
    readonly Amd: "AMD";
    readonly Ang: "ANG";
    readonly Aoa: "AOA";
    readonly Ars: "ARS";
    readonly Aud: "AUD";
    readonly Awg: "AWG";
    readonly Azn: "AZN";
    readonly Bam: "BAM";
    readonly Bbd: "BBD";
    readonly Bdt: "BDT";
    readonly Bgn: "BGN";
    readonly Bhd: "BHD";
    readonly Bif: "BIF";
    readonly Bmd: "BMD";
    readonly Bnd: "BND";
    readonly Bob: "BOB";
    readonly Bov: "BOV";
    readonly Brl: "BRL";
    readonly Bsd: "BSD";
    readonly Btn: "BTN";
    readonly Bwp: "BWP";
    readonly Byr: "BYR";
    readonly Bzd: "BZD";
    readonly Cad: "CAD";
    readonly Cdf: "CDF";
    readonly Che: "CHE";
    readonly Chf: "CHF";
    readonly Chw: "CHW";
    readonly Clf: "CLF";
    readonly Clp: "CLP";
    readonly Cny: "CNY";
    readonly Cop: "COP";
    readonly Cou: "COU";
    readonly Crc: "CRC";
    readonly Cuc: "CUC";
    readonly Cup: "CUP";
    readonly Cve: "CVE";
    readonly Czk: "CZK";
    readonly Djf: "DJF";
    readonly Dkk: "DKK";
    readonly Dop: "DOP";
    readonly Dzd: "DZD";
    readonly Egp: "EGP";
    readonly Ern: "ERN";
    readonly Etb: "ETB";
    readonly Eur: "EUR";
    readonly Fjd: "FJD";
    readonly Fkp: "FKP";
    readonly Gbp: "GBP";
    readonly Gel: "GEL";
    readonly Ghs: "GHS";
    readonly Gip: "GIP";
    readonly Gmd: "GMD";
    readonly Gnf: "GNF";
    readonly Gtq: "GTQ";
    readonly Gyd: "GYD";
    readonly Hkd: "HKD";
    readonly Hnl: "HNL";
    readonly Hrk: "HRK";
    readonly Htg: "HTG";
    readonly Huf: "HUF";
    readonly Idr: "IDR";
    readonly Ils: "ILS";
    readonly Inr: "INR";
    readonly Iqd: "IQD";
    readonly Irr: "IRR";
    readonly Isk: "ISK";
    readonly Jmd: "JMD";
    readonly Jod: "JOD";
    readonly Jpy: "JPY";
    readonly Kes: "KES";
    readonly Kgs: "KGS";
    readonly Khr: "KHR";
    readonly Kmf: "KMF";
    readonly Kpw: "KPW";
    readonly Krw: "KRW";
    readonly Kwd: "KWD";
    readonly Kyd: "KYD";
    readonly Kzt: "KZT";
    readonly Lak: "LAK";
    readonly Lbp: "LBP";
    readonly Lkr: "LKR";
    readonly Lrd: "LRD";
    readonly Lsl: "LSL";
    readonly Ltl: "LTL";
    readonly Lvl: "LVL";
    readonly Lyd: "LYD";
    readonly Mad: "MAD";
    readonly Mdl: "MDL";
    readonly Mga: "MGA";
    readonly Mkd: "MKD";
    readonly Mmk: "MMK";
    readonly Mnt: "MNT";
    readonly Mop: "MOP";
    readonly Mro: "MRO";
    readonly Mur: "MUR";
    readonly Mvr: "MVR";
    readonly Mwk: "MWK";
    readonly Mxn: "MXN";
    readonly Mxv: "MXV";
    readonly Myr: "MYR";
    readonly Mzn: "MZN";
    readonly Nad: "NAD";
    readonly Ngn: "NGN";
    readonly Nio: "NIO";
    readonly Nok: "NOK";
    readonly Npr: "NPR";
    readonly Nzd: "NZD";
    readonly Omr: "OMR";
    readonly Pab: "PAB";
    readonly Pen: "PEN";
    readonly Pgk: "PGK";
    readonly Php: "PHP";
    readonly Pkr: "PKR";
    readonly Pln: "PLN";
    readonly Pyg: "PYG";
    readonly Qar: "QAR";
    readonly Ron: "RON";
    readonly Rsd: "RSD";
    readonly Rub: "RUB";
    readonly Rwf: "RWF";
    readonly Sar: "SAR";
    readonly Sbd: "SBD";
    readonly Scr: "SCR";
    readonly Sdg: "SDG";
    readonly Sek: "SEK";
    readonly Sgd: "SGD";
    readonly Shp: "SHP";
    readonly Sll: "SLL";
    readonly Sos: "SOS";
    readonly Srd: "SRD";
    readonly Ssp: "SSP";
    readonly Std: "STD";
    readonly Svc: "SVC";
    readonly Syp: "SYP";
    readonly Szl: "SZL";
    readonly Thb: "THB";
    readonly Tjs: "TJS";
    readonly Tmt: "TMT";
    readonly Tnd: "TND";
    readonly Top: "TOP";
    readonly Trc: "TRC";
    readonly Try: "TRY";
    readonly Ttd: "TTD";
    readonly Twd: "TWD";
    readonly Tzs: "TZS";
    readonly Uah: "UAH";
    readonly Ugx: "UGX";
    readonly Usd: "USD";
    readonly Usn: "USN";
    readonly Uss: "USS";
    readonly Uyi: "UYI";
    readonly Uyu: "UYU";
    readonly Uzs: "UZS";
    readonly Vef: "VEF";
    readonly Vnd: "VND";
    readonly Vuv: "VUV";
    readonly Wst: "WST";
    readonly Xaf: "XAF";
    readonly Xag: "XAG";
    readonly Xau: "XAU";
    readonly Xba: "XBA";
    readonly Xbb: "XBB";
    readonly Xbc: "XBC";
    readonly Xbd: "XBD";
    readonly Xcd: "XCD";
    readonly Xdr: "XDR";
    readonly Xof: "XOF";
    readonly Xpd: "XPD";
    readonly Xpf: "XPF";
    readonly Xpt: "XPT";
    readonly Xts: "XTS";
    readonly Xxx: "XXX";
    readonly Yer: "YER";
    readonly Zar: "ZAR";
    readonly Zmk: "ZMK";
    readonly Zmw: "ZMW";
    readonly Btc: "BTC";
    readonly Eth: "ETH";
};
/**
 * Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).
 */
export type Currency = OpenEnum<typeof Currency>;
export declare const Currency$zodSchema: z.ZodUnion<readonly [z.ZodEnum<{
    UNKNOWN_CURRENCY: "UNKNOWN_CURRENCY";
    AED: "AED";
    AFN: "AFN";
    ALL: "ALL";
    AMD: "AMD";
    ANG: "ANG";
    AOA: "AOA";
    ARS: "ARS";
    AUD: "AUD";
    AWG: "AWG";
    AZN: "AZN";
    BAM: "BAM";
    BBD: "BBD";
    BDT: "BDT";
    BGN: "BGN";
    BHD: "BHD";
    BIF: "BIF";
    BMD: "BMD";
    BND: "BND";
    BOB: "BOB";
    BOV: "BOV";
    BRL: "BRL";
    BSD: "BSD";
    BTN: "BTN";
    BWP: "BWP";
    BYR: "BYR";
    BZD: "BZD";
    CAD: "CAD";
    CDF: "CDF";
    CHE: "CHE";
    CHF: "CHF";
    CHW: "CHW";
    CLF: "CLF";
    CLP: "CLP";
    CNY: "CNY";
    COP: "COP";
    COU: "COU";
    CRC: "CRC";
    CUC: "CUC";
    CUP: "CUP";
    CVE: "CVE";
    CZK: "CZK";
    DJF: "DJF";
    DKK: "DKK";
    DOP: "DOP";
    DZD: "DZD";
    EGP: "EGP";
    ERN: "ERN";
    ETB: "ETB";
    EUR: "EUR";
    FJD: "FJD";
    FKP: "FKP";
    GBP: "GBP";
    GEL: "GEL";
    GHS: "GHS";
    GIP: "GIP";
    GMD: "GMD";
    GNF: "GNF";
    GTQ: "GTQ";
    GYD: "GYD";
    HKD: "HKD";
    HNL: "HNL";
    HRK: "HRK";
    HTG: "HTG";
    HUF: "HUF";
    IDR: "IDR";
    ILS: "ILS";
    INR: "INR";
    IQD: "IQD";
    IRR: "IRR";
    ISK: "ISK";
    JMD: "JMD";
    JOD: "JOD";
    JPY: "JPY";
    KES: "KES";
    KGS: "KGS";
    KHR: "KHR";
    KMF: "KMF";
    KPW: "KPW";
    KRW: "KRW";
    KWD: "KWD";
    KYD: "KYD";
    KZT: "KZT";
    LAK: "LAK";
    LBP: "LBP";
    LKR: "LKR";
    LRD: "LRD";
    LSL: "LSL";
    LTL: "LTL";
    LVL: "LVL";
    LYD: "LYD";
    MAD: "MAD";
    MDL: "MDL";
    MGA: "MGA";
    MKD: "MKD";
    MMK: "MMK";
    MNT: "MNT";
    MOP: "MOP";
    MRO: "MRO";
    MUR: "MUR";
    MVR: "MVR";
    MWK: "MWK";
    MXN: "MXN";
    MXV: "MXV";
    MYR: "MYR";
    MZN: "MZN";
    NAD: "NAD";
    NGN: "NGN";
    NIO: "NIO";
    NOK: "NOK";
    NPR: "NPR";
    NZD: "NZD";
    OMR: "OMR";
    PAB: "PAB";
    PEN: "PEN";
    PGK: "PGK";
    PHP: "PHP";
    PKR: "PKR";
    PLN: "PLN";
    PYG: "PYG";
    QAR: "QAR";
    RON: "RON";
    RSD: "RSD";
    RUB: "RUB";
    RWF: "RWF";
    SAR: "SAR";
    SBD: "SBD";
    SCR: "SCR";
    SDG: "SDG";
    SEK: "SEK";
    SGD: "SGD";
    SHP: "SHP";
    SLL: "SLL";
    SOS: "SOS";
    SRD: "SRD";
    SSP: "SSP";
    STD: "STD";
    SVC: "SVC";
    SYP: "SYP";
    SZL: "SZL";
    THB: "THB";
    TJS: "TJS";
    TMT: "TMT";
    TND: "TND";
    TOP: "TOP";
    TRC: "TRC";
    TRY: "TRY";
    TTD: "TTD";
    TWD: "TWD";
    TZS: "TZS";
    UAH: "UAH";
    UGX: "UGX";
    USD: "USD";
    USN: "USN";
    USS: "USS";
    UYI: "UYI";
    UYU: "UYU";
    UZS: "UZS";
    VEF: "VEF";
    VND: "VND";
    VUV: "VUV";
    WST: "WST";
    XAF: "XAF";
    XAG: "XAG";
    XAU: "XAU";
    XBA: "XBA";
    XBB: "XBB";
    XBC: "XBC";
    XBD: "XBD";
    XCD: "XCD";
    XDR: "XDR";
    XOF: "XOF";
    XPD: "XPD";
    XPF: "XPF";
    XPT: "XPT";
    XTS: "XTS";
    XXX: "XXX";
    YER: "YER";
    ZAR: "ZAR";
    ZMK: "ZMK";
    ZMW: "ZMW";
    BTC: "BTC";
    ETH: "ETH";
}>, z.ZodPipe<z.ZodString, z.ZodTransform<import("../types/enums.js").Unrecognized<string>, string>>]>;
//# sourceMappingURL=currency.d.ts.map