/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
import { PassThroughBody$zodSchema, } from "./passthroughbody.js";
export const CustomObjectSchemaType = {
    String: "string",
    Number: "number",
    Integer: "integer",
    Boolean: "boolean",
    Date: "date",
    Datetime: "datetime",
    Currency: "currency",
    Email: "email",
    Phone: "phone",
    Reference: "reference",
    Select: "select",
    Multiselect: "multiselect",
};
export const CustomObjectSchemaType$zodSchema = z.union([
    z.enum([
        "string",
        "number",
        "integer",
        "boolean",
        "date",
        "datetime",
        "currency",
        "email",
        "phone",
        "reference",
        "select",
        "multiselect",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]);
export const CustomObjectSchemaOption$zodSchema = z.object({
    label: z.string().optional(),
    value: z.string().optional(),
});
export const CustomObjectSchemaField$zodSchema = z.object({
    default_value: z.string().nullable().optional().describe("Default value for the field"),
    description: z.string().nullable().optional(),
    id: z.string().optional(),
    name: z.string().optional(),
    options: z.array(z.lazy(() => CustomObjectSchemaOption$zodSchema)).nullable()
        .optional().describe("Options for select and multiselect types"),
    required: z.boolean().optional(),
    type: CustomObjectSchemaType$zodSchema.optional(),
});
export const CustomObjectSchema$zodSchema = z
    .object({
    active: z.boolean().nullable().optional().describe("Whether the custom object schema is active"),
    created_at: z.string().nullable().optional().describe("The timestamp when the custom object schema was created"),
    created_by: z.string().nullable().optional().describe("The ID of the user who created the custom object schema"),
    description: z.string().nullable().optional().describe("The description of the custom object schema"),
    fields: z.array(z.lazy(() => CustomObjectSchemaField$zodSchema)).optional()
        .describe("The fields defined in the schema"),
    id: z.string().optional().describe("The unique identifier of the custom object schema"),
    name: z.string().nullable().optional().describe("The name of the custom object schema"),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    updated_at: z.string().nullable().optional().describe("The timestamp when the custom object schema was last updated"),
    updated_by: z.string().nullable().optional().describe("The ID of the user who last updated the custom object schema"),
    visible: z.boolean().nullable().optional().describe("Whether the custom object schema is visible in the UI"),
});
export const CustomObjectSchemaInput$zodSchema = z.object({
    active: z.boolean().nullable().optional().describe("Whether the custom object schema is active"),
    description: z.string().nullable().optional().describe("The description of the custom object schema"),
    fields: z.array(z.lazy(() => CustomObjectSchemaField$zodSchema)).optional()
        .describe("The fields defined in the schema"),
    name: z.string().nullable().optional().describe("The name of the custom object schema"),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    visible: z.boolean().nullable().optional().describe("Whether the custom object schema is visible in the UI"),
});
//# sourceMappingURL=customobjectschema.js.map