/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { PassThroughBody$zodSchema, } from "./passthroughbody.js";
export const DriveGroup$zodSchema = z.object({
    created_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was created."),
    created_by: z.string().nullable().optional().describe("The user who created the object."),
    custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe("When custom mappings are configured on the resource, the result is included here."),
    description: z.string().nullable().optional().describe("A description of the object."),
    display_name: z.string().nullable().optional().describe("The display name of the drive group"),
    id: z.string().describe("A unique identifier for an object."),
    name: z.string().describe("The name of the drive group"),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was last updated."),
    updated_by: z.string().nullable().optional().describe("The user who last updated the object."),
});
//# sourceMappingURL=drivegroup.js.map