/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const EcommerceOrdersFilter$zodSchema = z.object({
    created_since: z.string().optional().describe("Minimum date the order was created"),
    customer_id: z.string().optional().describe("Customer id to filter on"),
    email: z.string().optional().describe("Customer email address to filter on"),
    updated_since: z.string().optional().describe("Minimum date the order was last modified"),
});
//# sourceMappingURL=ecommerceordersfilter.js.map