/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
import { Currency$zodSchema } from "./currency.js";
import { Email$zodSchema } from "./email.js";
import { LinkedEcommerceOrder$zodSchema, } from "./linkedecommerceorder.js";
import { PhoneNumber$zodSchema } from "./phonenumber.js";
/**
 * The current status of the customer
 */
export const EcommerceCustomerCustomerStatus = {
    Active: "active",
    Archived: "archived",
};
export const EcommerceCustomerCustomerStatus$zodSchema = z.union([
    z.enum([
        "active",
        "archived",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("The current status of the customer");
export const EcommerceCustomerType = {
    Billing: "billing",
    Shipping: "shipping",
    Other: "other",
};
export const EcommerceCustomerType$zodSchema = z.union([
    z.enum([
        "billing",
        "shipping",
        "other",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]);
export const EcommerceCustomerAddress$zodSchema = z.object({
    city: z.string().nullable().optional().describe("City of the customer"),
    country: z.string().nullable().optional().describe("Country of the customer"),
    id: z.string().nullable().optional().describe("A unique identifier for an object."),
    line1: z.string().nullable().optional().describe("First line of the street address of the customer"),
    line2: z.string().nullable().optional().describe("Second line of the street address of the customer"),
    postal_code: z.string().nullable().optional().describe("Postal code of the customer"),
    state: z.string().nullable().optional().describe("State of the customer"),
    type: EcommerceCustomerType$zodSchema.optional(),
});
export const EcommerceCustomer$zodSchema = z
    .object({
    addresses: z.array(z.lazy(() => EcommerceCustomerAddress$zodSchema))
        .optional().describe("An array of addresses for the customer."),
    company_name: z.string().nullable().optional().describe("Company name of the customer"),
    created_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was created."),
    currency: Currency$zodSchema.nullable().optional().describe("Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)."),
    custom_mappings: z.record(z.string(), z.any()).nullable().optional()
        .describe("When custom mappings are configured on the resource, the result is included here."),
    emails: z.array(Email$zodSchema).nullable().optional().describe("An array of email addresses for the customer."),
    first_name: z.string().nullable().optional().describe("First name of the customer"),
    id: z.string().describe("A unique identifier for an object."),
    last_name: z.string().nullable().optional().describe("Last name of the customer"),
    name: z.string().nullable().optional().describe("Full name of the customer"),
    orders: z.array(LinkedEcommerceOrder$zodSchema).optional(),
    phone_numbers: z.array(PhoneNumber$zodSchema).nullable().optional()
        .describe("An array of phone numbers for the customer."),
    status: EcommerceCustomerCustomerStatus$zodSchema.nullable().optional()
        .describe("The current status of the customer"),
    updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was last updated."),
});
//# sourceMappingURL=ecommercecustomer.js.map