/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
/**
 * Email type
 */
export const EmailType = {
    Primary: "primary",
    Secondary: "secondary",
    Work: "work",
    Personal: "personal",
    Billing: "billing",
    Other: "other",
};
export const EmailType$zodSchema = z.union([
    z.enum([
        "primary",
        "secondary",
        "work",
        "personal",
        "billing",
        "other",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("Email type");
export const Email$zodSchema = z.object({
    email: z.string().nullable().describe("Email address"),
    id: z.string().nullable().optional().describe("Unique identifier for the email address"),
    type: EmailType$zodSchema.nullable().optional().describe("Email type"),
});
//# sourceMappingURL=email.js.map