/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { Currency$zodSchema } from "./currency.js";
import { LinkedCustomer$zodSchema } from "./linkedcustomer.js";
import { LinkedDepartment$zodSchema, } from "./linkeddepartment.js";
import { LinkedExpenseCategory$zodSchema, } from "./linkedexpensecategory.js";
import { LinkedLedgerAccount$zodSchema, } from "./linkedledgeraccount.js";
import { LinkedLocation$zodSchema } from "./linkedlocation.js";
import { LinkedTaxRate$zodSchema } from "./linkedtaxrate.js";
import { LinkedTrackingCategory$zodSchema, } from "./linkedtrackingcategory.js";
export const ExpenseReportLineItem$zodSchema = z.object({
    account: LinkedLedgerAccount$zodSchema.nullable().optional(),
    amount: z.number().describe("The amount of the expense line item."),
    billable: z.boolean().nullable().optional().describe("Whether the expense is billable to a customer."),
    created_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was created."),
    created_by: z.string().nullable().optional().describe("The user who created the object."),
    currency: Currency$zodSchema.nullable().optional().describe("Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)."),
    customer: LinkedCustomer$zodSchema.nullable().optional().describe("The customer this entity is linked to."),
    department: LinkedDepartment$zodSchema.nullable().optional(),
    description: z.string().nullable().optional().describe("The description of the expense line item."),
    expense_category: LinkedExpenseCategory$zodSchema.optional().describe("The expense category this entity is linked to."),
    id: z.string().optional().describe("A unique identifier for an object."),
    line_number: z.int().nullable().optional().describe("Line number of the resource"),
    location: LinkedLocation$zodSchema.nullable().optional(),
    quantity: z.number().nullable().optional(),
    receipt_url: z.string().nullable().optional().describe("URL to the receipt or attachment for this expense line."),
    reimbursable: z.boolean().nullable().optional().describe("Whether the expense is reimbursable to the employee."),
    tax_amount: z.number().nullable().optional().describe("Tax amount"),
    tax_rate: LinkedTaxRate$zodSchema.optional(),
    total_amount: z.number().nullable().optional().describe("The total amount of the expense line item including tax."),
    tracking_categories: z.array(LinkedTrackingCategory$zodSchema.nullable())
        .nullable().optional().describe("A list of linked tracking categories."),
    transaction_date: z.string().date().nullable().optional().describe("The date of the individual expense."),
    unit_price: z.number().nullable().optional(),
    updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe("The date and time when the object was last updated."),
    updated_by: z.string().nullable().optional().describe("The user who last updated the object."),
});
//# sourceMappingURL=expensereportlineitem.js.map