/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
import { SortDirection$zodSchema } from "./sortdirection.js";
/**
 * The field on which to sort the Files
 */
export const FilesSortBy = {
    CreatedAt: "created_at",
    UpdatedAt: "updated_at",
    Name: "name",
};
export const FilesSortBy$zodSchema = z.union([
    z.enum([
        "created_at",
        "updated_at",
        "name",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("The field on which to sort the Files");
export const FilesSort$zodSchema = z.object({
    by: FilesSortBy$zodSchema.optional().describe("The field on which to sort the Files"),
    direction: SortDirection$zodSchema.default("asc").describe("The direction in which to sort the results"),
});
//# sourceMappingURL=filessort.js.map