/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { PassThroughBody$zodSchema, } from "./passthroughbody.js";
export const FilesSearch$zodSchema = z.object({
    drive_id: z.string().optional().describe("ID of the drive to filter on"),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    query: z.string().describe("The query to search for. May match across multiple fields."),
});
//# sourceMappingURL=filessearch.js.map