/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { BadRequestResponse$zodSchema, } from "./badrequestresponse.js";
import { DriveInput$zodSchema } from "./driveinput.js";
import { NotFoundResponse$zodSchema, } from "./notfoundresponse.js";
import { PaymentRequiredResponse$zodSchema, } from "./paymentrequiredresponse.js";
import { UnauthorizedResponse$zodSchema, } from "./unauthorizedresponse.js";
import { UnexpectedErrorResponse$zodSchema, } from "./unexpectederrorresponse.js";
import { UnprocessableResponse$zodSchema, } from "./unprocessableresponse.js";
import { UpdateDriveResponse$zodSchema, } from "./updatedriveresponse.js";
export const FileStorageDrivesUpdateGlobals$zodSchema = z.object({
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
});
export const FileStorageDrivesUpdateRequest$zodSchema = z.object({
    body: DriveInput$zodSchema,
    id: z.string().describe("ID of the record you are acting upon."),
    raw: z.boolean().default(false).describe("Include raw response. Mostly used for debugging purposes"),
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
    xApideckServiceId: z.string().describe("Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.").optional(),
});
export const FileStorageDrivesUpdateResponse$zodSchema = z.union([
    UpdateDriveResponse$zodSchema,
    BadRequestResponse$zodSchema,
    UnauthorizedResponse$zodSchema,
    PaymentRequiredResponse$zodSchema,
    NotFoundResponse$zodSchema,
    UnprocessableResponse$zodSchema,
    UnexpectedErrorResponse$zodSchema,
]);
//# sourceMappingURL=filestoragedrivesupdateop.js.map