/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { AccountingBankAccount$zodSchema, } from "./accountingbankaccount.js";
export const GetBankAccountResponse$zodSchema = z.object({
    data: AccountingBankAccount$zodSchema,
    operation: z.string().optional().describe("Operation performed"),
    resource: z.string().optional().describe("Unified API resource name"),
    service: z.string().optional().describe("Apideck ID of service provider"),
    status: z.string().describe("HTTP Response Status"),
    status_code: z.int().describe("HTTP Response Status Code"),
}).describe("Bank Account");
//# sourceMappingURL=getbankaccountresponse.js.map