/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { CustomFieldFinder$zodSchema, } from "./customfieldfinder.js";
export const GetCustomFieldsResponse$zodSchema = z.object({
    _raw: z.record(z.string(), z.any()).nullable().optional().describe("Raw response from the integration when raw=true query param is provided"),
    data: z.array(CustomFieldFinder$zodSchema),
    status: z.string().describe("HTTP Response Status"),
    status_code: z.int().describe("HTTP Response Status Code"),
}).describe("Custom mapping");
//# sourceMappingURL=getcustomfieldsresponse.js.map