/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { CreditNote$zodSchema } from "./creditnote.js";
export const GetCreditNoteResponse$zodSchema = z.object({
    _raw: z.record(z.string(), z.any()).nullable().optional().describe("Raw response from the integration when raw=true query param is provided"),
    data: CreditNote$zodSchema,
    operation: z.string().describe("Operation performed"),
    resource: z.string().describe("Unified API resource name"),
    service: z.string().describe("Apideck ID of service provider"),
    status: z.string().describe("HTTP Response Status"),
    status_code: z.int().describe("HTTP Response Status Code"),
}).describe("Credit Note");
//# sourceMappingURL=getcreditnoteresponse.js.map