/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { CollectionTicketComment$zodSchema, } from "./collectionticketcomment.js";
export const GetCommentResponse$zodSchema = z
    .object({
    _raw: z.record(z.string(), z.any()).nullable().optional().describe("Raw response from the integration when raw=true query param is provided"),
    data: CollectionTicketComment$zodSchema,
    operation: z.string().describe("Operation performed"),
    resource: z.string().describe("Unified API resource name"),
    service: z.string().describe("Apideck ID of service provider"),
    status: z.string().describe("HTTP Response Status"),
    status_code: z.int().describe("HTTP Response Status Code"),
}).describe("Get a Comment");
//# sourceMappingURL=getcommentresponse.js.map