/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { CustomMapping$zodSchema } from "./custommapping.js";
export const GetCustomMappingsResponse$zodSchema = z.object({
    _raw: z.record(z.string(), z.any()).nullable().optional().describe("Raw response from the integration when raw=true query param is provided"),
    data: z.array(CustomMapping$zodSchema),
    status: z.string().describe("HTTP Response Status"),
    status_code: z.int().describe("HTTP Response Status Code"),
}).describe("Custom mapping");
//# sourceMappingURL=getcustommappingsresponse.js.map