/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { BadRequestResponse$zodSchema, } from "./badrequestresponse.js";
import { GetCollectionUsersResponse$zodSchema, } from "./getcollectionusersresponse.js";
import { NotFoundResponse$zodSchema, } from "./notfoundresponse.js";
import { PaymentRequiredResponse$zodSchema, } from "./paymentrequiredresponse.js";
import { UnauthorizedResponse$zodSchema, } from "./unauthorizedresponse.js";
import { UnexpectedErrorResponse$zodSchema, } from "./unexpectederrorresponse.js";
import { UnprocessableResponse$zodSchema, } from "./unprocessableresponse.js";
export const IssueTrackingCollectionUsersAllGlobals$zodSchema = z.object({
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
});
export const IssueTrackingCollectionUsersAllRequest$zodSchema = z.object({
    collection_id: z.string().describe("The collection ID"),
    cursor: z.string().describe("Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response.").nullable().optional(),
    fields: z.string().describe("The 'fields' parameter allows API users to specify the fields they want to include in the API response. If this parameter is not present, the API will return all available fields. If this parameter is present, only the fields specified in the comma-separated string will be included in the response. Nested properties can also be requested by using a dot notation. <br /><br />Example: `fields=name,email,addresses.city`<br /><br />In the example above, the response will only include the fields \"name\", \"email\" and \"addresses.city\". If any other fields are available, they will be excluded.").nullable().optional(),
    limit: z.int().default(20).describe("Number of results to return. Minimum 1, Maximum 200, Default 20"),
    pass_through: z.record(z.string(), z.any()).describe("Optional unmapped key/values that will be passed through to downstream as query parameters. Ie: ?pass_through[search]=leads becomes ?search=leads").optional(),
    raw: z.boolean().default(false).describe("Include raw response. Mostly used for debugging purposes"),
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
    xApideckServiceId: z.string().describe("Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.").optional(),
});
export const IssueTrackingCollectionUsersAllResponseResult$zodSchema = z.union([
    GetCollectionUsersResponse$zodSchema,
    BadRequestResponse$zodSchema,
    UnauthorizedResponse$zodSchema,
    PaymentRequiredResponse$zodSchema,
    NotFoundResponse$zodSchema,
    UnprocessableResponse$zodSchema,
    UnexpectedErrorResponse$zodSchema,
]);
export const IssueTrackingCollectionUsersAllResponse$zodSchema = z.object({
    Result: z.union([
        GetCollectionUsersResponse$zodSchema,
        BadRequestResponse$zodSchema,
        UnauthorizedResponse$zodSchema,
        PaymentRequiredResponse$zodSchema,
        NotFoundResponse$zodSchema,
        UnprocessableResponse$zodSchema,
        UnexpectedErrorResponse$zodSchema,
    ]),
});
//# sourceMappingURL=issuetrackingcollectionusersallop.js.map