/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { BadRequestResponse$zodSchema, } from "./badrequestresponse.js";
import { NotFoundResponse$zodSchema, } from "./notfoundresponse.js";
import { PaymentRequiredResponse$zodSchema, } from "./paymentrequiredresponse.js";
import { TicketInput$zodSchema } from "./ticket.js";
import { UnauthorizedResponse$zodSchema, } from "./unauthorizedresponse.js";
import { UnexpectedErrorResponse$zodSchema, } from "./unexpectederrorresponse.js";
import { UnprocessableResponse$zodSchema, } from "./unprocessableresponse.js";
import { UpdateTicketResponse$zodSchema, } from "./updateticketresponse.js";
export const IssueTrackingCollectionTicketsUpdateGlobals$zodSchema = z.object({
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
});
export const IssueTrackingCollectionTicketsUpdateRequest$zodSchema = z.object({
    body: TicketInput$zodSchema,
    collection_id: z.string().describe("The collection ID"),
    raw: z.boolean().default(false).describe("Include raw response. Mostly used for debugging purposes"),
    ticket_id: z.string().describe("ID of the ticket you are acting upon."),
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
    xApideckServiceId: z.string().describe("Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.").optional(),
});
export const IssueTrackingCollectionTicketsUpdateResponse$zodSchema = z.union([
    UpdateTicketResponse$zodSchema,
    BadRequestResponse$zodSchema,
    UnauthorizedResponse$zodSchema,
    PaymentRequiredResponse$zodSchema,
    NotFoundResponse$zodSchema,
    UnprocessableResponse$zodSchema,
    UnexpectedErrorResponse$zodSchema,
]);
//# sourceMappingURL=issuetrackingcollectionticketsupdateop.js.map