/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
export const JournalEntriesFilterStatus = {
    Draft: "draft",
    PendingApproval: "pending_approval",
    Approved: "approved",
    Posted: "posted",
    Voided: "voided",
    Rejected: "rejected",
    Deleted: "deleted",
    Other: "other",
};
export const JournalEntriesFilterStatus$zodSchema = z.union([
    z.enum([
        "draft",
        "pending_approval",
        "approved",
        "posted",
        "voided",
        "rejected",
        "deleted",
        "other",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]);
export const JournalEntriesFilter$zodSchema = z
    .object({
    status: JournalEntriesFilterStatus$zodSchema.optional(),
    updated_since: z.iso.datetime({ offset: true }).optional(),
});
//# sourceMappingURL=journalentriesfilter.js.map