import * as z from "zod";
import { Address } from "./address.js";
import { Currency } from "./currency.js";
import { CustomFieldUnion } from "./customfieldunion.js";
import { Email } from "./email.js";
import { PassThroughBody } from "./passthroughbody.js";
import { PhoneNumber } from "./phonenumber.js";
import { SocialLink } from "./sociallink.js";
import { Website } from "./website.js";
export type Lead = {
    id?: string | undefined;
    name: string;
    company_name?: string | null | undefined;
    owner_id?: string | null | undefined;
    owner_name?: string | null | undefined;
    company_id?: string | null | undefined;
    contact_id?: string | null | undefined;
    lead_id?: string | null | undefined;
    lead_source?: string | null | undefined;
    first_name?: string | null | undefined;
    last_name?: string | null | undefined;
    description?: string | null | undefined;
    prefix?: string | null | undefined;
    title?: string | null | undefined;
    language?: string | null | undefined;
    status?: string | null | undefined;
    monetary_amount?: number | null | undefined;
    currency?: Currency | null | undefined;
    fax?: string | null | undefined;
    websites?: Array<Website> | undefined;
    addresses?: Array<Address> | undefined;
    social_links?: Array<SocialLink> | undefined;
    phone_numbers?: Array<PhoneNumber> | undefined;
    emails?: Array<Email> | undefined;
    custom_fields?: Array<CustomFieldUnion> | null | undefined;
    tags?: Array<string> | null | undefined;
    custom_mappings?: {
        [k: string]: any;
    } | null | undefined;
    updated_at?: string | null | undefined;
    created_at?: string | null | undefined;
    pass_through?: Array<PassThroughBody> | undefined;
};
export declare const Lead$zodSchema: z.ZodType<Lead>;
//# sourceMappingURL=lead.d.ts.map