/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
/**
 * Line Item type
 */
export const LineItemType = {
    ExpenseItem: "expense_item",
    ExpenseAccount: "expense_account",
    Other: "other",
};
export const LineItemType$zodSchema = z.union([
    z.enum([
        "expense_item",
        "expense_account",
        "other",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("Line Item type");
//# sourceMappingURL=lineitemtype.js.map