/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const LinkedSubsidiary$zodSchema = z.object({
    display_id: z.string().nullable().optional().describe("Id to be displayed."),
    id: z.string().optional().describe("A unique identifier for an object."),
    name: z.string().nullable().optional().describe("The name of the resource."),
});
//# sourceMappingURL=linkedsubsidiary.js.map