/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const LinkedTaxStatusDetail$zodSchema = z.object({
    country: z.string().optional().describe("The country of the tax status."),
    transaction_tax_status: z.string().nullable().optional().describe("The transaction tax status."),
});
//# sourceMappingURL=linkedtaxstatusdetail.js.map