/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const LinkedEmployee$zodSchema = z.object({
    display_id: z.string().nullable().optional().describe("The display ID of the employee. For best performance, send this field (the employee number) instead of the GUID in the id field."),
    display_name: z.string().nullable().optional().describe("The display name of the employee."),
    id: z.string().optional().describe("A unique identifier for an object."),
}).describe("The employee this entity is linked to.");
//# sourceMappingURL=linkedemployee.js.map