/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const LinkedLedgerAccount$zodSchema = z
    .object({
    code: z.string().nullable().optional().describe("The code assigned to the account."),
    display_id: z.string().nullable().optional().describe("The display ID of the account."),
    id: z.string().optional().describe("The unique identifier for the account."),
    name: z.string().nullable().optional().describe("The name of the account."),
    nominal_code: z.string().nullable().optional().describe("The nominal code of the account."),
    parent_id: z.string().nullable().optional().describe("The parent ID of the account."),
});
//# sourceMappingURL=linkedledgeraccount.js.map