/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const Owner$zodSchema = z.object({
    email: z.string().nullable().optional().describe("Email of the owner"),
    id: z.string().optional().describe("ID of the owner"),
    name: z.string().nullable().optional().describe("Name of the owner"),
});
//# sourceMappingURL=owner.js.map