import * as z from "zod";
import { AllocationInput } from "./allocation.js";
import { Currency } from "./currency.js";
import { CustomFieldUnion } from "./customfieldunion.js";
import { DeprecatedLinkedSupplierInput } from "./deprecatedlinkedsupplierinput.js";
import { LinkedCustomerInput } from "./linkedcustomerinput.js";
import { LinkedLedgerAccount } from "./linkedledgeraccount.js";
import { LinkedTrackingCategory } from "./linkedtrackingcategory.js";
import { PassThroughBody } from "./passthroughbody.js";
import { PaymentStatus } from "./paymentstatus.js";
import { PaymentType } from "./paymenttype.js";
export type PaymentInput = {
    currency?: Currency | null | undefined;
    currency_rate?: number | null | undefined;
    total_amount: number | null;
    reference?: string | null | undefined;
    payment_method?: string | null | undefined;
    payment_method_reference?: string | null | undefined;
    payment_method_id?: string | null | undefined;
    accounts_receivable_account_type?: string | null | undefined;
    accounts_receivable_account_id?: string | null | undefined;
    account?: LinkedLedgerAccount | null | undefined;
    transaction_date: string | null;
    customer?: LinkedCustomerInput | null | undefined;
    supplier?: DeprecatedLinkedSupplierInput | null | undefined;
    company_id?: string | null | undefined;
    reconciled?: boolean | null | undefined;
    status?: PaymentStatus | undefined;
    type?: PaymentType | undefined;
    allocations?: Array<AllocationInput> | undefined;
    note?: string | null | undefined;
    number?: string | null | undefined;
    tracking_categories?: Array<LinkedTrackingCategory | null> | null | undefined;
    custom_fields?: Array<CustomFieldUnion> | undefined;
    row_version?: string | null | undefined;
    display_id?: string | null | undefined;
    pass_through?: Array<PassThroughBody> | undefined;
};
export declare const PaymentInput$zodSchema: z.ZodType<PaymentInput>;
//# sourceMappingURL=paymentinput.d.ts.map