/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { AllocationInput$zodSchema } from "./allocation.js";
import { Currency$zodSchema } from "./currency.js";
import { CustomFieldUnion$zodSchema, } from "./customfieldunion.js";
import { DeprecatedLinkedSupplierInput$zodSchema, } from "./deprecatedlinkedsupplierinput.js";
import { LinkedCustomerInput$zodSchema, } from "./linkedcustomerinput.js";
import { LinkedLedgerAccount$zodSchema, } from "./linkedledgeraccount.js";
import { LinkedTrackingCategory$zodSchema, } from "./linkedtrackingcategory.js";
import { PassThroughBody$zodSchema, } from "./passthroughbody.js";
import { PaymentStatus$zodSchema } from "./paymentstatus.js";
import { PaymentType$zodSchema } from "./paymenttype.js";
export const PaymentInput$zodSchema = z.object({
    account: LinkedLedgerAccount$zodSchema.nullable().optional(),
    accounts_receivable_account_id: z.string().nullable().optional().describe("Unique identifier for the account to allocate payment to."),
    accounts_receivable_account_type: z.string().nullable().optional().describe("Type of accounts receivable account."),
    allocations: z.array(AllocationInput$zodSchema).optional(),
    company_id: z.string().nullable().optional().describe("The company ID the transaction belongs to"),
    currency: Currency$zodSchema.nullable().optional().describe("Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)."),
    currency_rate: z.number().nullable().optional().describe("Currency Exchange Rate at the time entity was recorded/generated."),
    custom_fields: z.array(CustomFieldUnion$zodSchema).optional(),
    customer: LinkedCustomerInput$zodSchema.nullable().optional().describe("The customer this entity is linked to."),
    display_id: z.string().nullable().optional().describe("Id to be displayed."),
    note: z.string().nullable().optional().describe("Note associated with the transaction"),
    number: z.string().nullable().optional().describe("Number associated with the transaction"),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    payment_method: z.string().nullable().optional().describe("Payment method used for the transaction, such as cash, credit card, bank transfer, or check"),
    payment_method_id: z.string().nullable().optional().describe("A unique identifier for an object."),
    payment_method_reference: z.string().nullable().optional().describe("Optional reference message returned by payment method on processing"),
    reconciled: z.boolean().nullable().optional().describe("Indicates if the transaction has been reconciled."),
    reference: z.string().nullable().optional().describe("Optional transaction reference message ie: Debit remittance detail."),
    row_version: z.string().nullable().optional().describe("A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object."),
    status: PaymentStatus$zodSchema.optional().describe("Status of payment"),
    supplier: DeprecatedLinkedSupplierInput$zodSchema.nullable().optional()
        .describe("The supplier this entity is linked to."),
    total_amount: z.number().nullable().describe("The total amount of the transaction or record"),
    tracking_categories: z.array(LinkedTrackingCategory$zodSchema.nullable())
        .nullable().optional().describe("A list of linked tracking categories."),
    transaction_date: z.iso.datetime({ offset: true }).nullable().describe("The date of the transaction - YYYY:MM::DDThh:mm:ss.sTZD"),
    type: PaymentType$zodSchema.optional().describe("Type of payment"),
});
//# sourceMappingURL=paymentinput.js.map