/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { Currency$zodSchema } from "./currency.js";
import { PassThroughBody$zodSchema, } from "./passthroughbody.js";
export const StageInput$zodSchema = z.object({
    archived: z.boolean().nullable().optional().describe("Whether the Pipeline Stage is archived or not."),
    display_order: z.int().nullable().optional().describe("The order in which the Pipeline Stage is displayed in the UI."),
    name: z.string().nullable().optional().describe("The name of the Pipeline Stage."),
    value: z.string().nullable().optional().describe("The value of the Pipeline Stage."),
    win_probability: z.int().nullable().optional().describe("The expected probability of winning an Opportunity in this Pipeline Stage. Valid values are [0-100]."),
});
export const PipelineInput$zodSchema = z.object({
    active: z.boolean().optional().describe("Whether the Pipeline is active or not."),
    archived: z.boolean().optional().describe("Whether the Pipeline is archived or not."),
    currency: Currency$zodSchema.nullable().optional().describe("Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217)."),
    display_order: z.int().nullable().optional().describe("The order in which the Pipeline is displayed in the UI."),
    id: z.string().optional().describe("The unique identifier of the Pipeline."),
    name: z.string().describe("The name of the Pipeline."),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    stages: z.array(z.lazy(() => StageInput$zodSchema)).optional().describe("The Pipeline Stages."),
    win_probability_enabled: z.boolean().optional().describe("Whether the Pipeline has win probability enabled or not."),
});
//# sourceMappingURL=pipelineinput.js.map