import * as z from "zod";
import { Address } from "./address.js";
import { AllocationInput } from "./allocation.js";
import { Currency } from "./currency.js";
import { CustomFieldUnion } from "./customfieldunion.js";
import { InvoiceLineItemInput } from "./invoicelineitem.js";
import { LinkedCustomerInput } from "./linkedcustomerinput.js";
import { LinkedDepartmentInput } from "./linkeddepartmentinput.js";
import { LinkedLedgerAccount } from "./linkedledgeraccount.js";
import { LinkedLocationInput } from "./linkedlocationinput.js";
import { LinkedTrackingCategory } from "./linkedtrackingcategory.js";
import { PassThroughBody } from "./passthroughbody.js";
import { RefundStatus } from "./refundstatus.js";
import { RefundType } from "./refundtype.js";
export type RefundInput = {
    number?: string | null | undefined;
    customer?: LinkedCustomerInput | null | undefined;
    company_id?: string | null | undefined;
    currency?: Currency | null | undefined;
    currency_rate?: number | null | undefined;
    tax_inclusive?: boolean | null | undefined;
    sub_total?: number | null | undefined;
    total_amount: number | null;
    total_tax?: number | null | undefined;
    refund_date?: string | null | undefined;
    status?: RefundStatus | undefined;
    type?: RefundType | undefined;
    payment_method?: string | null | undefined;
    payment_method_reference?: string | null | undefined;
    payment_method_id?: string | null | undefined;
    account?: LinkedLedgerAccount | null | undefined;
    line_items?: Array<InvoiceLineItemInput> | undefined;
    allocations?: Array<AllocationInput> | undefined;
    tax_code?: string | null | undefined;
    discount_percentage?: number | null | undefined;
    discount_amount?: number | null | undefined;
    note?: string | null | undefined;
    customer_memo?: string | null | undefined;
    reference?: string | null | undefined;
    billing_address?: Address | undefined;
    shipping_address?: Address | undefined;
    department?: LinkedDepartmentInput | null | undefined;
    location?: LinkedLocationInput | null | undefined;
    tracking_categories?: Array<LinkedTrackingCategory | null> | null | undefined;
    custom_fields?: Array<CustomFieldUnion> | undefined;
    row_version?: string | null | undefined;
    pass_through?: Array<PassThroughBody> | undefined;
};
export declare const RefundInput$zodSchema: z.ZodType<RefundInput>;
//# sourceMappingURL=refundinput.d.ts.map