/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const RequestCountAllocation$zodSchema = z.object({
    proxy: z.number().optional(),
    unify: z.number().optional(),
    vault: z.number().optional(),
});
//# sourceMappingURL=requestcountallocation.js.map