/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
import { ConsumerMetadata$zodSchema, } from "./consumermetadata.js";
import { UnifiedApiId$zodSchema } from "./unifiedapiid.js";
export const AllowAction = {
    Delete: "delete",
    Disconnect: "disconnect",
    Reauthorize: "reauthorize",
    Disable: "disable",
};
export const AllowAction$zodSchema = z.union([
    z.enum([
        "delete",
        "disconnect",
        "reauthorize",
        "disable",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]);
export const Settings$zodSchema = z.object({
    allow_actions: z.array(AllowAction$zodSchema).optional().describe("Hide actions from your users in [Vault](/apis/vault/reference#section/Get-Started). Actions in `allow_actions` will be shown on a connection in Vault.\nAvailable actions are: `delete`, `disconnect`, `reauthorize` and `disable`.\nEmpty array will hide all actions. By default all actions are visible."),
    auto_redirect: z.boolean().default(false).describe("Automatically redirect to redirect uri after the connection has been configured as callable. Defaults to `false`."),
    hide_guides: z.boolean().default(false).describe("Hide Apideck connection guides in [Vault](/apis/vault/reference#section/Get-Started). Defaults to `false`."),
    hide_resource_settings: z.boolean().default(false).describe("A boolean that controls the display of the configurable resources for an integration. When set to true, the resource configuration options will be hidden and not shown to the user. When set to false, the resource configuration options will be displayed to the user."),
    isolation_mode: z.boolean().default(false).describe("Configure [Vault](/apis/vault/reference#section/Get-Started) to run in isolation mode, meaning it only shows the connection settings and hides the navigation items."),
    sandbox_mode: z.boolean().default(false).describe("Configure [Vault](/apis/vault/reference#section/Get-Started) to show a banner informing the logged in user is in a test environment."),
    session_length: z.string().default("1h").describe("The duration of time the session is valid for (maximum 1 week)."),
    show_logs: z.boolean().default(true).describe("Configure [Vault](/apis/vault/reference#section/Get-Started) to show the logs page. Defaults to `true`."),
    show_sidebar: z.boolean().default(true).describe("Configure [Vault](/apis/vault/reference#section/Get-Started) to show the sidebar. Defaults to `true`."),
    show_suggestions: z.boolean().default(false).describe("Configure [Vault](/apis/vault/reference#section/Get-Started) to show the suggestions page. Defaults to `false`."),
    unified_apis: z.array(UnifiedApiId$zodSchema).optional().describe("Provide the IDs of the Unified APIs you want to be visible. Leaving it empty or omitting this field will show all Unified APIs."),
}).describe("Settings to change the way the Vault is displayed.");
export const Theme$zodSchema = z.object({
    favicon: z.string().optional().describe("The URL to the favicon to use for Vault."),
    logo: z.string().optional().describe("The URL to the logo to use for Vault."),
    primary_color: z.string().optional().describe("The primary color to use for Vault."),
    privacy_url: z.string().optional().describe("The URL to the privacy policy that will be shown in the sidebar."),
    sidepanel_background_color: z.string().optional().describe("The background color to use for the sidebar."),
    sidepanel_text_color: z.string().optional().describe("The text color to use for the sidebar."),
    terms_url: z.string().optional().describe("The URL to the terms and conditions that will be shown in the sidebar."),
    vault_name: z.string().optional().describe("The name that will be shown in the sidebar."),
}).describe("Theming options to change the look and feel of Vault.");
export const Session$zodSchema = z.object({
    consumer_metadata: ConsumerMetadata$zodSchema.optional().describe("The metadata of the consumer. This is used to display the consumer in the sidebar. This is optional, but recommended."),
    custom_consumer_settings: z.record(z.string(), z.any()).optional().describe("Custom consumer settings that are passed as part of the session."),
    redirect_uri: z.string().optional().describe("The URL to redirect the user to after the session has been configured."),
    settings: z.lazy(() => Settings$zodSchema).optional().describe("Settings to change the way the Vault is displayed."),
    theme: z.lazy(() => Theme$zodSchema).optional().describe("Theming options to change the look and feel of Vault."),
});
//# sourceMappingURL=session.js.map