/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const SubsidiaryReference$zodSchema = z
    .object({
    id: z.string().optional().describe("A unique identifier for an object."),
    name: z.string().nullable().optional().describe("The name of the company."),
});
//# sourceMappingURL=subsidiaryreference.js.map