/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const RequestResponse$zodSchema = z.object({}).describe("HTTP request details");
export const UnauthorizedDetailResponse$zodSchema = z.object({}).describe("HTTP response details");
export const DebugResponse$zodSchema = z.object({
    code: z.string().optional().describe("Error code (e.g., ETIMEDOUT, ECONNREFUSED)"),
    cooldown_remaining_ms: z.number().optional().describe("Milliseconds remaining in cooldown period before retry is allowed."),
    credentials_expire_at_ms: z.number().optional().describe("Unix timestamp (milliseconds) when credentials will be deleted if not refreshed. Only present for non-recoverable errors (401, 400). Credentials are preserved indefinitely for recoverable/network errors."),
    message: z.string().optional().describe("Error message from downstream provider or network layer"),
    request: z.lazy(() => RequestResponse$zodSchema).optional().describe("HTTP request details"),
    response: z.lazy(() => UnauthorizedDetailResponse$zodSchema).optional()
        .describe("HTTP response details"),
    retry_after_ms: z.number().optional().describe("Unix timestamp (milliseconds) when token refresh retry is allowed after cooldown period expires."),
}).describe("Debug information including request/response details and OAuth timing metadata");
export const DetailResponse$zodSchema = z.object({
    debug: z.lazy(() => DebugResponse$zodSchema).optional().describe("Debug information including request/response details and OAuth timing metadata"),
    message: z.string().optional().describe("Detailed error message"),
    type: z.string().optional().describe("Error type identifier"),
});
export const DetailResponseUnion$zodSchema = z
    .union([
    z.string(),
    z.lazy(() => DetailResponse$zodSchema),
]).describe("Contains parameter or domain specific information related to the error and why it occurred.");
export const Unauthorized$zodSchema = z.object({
    detail: z.union([
        z.string(),
        z.lazy(() => DetailResponse$zodSchema),
    ]).optional().describe("Contains parameter or domain specific information related to the error and why it occurred."),
    error: z.string().optional().describe("Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)"),
    message: z.string().optional().describe("A human-readable message providing more details about the error."),
    ref: z.string().optional().describe("Link to documentation of error type"),
    status_code: z.number().optional().describe("HTTP status code"),
    type_name: z.string().optional().describe("The type of error returned"),
}).describe("Unauthorized");
//# sourceMappingURL=unauthorized.js.map