/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { Address$zodSchema } from "./address.js";
import { Email$zodSchema } from "./email.js";
import { PassThroughBody$zodSchema, } from "./passthroughbody.js";
import { PhoneNumber$zodSchema } from "./phonenumber.js";
export const UserOutput$zodSchema = z.object({
    addresses: z.array(Address$zodSchema).optional(),
    company_name: z.string().nullable().optional().describe("The name of the company."),
    created_at: z.string().nullable().optional().describe("The date and time when the user was created."),
    custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe("When custom mappings are configured on the resource, the result is included here."),
    department: z.string().nullable().optional().describe("The department the person is currently in. [Deprecated](https://developers.apideck.com/changelog) in favor of the dedicated department_id and department_name field."),
    description: z.string().nullable().optional().describe("A description of the object."),
    division: z.string().nullable().optional().describe("The division the person is currently in. Usually a collection of departments or teams or regions."),
    emails: z.array(Email$zodSchema),
    employee_number: z.string().nullable().optional().describe("An Employee Number, Employee ID or Employee Code, is a unique number that has been assigned to each individual staff member within a company."),
    first_name: z.string().nullable().optional().describe("The first name of the person."),
    id: z.string().optional().describe("The unique identifier for the user"),
    image: z.string().nullable().optional().describe("The URL of the user's avatar"),
    language: z.string().nullable().optional().describe("language code according to ISO 639-1. For the United States - EN"),
    last_name: z.string().nullable().optional().describe("The last name of the person."),
    parent_id: z.string().nullable().optional().describe("The parent user id"),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe("The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources."),
    phone_numbers: z.array(PhoneNumber$zodSchema).optional(),
    status: z.string().nullable().optional().describe("The status of the user"),
    title: z.string().nullable().optional().describe("The job title of the person."),
    updated_at: z.string().nullable().optional().describe("The date and time when the user was last updated."),
    username: z.string().nullable().optional().describe("The username of the user"),
});
//# sourceMappingURL=useroutput.js.map