/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { BadRequestResponse$zodSchema, } from "./badrequestresponse.js";
import { CreateCallbackState$zodSchema, } from "./createcallbackstate.js";
import { CreateCallbackStateResponse$zodSchema, } from "./createcallbackstateresponse.js";
import { NotFoundResponse$zodSchema, } from "./notfoundresponse.js";
import { PaymentRequiredResponse$zodSchema, } from "./paymentrequiredresponse.js";
import { UnauthorizedResponse$zodSchema, } from "./unauthorizedresponse.js";
import { UnexpectedErrorResponse$zodSchema, } from "./unexpectederrorresponse.js";
import { UnprocessableResponse$zodSchema, } from "./unprocessableresponse.js";
export const VaultCreateCallbackStateGlobals$zodSchema = z.object({
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
});
export const VaultCreateCallbackStateRequest$zodSchema = z.object({
    body: CreateCallbackState$zodSchema.describe("Callback state data"),
    service_id: z.string().describe("Service ID of the resource to return"),
    unified_api: z.string().describe("Unified API"),
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
});
export const VaultCreateCallbackStateResponse$zodSchema = z.union([
    CreateCallbackStateResponse$zodSchema,
    BadRequestResponse$zodSchema,
    UnauthorizedResponse$zodSchema,
    PaymentRequiredResponse$zodSchema,
    NotFoundResponse$zodSchema,
    UnprocessableResponse$zodSchema,
    UnexpectedErrorResponse$zodSchema,
]);
//# sourceMappingURL=vaultcreatecallbackstateop.js.map