/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { BadRequestResponse$zodSchema, } from "./badrequestresponse.js";
import { GetCustomFieldsResponse$zodSchema, } from "./getcustomfieldsresponse.js";
import { NotFoundResponse$zodSchema, } from "./notfoundresponse.js";
import { PaymentRequiredResponse$zodSchema, } from "./paymentrequiredresponse.js";
import { UnauthorizedResponse$zodSchema, } from "./unauthorizedresponse.js";
import { UnexpectedErrorResponse$zodSchema, } from "./unexpectederrorresponse.js";
import { UnprocessableResponse$zodSchema, } from "./unprocessableresponse.js";
export const VaultCustomFieldsAllGlobals$zodSchema = z.object({
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
});
export const VaultCustomFieldsAllRequest$zodSchema = z.object({
    resource: z.string().describe("Name of the resource (plural)"),
    resource_id: z.string().describe("This is the id of the resource you want to fetch when listing custom fields. For example, if you want to fetch custom fields for a specific contact, you would use the contact id.").optional(),
    service_id: z.string().describe("Service ID of the resource to return"),
    unified_api: z.string().describe("Unified API"),
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
    xApideckConsumerId: z.string().describe("ID of the consumer which you want to get or push data from").optional(),
});
export const VaultCustomFieldsAllResponse$zodSchema = z.union([
    GetCustomFieldsResponse$zodSchema,
    BadRequestResponse$zodSchema,
    UnauthorizedResponse$zodSchema,
    PaymentRequiredResponse$zodSchema,
    NotFoundResponse$zodSchema,
    UnprocessableResponse$zodSchema,
    UnexpectedErrorResponse$zodSchema,
]);
//# sourceMappingURL=vaultcustomfieldsallop.js.map