import * as z from "zod";
import { OpenEnum } from "../types/enums.js";
export declare const WebhookEventType: {
    readonly Wildcard: "*";
    readonly CrmActivityCreated: "crm.activity.created";
    readonly CrmActivityUpdated: "crm.activity.updated";
    readonly CrmActivityDeleted: "crm.activity.deleted";
    readonly CrmCompanyCreated: "crm.company.created";
    readonly CrmCompanyUpdated: "crm.company.updated";
    readonly CrmCompanyDeleted: "crm.company.deleted";
    readonly CrmContactCreated: "crm.contact.created";
    readonly CrmContactUpdated: "crm.contact.updated";
    readonly CrmContactDeleted: "crm.contact.deleted";
    readonly CrmLeadCreated: "crm.lead.created";
    readonly CrmLeadUpdated: "crm.lead.updated";
    readonly CrmLeadDeleted: "crm.lead.deleted";
    readonly CrmNoteCreated: "crm.note.created";
    readonly CrmNoteUpdated: "crm.note.updated";
    readonly CrmNoteDeleted: "crm.note.deleted";
    readonly CrmOpportunityCreated: "crm.opportunity.created";
    readonly CrmOpportunityUpdated: "crm.opportunity.updated";
    readonly CrmOpportunityDeleted: "crm.opportunity.deleted";
    readonly LeadLeadCreated: "lead.lead.created";
    readonly LeadLeadUpdated: "lead.lead.updated";
    readonly LeadLeadDeleted: "lead.lead.deleted";
    readonly VaultConnectionCreated: "vault.connection.created";
    readonly VaultConnectionUpdated: "vault.connection.updated";
    readonly VaultConnectionDisabled: "vault.connection.disabled";
    readonly VaultConnectionDeleted: "vault.connection.deleted";
    readonly VaultConnectionCallable: "vault.connection.callable";
    readonly VaultConnectionRevoked: "vault.connection.revoked";
    readonly VaultConnectionTokenRefreshFailed: "vault.connection.token_refresh.failed";
    readonly VaultConnectionTokenRefreshPending: "vault.connection.token_refresh.pending";
    readonly VaultConnectionTokenRefreshRecovered: "vault.connection.token_refresh.recovered";
    readonly AtsJobCreated: "ats.job.created";
    readonly AtsJobUpdated: "ats.job.updated";
    readonly AtsJobDeleted: "ats.job.deleted";
    readonly AtsApplicantCreated: "ats.applicant.created";
    readonly AtsApplicantUpdated: "ats.applicant.updated";
    readonly AtsApplicantDeleted: "ats.applicant.deleted";
    readonly AccountingCustomerCreated: "accounting.customer.created";
    readonly AccountingCustomerUpdated: "accounting.customer.updated";
    readonly AccountingCustomerDeleted: "accounting.customer.deleted";
    readonly AccountingInvoiceCreated: "accounting.invoice.created";
    readonly AccountingInvoiceUpdated: "accounting.invoice.updated";
    readonly AccountingInvoiceDeleted: "accounting.invoice.deleted";
    readonly AccountingInvoiceItemCreated: "accounting.invoice_item.created";
    readonly AccountingInvoiceItemUpdated: "accounting.invoice_item.updated";
    readonly AccountingInvoiceItemDeleted: "accounting.invoice_item.deleted";
    readonly AccountingLedgerAccountCreated: "accounting.ledger_account.created";
    readonly AccountingLedgerAccountUpdated: "accounting.ledger_account.updated";
    readonly AccountingLedgerAccountDeleted: "accounting.ledger_account.deleted";
    readonly AccountingTaxRateCreated: "accounting.tax_rate.created";
    readonly AccountingTaxRateUpdated: "accounting.tax_rate.updated";
    readonly AccountingTaxRateDeleted: "accounting.tax_rate.deleted";
    readonly AccountingBillCreated: "accounting.bill.created";
    readonly AccountingBillUpdated: "accounting.bill.updated";
    readonly AccountingBillDeleted: "accounting.bill.deleted";
    readonly AccountingBillPaymentCreated: "accounting.bill_payment.created";
    readonly AccountingBillPaymentUpdated: "accounting.bill_payment.updated";
    readonly AccountingBillPaymentDeleted: "accounting.bill_payment.deleted";
    readonly AccountingPaymentCreated: "accounting.payment.created";
    readonly AccountingPaymentUpdated: "accounting.payment.updated";
    readonly AccountingPaymentDeleted: "accounting.payment.deleted";
    readonly AccountingSupplierCreated: "accounting.supplier.created";
    readonly AccountingSupplierUpdated: "accounting.supplier.updated";
    readonly AccountingSupplierDeleted: "accounting.supplier.deleted";
    readonly AccountingPurchaseOrderCreated: "accounting.purchase_order.created";
    readonly AccountingPurchaseOrderUpdated: "accounting.purchase_order.updated";
    readonly AccountingPurchaseOrderDeleted: "accounting.purchase_order.deleted";
    readonly AccountingCreditNoteCreated: "accounting.credit_note.created";
    readonly AccountingCreditNoteUpdated: "accounting.credit_note.updated";
    readonly AccountingCreditNoteDeleted: "accounting.credit_note.deleted";
    readonly PosOrderCreated: "pos.order.created";
    readonly PosOrderUpdated: "pos.order.updated";
    readonly PosOrderDeleted: "pos.order.deleted";
    readonly PosProductCreated: "pos.product.created";
    readonly PosProductUpdated: "pos.product.updated";
    readonly PosProductDeleted: "pos.product.deleted";
    readonly PosPaymentCreated: "pos.payment.created";
    readonly PosPaymentUpdated: "pos.payment.updated";
    readonly PosPaymentDeleted: "pos.payment.deleted";
    readonly PosMerchantCreated: "pos.merchant.created";
    readonly PosMerchantUpdated: "pos.merchant.updated";
    readonly PosMerchantDeleted: "pos.merchant.deleted";
    readonly PosLocationCreated: "pos.location.created";
    readonly PosLocationUpdated: "pos.location.updated";
    readonly PosLocationDeleted: "pos.location.deleted";
    readonly PosItemCreated: "pos.item.created";
    readonly PosItemUpdated: "pos.item.updated";
    readonly PosItemDeleted: "pos.item.deleted";
    readonly PosModifierCreated: "pos.modifier.created";
    readonly PosModifierUpdated: "pos.modifier.updated";
    readonly PosModifierDeleted: "pos.modifier.deleted";
    readonly PosModifierGroupCreated: "pos.modifier-group.created";
    readonly PosModifierGroupUpdated: "pos.modifier-group.updated";
    readonly PosModifierGroupDeleted: "pos.modifier-group.deleted";
    readonly HrisEmployeeCreated: "hris.employee.created";
    readonly HrisEmployeeUpdated: "hris.employee.updated";
    readonly HrisEmployeeDeleted: "hris.employee.deleted";
    readonly HrisEmployeeTerminated: "hris.employee.terminated";
    readonly HrisCompanyCreated: "hris.company.created";
    readonly HrisCompanyUpdated: "hris.company.updated";
    readonly HrisCompanyDeleted: "hris.company.deleted";
    readonly FileStorageFileCreated: "file-storage.file.created";
    readonly FileStorageFileUpdated: "file-storage.file.updated";
    readonly FileStorageFileDeleted: "file-storage.file.deleted";
    readonly FileStorageDriveUpdated: "file-storage.drive.updated";
    readonly IssueTrackingTicketCreated: "issue-tracking.ticket.created";
    readonly IssueTrackingTicketUpdated: "issue-tracking.ticket.updated";
    readonly IssueTrackingTicketDeleted: "issue-tracking.ticket.deleted";
    readonly AtsApplicationCreated: "ats.application.created";
    readonly AtsApplicationUpdated: "ats.application.updated";
    readonly AtsApplicationDeleted: "ats.application.deleted";
    readonly AccountingExpenseCreated: "accounting.expense.created";
    readonly AccountingExpenseUpdated: "accounting.expense.updated";
    readonly AccountingExpenseDeleted: "accounting.expense.deleted";
    readonly EcommerceOrderCreated: "ecommerce.order.created";
    readonly EcommerceOrderUpdated: "ecommerce.order.updated";
    readonly EcommerceOrderDeleted: "ecommerce.order.deleted";
    readonly EcommerceProductCreated: "ecommerce.product.created";
    readonly EcommerceProductUpdated: "ecommerce.product.updated";
    readonly EcommerceProductDeleted: "ecommerce.product.deleted";
    readonly EcommerceCustomerCreated: "ecommerce.customer.created";
    readonly EcommerceCustomerUpdated: "ecommerce.customer.updated";
    readonly EcommerceCustomerDeleted: "ecommerce.customer.deleted";
    readonly AccountingQuoteCreated: "accounting.quote.created";
    readonly AccountingQuoteUpdated: "accounting.quote.updated";
    readonly AccountingQuoteDeleted: "accounting.quote.deleted";
    readonly AccountingProjectCreated: "accounting.project.created";
    readonly AccountingProjectUpdated: "accounting.project.updated";
    readonly AccountingProjectDeleted: "accounting.project.deleted";
};
export type WebhookEventType = OpenEnum<typeof WebhookEventType>;
export declare const WebhookEventType$zodSchema: z.ZodUnion<readonly [z.ZodEnum<{
    "*": "*";
    "crm.activity.created": "crm.activity.created";
    "crm.activity.updated": "crm.activity.updated";
    "crm.activity.deleted": "crm.activity.deleted";
    "crm.company.created": "crm.company.created";
    "crm.company.updated": "crm.company.updated";
    "crm.company.deleted": "crm.company.deleted";
    "crm.contact.created": "crm.contact.created";
    "crm.contact.updated": "crm.contact.updated";
    "crm.contact.deleted": "crm.contact.deleted";
    "crm.lead.created": "crm.lead.created";
    "crm.lead.updated": "crm.lead.updated";
    "crm.lead.deleted": "crm.lead.deleted";
    "crm.note.created": "crm.note.created";
    "crm.note.updated": "crm.note.updated";
    "crm.note.deleted": "crm.note.deleted";
    "crm.opportunity.created": "crm.opportunity.created";
    "crm.opportunity.updated": "crm.opportunity.updated";
    "crm.opportunity.deleted": "crm.opportunity.deleted";
    "lead.lead.created": "lead.lead.created";
    "lead.lead.updated": "lead.lead.updated";
    "lead.lead.deleted": "lead.lead.deleted";
    "vault.connection.created": "vault.connection.created";
    "vault.connection.updated": "vault.connection.updated";
    "vault.connection.disabled": "vault.connection.disabled";
    "vault.connection.deleted": "vault.connection.deleted";
    "vault.connection.callable": "vault.connection.callable";
    "vault.connection.revoked": "vault.connection.revoked";
    "vault.connection.token_refresh.failed": "vault.connection.token_refresh.failed";
    "vault.connection.token_refresh.pending": "vault.connection.token_refresh.pending";
    "vault.connection.token_refresh.recovered": "vault.connection.token_refresh.recovered";
    "ats.job.created": "ats.job.created";
    "ats.job.updated": "ats.job.updated";
    "ats.job.deleted": "ats.job.deleted";
    "ats.applicant.created": "ats.applicant.created";
    "ats.applicant.updated": "ats.applicant.updated";
    "ats.applicant.deleted": "ats.applicant.deleted";
    "accounting.customer.created": "accounting.customer.created";
    "accounting.customer.updated": "accounting.customer.updated";
    "accounting.customer.deleted": "accounting.customer.deleted";
    "accounting.invoice.created": "accounting.invoice.created";
    "accounting.invoice.updated": "accounting.invoice.updated";
    "accounting.invoice.deleted": "accounting.invoice.deleted";
    "accounting.invoice_item.created": "accounting.invoice_item.created";
    "accounting.invoice_item.updated": "accounting.invoice_item.updated";
    "accounting.invoice_item.deleted": "accounting.invoice_item.deleted";
    "accounting.ledger_account.created": "accounting.ledger_account.created";
    "accounting.ledger_account.updated": "accounting.ledger_account.updated";
    "accounting.ledger_account.deleted": "accounting.ledger_account.deleted";
    "accounting.tax_rate.created": "accounting.tax_rate.created";
    "accounting.tax_rate.updated": "accounting.tax_rate.updated";
    "accounting.tax_rate.deleted": "accounting.tax_rate.deleted";
    "accounting.bill.created": "accounting.bill.created";
    "accounting.bill.updated": "accounting.bill.updated";
    "accounting.bill.deleted": "accounting.bill.deleted";
    "accounting.bill_payment.created": "accounting.bill_payment.created";
    "accounting.bill_payment.updated": "accounting.bill_payment.updated";
    "accounting.bill_payment.deleted": "accounting.bill_payment.deleted";
    "accounting.payment.created": "accounting.payment.created";
    "accounting.payment.updated": "accounting.payment.updated";
    "accounting.payment.deleted": "accounting.payment.deleted";
    "accounting.supplier.created": "accounting.supplier.created";
    "accounting.supplier.updated": "accounting.supplier.updated";
    "accounting.supplier.deleted": "accounting.supplier.deleted";
    "accounting.purchase_order.created": "accounting.purchase_order.created";
    "accounting.purchase_order.updated": "accounting.purchase_order.updated";
    "accounting.purchase_order.deleted": "accounting.purchase_order.deleted";
    "accounting.credit_note.created": "accounting.credit_note.created";
    "accounting.credit_note.updated": "accounting.credit_note.updated";
    "accounting.credit_note.deleted": "accounting.credit_note.deleted";
    "pos.order.created": "pos.order.created";
    "pos.order.updated": "pos.order.updated";
    "pos.order.deleted": "pos.order.deleted";
    "pos.product.created": "pos.product.created";
    "pos.product.updated": "pos.product.updated";
    "pos.product.deleted": "pos.product.deleted";
    "pos.payment.created": "pos.payment.created";
    "pos.payment.updated": "pos.payment.updated";
    "pos.payment.deleted": "pos.payment.deleted";
    "pos.merchant.created": "pos.merchant.created";
    "pos.merchant.updated": "pos.merchant.updated";
    "pos.merchant.deleted": "pos.merchant.deleted";
    "pos.location.created": "pos.location.created";
    "pos.location.updated": "pos.location.updated";
    "pos.location.deleted": "pos.location.deleted";
    "pos.item.created": "pos.item.created";
    "pos.item.updated": "pos.item.updated";
    "pos.item.deleted": "pos.item.deleted";
    "pos.modifier.created": "pos.modifier.created";
    "pos.modifier.updated": "pos.modifier.updated";
    "pos.modifier.deleted": "pos.modifier.deleted";
    "pos.modifier-group.created": "pos.modifier-group.created";
    "pos.modifier-group.updated": "pos.modifier-group.updated";
    "pos.modifier-group.deleted": "pos.modifier-group.deleted";
    "hris.employee.created": "hris.employee.created";
    "hris.employee.updated": "hris.employee.updated";
    "hris.employee.deleted": "hris.employee.deleted";
    "hris.employee.terminated": "hris.employee.terminated";
    "hris.company.created": "hris.company.created";
    "hris.company.updated": "hris.company.updated";
    "hris.company.deleted": "hris.company.deleted";
    "file-storage.file.created": "file-storage.file.created";
    "file-storage.file.updated": "file-storage.file.updated";
    "file-storage.file.deleted": "file-storage.file.deleted";
    "file-storage.drive.updated": "file-storage.drive.updated";
    "issue-tracking.ticket.created": "issue-tracking.ticket.created";
    "issue-tracking.ticket.updated": "issue-tracking.ticket.updated";
    "issue-tracking.ticket.deleted": "issue-tracking.ticket.deleted";
    "ats.application.created": "ats.application.created";
    "ats.application.updated": "ats.application.updated";
    "ats.application.deleted": "ats.application.deleted";
    "accounting.expense.created": "accounting.expense.created";
    "accounting.expense.updated": "accounting.expense.updated";
    "accounting.expense.deleted": "accounting.expense.deleted";
    "ecommerce.order.created": "ecommerce.order.created";
    "ecommerce.order.updated": "ecommerce.order.updated";
    "ecommerce.order.deleted": "ecommerce.order.deleted";
    "ecommerce.product.created": "ecommerce.product.created";
    "ecommerce.product.updated": "ecommerce.product.updated";
    "ecommerce.product.deleted": "ecommerce.product.deleted";
    "ecommerce.customer.created": "ecommerce.customer.created";
    "ecommerce.customer.updated": "ecommerce.customer.updated";
    "ecommerce.customer.deleted": "ecommerce.customer.deleted";
    "accounting.quote.created": "accounting.quote.created";
    "accounting.quote.updated": "accounting.quote.updated";
    "accounting.quote.deleted": "accounting.quote.deleted";
    "accounting.project.created": "accounting.project.created";
    "accounting.project.updated": "accounting.project.updated";
    "accounting.project.deleted": "accounting.project.deleted";
}>, z.ZodPipe<z.ZodString, z.ZodTransform<import("../types/enums.js").Unrecognized<string>, string>>]>;
//# sourceMappingURL=webhookeventtype.d.ts.map