/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { BadRequestResponse$zodSchema, } from "./badrequestresponse.js";
import { GetWebhookResponse$zodSchema, } from "./getwebhookresponse.js";
import { NotFoundResponse$zodSchema, } from "./notfoundresponse.js";
import { PaymentRequiredResponse$zodSchema, } from "./paymentrequiredresponse.js";
import { UnauthorizedResponse$zodSchema, } from "./unauthorizedresponse.js";
import { UnexpectedErrorResponse$zodSchema, } from "./unexpectederrorresponse.js";
import { UnprocessableResponse$zodSchema, } from "./unprocessableresponse.js";
export const WebhookWebhooksOneGlobals$zodSchema = z.object({
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
});
export const WebhookWebhooksOneRequest$zodSchema = z.object({
    id: z.string().describe("JWT Webhook token that represents the unifiedApi and applicationId associated to the event source."),
    xApideckAppId: z.string().describe("The ID of your Unify application")
        .optional(),
});
export const WebhookWebhooksOneResponse$zodSchema = z.union([
    GetWebhookResponse$zodSchema,
    BadRequestResponse$zodSchema,
    UnauthorizedResponse$zodSchema,
    PaymentRequiredResponse$zodSchema,
    NotFoundResponse$zodSchema,
    UnprocessableResponse$zodSchema,
    UnexpectedErrorResponse$zodSchema,
]);
//# sourceMappingURL=webhookwebhooksoneop.js.map