/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
export const WebhookSubscription$zodSchema = z
    .object({
    created_at: z.string().optional().describe("The date and time the webhook subscription was created downstream"),
    downstream_event_types: z.array(z.string()).optional().describe("The list of downstream Events this connection is subscribed to"),
    downstream_id: z.string().optional().describe("The ID of the downstream service"),
    execute_url: z.string().optional().describe("The URL the downstream is sending to when the event is triggered"),
    unify_event_types: z.array(z.string()).optional().describe("The list of Unify Events this connection is subscribed to"),
});
//# sourceMappingURL=webhooksubscription.js.map