/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { catchUnrecognizedEnum } from "../types/enums.js";
/**
 * The type of website
 */
export const WebsiteType = {
    Primary: "primary",
    Secondary: "secondary",
    Work: "work",
    Personal: "personal",
    Other: "other",
};
export const WebsiteType$zodSchema = z.union([
    z.enum([
        "primary",
        "secondary",
        "work",
        "personal",
        "other",
    ]),
    z.string().transform(catchUnrecognizedEnum),
]).describe("The type of website");
export const Website$zodSchema = z.object({
    id: z.string().nullable().optional().describe("Unique identifier for the website"),
    type: WebsiteType$zodSchema.nullable().optional().describe("The type of website"),
    url: z.string().describe("The website URL"),
});
//# sourceMappingURL=website.js.map