/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountingExpensesList } from "../../funcs/accountingExpensesList.js";
import { AccountingExpensesAllRequest$zodSchema } from "../../models/accountingexpensesallop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AccountingExpensesAllRequest$zodSchema.optional(),
};
export const tool$accountingExpensesList = {
    name: "accounting-expenses-list",
    description: `List Expenses

List Expenses`,
    scopes: ["read"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await accountingExpensesList(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=accountingExpensesList.js.map