/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountingTaxRatesUpdate } from "../../funcs/accountingTaxRatesUpdate.js";
import { AccountingTaxRatesUpdateRequest$zodSchema } from "../../models/accountingtaxratesupdateop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AccountingTaxRatesUpdateRequest$zodSchema,
};
export const tool$accountingTaxRatesUpdate = {
    name: "accounting-tax-rates-update",
    description: `Update Tax Rate

Update Tax Rate`,
    scopes: ["write"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await accountingTaxRatesUpdate(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=accountingTaxRatesUpdate.js.map