/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountingCreditNotesGet } from "../../funcs/accountingCreditNotesGet.js";
import { AccountingCreditNotesOneRequest$zodSchema } from "../../models/accountingcreditnotesoneop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AccountingCreditNotesOneRequest$zodSchema,
};
export const tool$accountingCreditNotesGet = {
    name: "accounting-credit-notes-get",
    description: `Get Credit Note

Get Credit Note`,
    scopes: ["read"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await accountingCreditNotesGet(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=accountingCreditNotesGet.js.map