/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountingJournalEntriesCreate } from "../../funcs/accountingJournalEntriesCreate.js";
import { AccountingJournalEntriesAddRequest$zodSchema } from "../../models/accountingjournalentriesaddop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AccountingJournalEntriesAddRequest$zodSchema,
};
export const tool$accountingJournalEntriesCreate = {
    name: "accounting-journal-entries-create",
    description: `Create Journal Entry

Create Journal Entry`,
    scopes: ["write"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await accountingJournalEntriesCreate(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=accountingJournalEntriesCreate.js.map