/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountingInvoiceItemsList } from "../../funcs/accountingInvoiceItemsList.js";
import { AccountingInvoiceItemsAllRequest$zodSchema } from "../../models/accountinginvoiceitemsallop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AccountingInvoiceItemsAllRequest$zodSchema.optional(),
};
export const tool$accountingInvoiceItemsList = {
    name: "accounting-invoice-items-list",
    description: `List Invoice Items

List Invoice Items`,
    scopes: ["read"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await accountingInvoiceItemsList(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=accountingInvoiceItemsList.js.map