/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountingCategoriesList } from "../../funcs/accountingCategoriesList.js";
import { AccountingCategoriesAllRequest$zodSchema } from "../../models/accountingcategoriesallop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AccountingCategoriesAllRequest$zodSchema.optional(),
};
export const tool$accountingCategoriesList = {
    name: "accounting-categories-list",
    description: `List Categories

List Categories`,
    scopes: ["read"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await accountingCategoriesList(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=accountingCategoriesList.js.map