/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountingBillsList } from "../../funcs/accountingBillsList.js";
import { AccountingBillsAllRequest$zodSchema } from "../../models/accountingbillsallop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AccountingBillsAllRequest$zodSchema.optional(),
};
export const tool$accountingBillsList = {
    name: "accounting-bills-list",
    description: `List Bills

List Bills`,
    scopes: ["read"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await accountingBillsList(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=accountingBillsList.js.map