/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountingBankFeedStatementsList } from "../../funcs/accountingBankFeedStatementsList.js";
import { AccountingBankFeedStatementsAllRequest$zodSchema } from "../../models/accountingbankfeedstatementsallop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AccountingBankFeedStatementsAllRequest$zodSchema.optional(),
};
export const tool$accountingBankFeedStatementsList = {
    name: "accounting-bank-feed-statements-list",
    description: `List Bank Feed Statements

List Bank Feed Statements`,
    scopes: ["read"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await accountingBankFeedStatementsList(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=accountingBankFeedStatementsList.js.map