/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountingExpenseReportsGet } from "../../funcs/accountingExpenseReportsGet.js";
import { AccountingExpenseReportsOneRequest$zodSchema } from "../../models/accountingexpensereportsoneop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AccountingExpenseReportsOneRequest$zodSchema,
};
export const tool$accountingExpenseReportsGet = {
    name: "accounting-expense-reports-get",
    description: `Get Expense Report

Get Expense Report`,
    scopes: ["read"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await accountingExpenseReportsGet(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=accountingExpenseReportsGet.js.map