/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountingCustomersGet } from "../../funcs/accountingCustomersGet.js";
import { AccountingCustomersOneRequest$zodSchema } from "../../models/accountingcustomersoneop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AccountingCustomersOneRequest$zodSchema,
};
export const tool$accountingCustomersGet = {
    name: "accounting-customers-get",
    description: `Get Customer

Get Customer`,
    scopes: ["read"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await accountingCustomersGet(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=accountingCustomersGet.js.map