/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountingBankFeedStatementsDelete } from "../../funcs/accountingBankFeedStatementsDelete.js";
import { AccountingBankFeedStatementsDeleteRequest$zodSchema } from "../../models/accountingbankfeedstatementsdeleteop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AccountingBankFeedStatementsDeleteRequest$zodSchema,
};
export const tool$accountingBankFeedStatementsDelete = {
    name: "accounting-bank-feed-statements-delete",
    description: `Delete Bank Feed Statement

Delete Bank Feed Statement`,
    scopes: ["destructive"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await accountingBankFeedStatementsDelete(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=accountingBankFeedStatementsDelete.js.map