/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountingTaxRatesGet } from "../../funcs/accountingTaxRatesGet.js";
import { AccountingTaxRatesOneRequest$zodSchema } from "../../models/accountingtaxratesoneop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AccountingTaxRatesOneRequest$zodSchema,
};
export const tool$accountingTaxRatesGet = {
    name: "accounting-tax-rates-get",
    description: `Get Tax Rate

Get Tax Rate. Note: Not all connectors return the actual rate/percentage value. In this case, only the tax code or reference is returned. Support will soon be added to return the actual rate/percentage by doing additional calls in the background to provide the full view of a given tax rate. Connectors Affected: Quickbooks
`,
    scopes: ["read"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await accountingTaxRatesGet(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=accountingTaxRatesGet.js.map