/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountingProjectsUpdate } from "../../funcs/accountingProjectsUpdate.js";
import { AccountingProjectsUpdateRequest$zodSchema } from "../../models/accountingprojectsupdateop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AccountingProjectsUpdateRequest$zodSchema,
};
export const tool$accountingProjectsUpdate = {
    name: "accounting-projects-update",
    description: `Update project

Update project`,
    scopes: ["write"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await accountingProjectsUpdate(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=accountingProjectsUpdate.js.map