/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { accountingCreditNotesUpdate } from "../../funcs/accountingCreditNotesUpdate.js";
import { AccountingCreditNotesUpdateRequest$zodSchema } from "../../models/accountingcreditnotesupdateop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AccountingCreditNotesUpdateRequest$zodSchema,
};
export const tool$accountingCreditNotesUpdate = {
    name: "accounting-credit-notes-update",
    description: `Update Credit Note

Update Credit Note`,
    scopes: ["write"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await accountingCreditNotesUpdate(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=accountingCreditNotesUpdate.js.map