/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { atsApplicantsGet } from "../../funcs/atsApplicantsGet.js";
import { AtsApplicantsOneRequest$zodSchema } from "../../models/atsapplicantsoneop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AtsApplicantsOneRequest$zodSchema,
};
export const tool$atsApplicantsGet = {
    name: "ats-applicants-get",
    description: `Get Applicant

Get Applicant`,
    scopes: ["read"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await atsApplicantsGet(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=atsApplicantsGet.js.map