/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { atsJobsDelete } from "../../funcs/atsJobsDelete.js";
import { AtsJobsDeleteRequest$zodSchema } from "../../models/atsjobsdeleteop.js";
import { formatResult } from "../tools.js";
const args = {
    request: AtsJobsDeleteRequest$zodSchema,
};
export const tool$atsJobsDelete = {
    name: "ats-jobs-delete",
    description: `Delete Job

Delete Job`,
    scopes: ["destructive"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await atsJobsDelete(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=atsJobsDelete.js.map