/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { crmCompaniesDelete } from "../../funcs/crmCompaniesDelete.js";
import { CrmCompaniesDeleteRequest$zodSchema } from "../../models/crmcompaniesdeleteop.js";
import { formatResult } from "../tools.js";
const args = {
    request: CrmCompaniesDeleteRequest$zodSchema,
};
export const tool$crmCompaniesDelete = {
    name: "crm-companies-delete",
    description: `Delete company

Delete company`,
    scopes: ["destructive"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await crmCompaniesDelete(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=crmCompaniesDelete.js.map