/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { crmLeadsUpdate } from "../../funcs/crmLeadsUpdate.js";
import { CrmLeadsUpdateRequest$zodSchema } from "../../models/crmleadsupdateop.js";
import { formatResult } from "../tools.js";
const args = {
    request: CrmLeadsUpdateRequest$zodSchema,
};
export const tool$crmLeadsUpdate = {
    name: "crm-leads-update",
    description: `Update lead

Update lead`,
    scopes: ["write"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await crmLeadsUpdate(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=crmLeadsUpdate.js.map