/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { crmNotesUpdate } from "../../funcs/crmNotesUpdate.js";
import { CrmNotesUpdateRequest$zodSchema } from "../../models/crmnotesupdateop.js";
import { formatResult } from "../tools.js";
const args = {
    request: CrmNotesUpdateRequest$zodSchema,
};
export const tool$crmNotesUpdate = {
    name: "crm-notes-update",
    description: `Update note

Update note`,
    scopes: ["write"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await crmNotesUpdate(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=crmNotesUpdate.js.map