/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { issueTrackingCollectionTicketCommentsDelete } from "../../funcs/issueTrackingCollectionTicketCommentsDelete.js";
import { IssueTrackingCollectionTicketCommentsDeleteRequest$zodSchema } from "../../models/issuetrackingcollectionticketcommentsdeleteop.js";
import { formatResult } from "../tools.js";
const args = {
    request: IssueTrackingCollectionTicketCommentsDeleteRequest$zodSchema,
};
export const tool$issueTrackingCollectionTicketCommentsDelete = {
    name: "issue-tracking-collection-ticket-comments-delete",
    description: `Delete Comment

Delete Comment`,
    scopes: ["destructive"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await issueTrackingCollectionTicketCommentsDelete(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=issueTrackingCollectionTicketCommentsDelete.js.map