/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { issueTrackingCollectionTicketsList } from "../../funcs/issueTrackingCollectionTicketsList.js";
import { IssueTrackingCollectionTicketsAllRequest$zodSchema } from "../../models/issuetrackingcollectionticketsallop.js";
import { formatResult } from "../tools.js";
const args = {
    request: IssueTrackingCollectionTicketsAllRequest$zodSchema,
};
export const tool$issueTrackingCollectionTicketsList = {
    name: "issue-tracking-collection-tickets-list",
    description: `List Tickets

List Tickets`,
    scopes: ["read"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await issueTrackingCollectionTicketsList(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=issueTrackingCollectionTicketsList.js.map