/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { proxyPatch } from "../../funcs/proxyPatch.js";
import { ProxyPatchProxyRequest$zodSchema } from "../../models/proxypatchproxyop.js";
import { formatResult } from "../tools.js";
const args = {
    request: ProxyPatchProxyRequest$zodSchema,
};
export const tool$proxyPatch = {
    name: "proxy-patch",
    description: `PATCH

Proxies a downstream PATCH request to a service and injects the necessary credentials into a request stored in Vault. This allows you to have an additional security layer and logging without needing to rely on Unify for normalization.
**Note**: Vault will proxy all data to the downstream URL and method/verb in the headers.
`,
    scopes: ["write"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await proxyPatch(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=proxyPatch.js.map