/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { proxyGet } from "../../funcs/proxyGet.js";
import { ProxyGetProxyRequest$zodSchema } from "../../models/proxygetproxyop.js";
import { formatResult } from "../tools.js";
const args = {
    request: ProxyGetProxyRequest$zodSchema,
};
export const tool$proxyGet = {
    name: "proxy-get",
    description: `GET

Proxies a downstream GET request to a service and injects the necessary credentials into a request stored in Vault. This allows you to have an additional security layer and logging without needing to rely on Unify for normalization.
**Note**: Vault will proxy all data to the downstream URL and method/verb in the headers.
`,
    scopes: ["read"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await proxyGet(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=proxyGet.js.map