/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { vaultCustomMappingsList } from "../../funcs/vaultCustomMappingsList.js";
import { VaultCustomMappingsAllRequest$zodSchema } from "../../models/vaultcustommappingsallop.js";
import { formatResult } from "../tools.js";
const args = {
    request: VaultCustomMappingsAllRequest$zodSchema,
};
export const tool$vaultCustomMappingsList = {
    name: "vault-custom-mappings-list",
    description: `List custom mappings

This endpoint returns a list of custom mappings.`,
    scopes: ["read"],
    annotations: {
        "title": "",
        "destructiveHint": false,
        "idempotentHint": false,
        "openWorldHint": false,
        "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
        const [result] = await vaultCustomMappingsList(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        return formatResult(result.value);
    },
};
//# sourceMappingURL=vaultCustomMappingsList.js.map