/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestResponse,
  BadRequestResponse$zodSchema,
} from "./badrequestresponse.js";
import {
  NotFoundResponse,
  NotFoundResponse$zodSchema,
} from "./notfoundresponse.js";
import { PaymentInput, PaymentInput$zodSchema } from "./paymentinput.js";
import {
  PaymentRequiredResponse,
  PaymentRequiredResponse$zodSchema,
} from "./paymentrequiredresponse.js";
import {
  UnauthorizedResponse,
  UnauthorizedResponse$zodSchema,
} from "./unauthorizedresponse.js";
import {
  UnexpectedErrorResponse,
  UnexpectedErrorResponse$zodSchema,
} from "./unexpectederrorresponse.js";
import {
  UnprocessableResponse,
  UnprocessableResponse$zodSchema,
} from "./unprocessableresponse.js";
import {
  UpdatePaymentResponse,
  UpdatePaymentResponse$zodSchema,
} from "./updatepaymentresponse.js";

export type AccountingPaymentsUpdateGlobals = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
};

export const AccountingPaymentsUpdateGlobals$zodSchema: z.ZodType<
  AccountingPaymentsUpdateGlobals
> = z.object({
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
});

export type AccountingPaymentsUpdateRequest = {
  id: string;
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
  xApideckServiceId?: string | undefined;
  xApideckCompanyId?: string | undefined;
  raw?: boolean | undefined;
  body: PaymentInput;
};

export const AccountingPaymentsUpdateRequest$zodSchema: z.ZodType<
  AccountingPaymentsUpdateRequest
> = z.object({
  body: PaymentInput$zodSchema,
  id: z.string().describe("ID of the record you are acting upon."),
  raw: z.boolean().default(false).describe(
    "Include raw response. Mostly used for debugging purposes",
  ),
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckCompanyId: z.string().describe(
    "The ID of the company to scope requests to. For connectors that support multi-company, this overrides the default company configured in connection settings.",
  ).optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
  xApideckServiceId: z.string().describe(
    "Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.",
  ).optional(),
});

export type AccountingPaymentsUpdateResponse =
  | UpdatePaymentResponse
  | BadRequestResponse
  | UnauthorizedResponse
  | PaymentRequiredResponse
  | NotFoundResponse
  | UnprocessableResponse
  | UnexpectedErrorResponse;

export const AccountingPaymentsUpdateResponse$zodSchema: z.ZodType<
  AccountingPaymentsUpdateResponse
> = z.union([
  UpdatePaymentResponse$zodSchema,
  BadRequestResponse$zodSchema,
  UnauthorizedResponse$zodSchema,
  PaymentRequiredResponse$zodSchema,
  NotFoundResponse$zodSchema,
  UnprocessableResponse$zodSchema,
  UnexpectedErrorResponse$zodSchema,
]);
