/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestResponse,
  BadRequestResponse$zodSchema,
} from "./badrequestresponse.js";
import {
  GetQuotesResponse,
  GetQuotesResponse$zodSchema,
} from "./getquotesresponse.js";
import {
  NotFoundResponse,
  NotFoundResponse$zodSchema,
} from "./notfoundresponse.js";
import {
  PaymentRequiredResponse,
  PaymentRequiredResponse$zodSchema,
} from "./paymentrequiredresponse.js";
import {
  UnauthorizedResponse,
  UnauthorizedResponse$zodSchema,
} from "./unauthorizedresponse.js";
import {
  UnexpectedErrorResponse,
  UnexpectedErrorResponse$zodSchema,
} from "./unexpectederrorresponse.js";
import {
  UnprocessableResponse,
  UnprocessableResponse$zodSchema,
} from "./unprocessableresponse.js";

export type AccountingQuotesAllGlobals = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
};

export const AccountingQuotesAllGlobals$zodSchema: z.ZodType<
  AccountingQuotesAllGlobals
> = z.object({
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
});

export type AccountingQuotesAllRequest = {
  raw?: boolean | undefined;
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
  xApideckServiceId?: string | undefined;
  xApideckCompanyId?: string | undefined;
  cursor?: string | null | undefined;
  limit?: number | undefined;
};

export const AccountingQuotesAllRequest$zodSchema: z.ZodType<
  AccountingQuotesAllRequest
> = z.object({
  cursor: z.string().describe(
    "Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response.",
  ).nullable().optional(),
  limit: z.int().default(20).describe(
    "Number of results to return. Minimum 1, Maximum 200, Default 20",
  ),
  raw: z.boolean().default(false).describe(
    "Include raw response. Mostly used for debugging purposes",
  ),
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckCompanyId: z.string().describe(
    "The ID of the company to scope requests to. For connectors that support multi-company, this overrides the default company configured in connection settings.",
  ).optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
  xApideckServiceId: z.string().describe(
    "Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.",
  ).optional(),
});

export type AccountingQuotesAllResponseResult =
  | GetQuotesResponse
  | BadRequestResponse
  | UnauthorizedResponse
  | PaymentRequiredResponse
  | NotFoundResponse
  | UnprocessableResponse
  | UnexpectedErrorResponse;

export const AccountingQuotesAllResponseResult$zodSchema: z.ZodType<
  AccountingQuotesAllResponseResult
> = z.union([
  GetQuotesResponse$zodSchema,
  BadRequestResponse$zodSchema,
  UnauthorizedResponse$zodSchema,
  PaymentRequiredResponse$zodSchema,
  NotFoundResponse$zodSchema,
  UnprocessableResponse$zodSchema,
  UnexpectedErrorResponse$zodSchema,
]);

export type AccountingQuotesAllResponse = {
  Result:
    | GetQuotesResponse
    | BadRequestResponse
    | UnauthorizedResponse
    | PaymentRequiredResponse
    | NotFoundResponse
    | UnprocessableResponse
    | UnexpectedErrorResponse;
};

export const AccountingQuotesAllResponse$zodSchema: z.ZodType<
  AccountingQuotesAllResponse
> = z.object({
  Result: z.union([
    GetQuotesResponse$zodSchema,
    BadRequestResponse$zodSchema,
    UnauthorizedResponse$zodSchema,
    PaymentRequiredResponse$zodSchema,
    NotFoundResponse$zodSchema,
    UnprocessableResponse$zodSchema,
    UnexpectedErrorResponse$zodSchema,
  ]),
});
