/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestResponse,
  BadRequestResponse$zodSchema,
} from "./badrequestresponse.js";
import { BillInput, BillInput$zodSchema } from "./bill.js";
import {
  NotFoundResponse,
  NotFoundResponse$zodSchema,
} from "./notfoundresponse.js";
import {
  PaymentRequiredResponse,
  PaymentRequiredResponse$zodSchema,
} from "./paymentrequiredresponse.js";
import {
  UnauthorizedResponse,
  UnauthorizedResponse$zodSchema,
} from "./unauthorizedresponse.js";
import {
  UnexpectedErrorResponse,
  UnexpectedErrorResponse$zodSchema,
} from "./unexpectederrorresponse.js";
import {
  UnprocessableResponse,
  UnprocessableResponse$zodSchema,
} from "./unprocessableresponse.js";
import {
  UpdateBillResponse,
  UpdateBillResponse$zodSchema,
} from "./updatebillresponse.js";

export type AccountingBillsUpdateGlobals = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
};

export const AccountingBillsUpdateGlobals$zodSchema: z.ZodType<
  AccountingBillsUpdateGlobals
> = z.object({
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
});

export type AccountingBillsUpdateRequest = {
  id: string;
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
  xApideckServiceId?: string | undefined;
  raw?: boolean | undefined;
  body: BillInput;
};

export const AccountingBillsUpdateRequest$zodSchema: z.ZodType<
  AccountingBillsUpdateRequest
> = z.object({
  body: BillInput$zodSchema,
  id: z.string().describe("ID of the record you are acting upon."),
  raw: z.boolean().default(false).describe(
    "Include raw response. Mostly used for debugging purposes",
  ),
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
  xApideckServiceId: z.string().describe(
    "Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.",
  ).optional(),
});

export type AccountingBillsUpdateResponse =
  | UpdateBillResponse
  | BadRequestResponse
  | UnauthorizedResponse
  | PaymentRequiredResponse
  | NotFoundResponse
  | UnprocessableResponse
  | UnexpectedErrorResponse;

export const AccountingBillsUpdateResponse$zodSchema: z.ZodType<
  AccountingBillsUpdateResponse
> = z.union([
  UpdateBillResponse$zodSchema,
  BadRequestResponse$zodSchema,
  UnauthorizedResponse$zodSchema,
  PaymentRequiredResponse$zodSchema,
  NotFoundResponse$zodSchema,
  UnprocessableResponse$zodSchema,
  UnexpectedErrorResponse$zodSchema,
]);
