/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ActivitiesFilter = {
  company_id?: string | undefined;
  owner_id?: string | undefined;
  contact_id?: string | undefined;
  updated_since?: string | undefined;
  type?: string | undefined;
};

export const ActivitiesFilter$zodSchema: z.ZodType<ActivitiesFilter> = z.object(
  {
    company_id: z.string().optional().describe("Company ID to filter on"),
    contact_id: z.string().optional().describe(
      "Primary contact ID to filter on",
    ),
    owner_id: z.string().optional().describe("Owner ID to filter on"),
    type: z.string().optional().describe("Type to filter on"),
    updated_since: z.iso.datetime({ offset: true }).optional(),
  },
);
