/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import {
  ActivityAttendee,
  ActivityAttendee$zodSchema,
  ActivityAttendeeInput,
  ActivityAttendeeInput$zodSchema,
} from "./activityattendee.js";
import { Address, Address$zodSchema } from "./address.js";
import {
  CustomFieldUnion,
  CustomFieldUnion$zodSchema,
} from "./customfieldunion.js";
import {
  PassThroughBody,
  PassThroughBody$zodSchema,
} from "./passthroughbody.js";

/**
 * The type of the activity
 */
export const ActivityType = {
  Call: "call",
  Meeting: "meeting",
  Email: "email",
  Note: "note",
  Task: "task",
  Deadline: "deadline",
  SendLetter: "send-letter",
  SendQuote: "send-quote",
  Other: "other",
} as const;
/**
 * The type of the activity
 */
export type ActivityType = OpenEnum<typeof ActivityType>;

export const ActivityType$zodSchema = z.union([
  z.enum([
    "call",
    "meeting",
    "email",
    "note",
    "task",
    "deadline",
    "send-letter",
    "send-quote",
    "other",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("The type of the activity");

export const ShowAs = {
  Free: "free",
  Busy: "busy",
} as const;
export type ShowAs = OpenEnum<typeof ShowAs>;

export const ShowAs$zodSchema = z.union([
  z.enum([
    "free",
    "busy",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]);

export type Activity = {
  id?: string | undefined;
  downstream_id?: string | null | undefined;
  activity_datetime?: string | null | undefined;
  duration_seconds?: number | null | undefined;
  user_id?: string | null | undefined;
  account_id?: string | null | undefined;
  contact_id?: string | null | undefined;
  company_id?: string | null | undefined;
  opportunity_id?: string | null | undefined;
  lead_id?: string | null | undefined;
  owner_id?: string | null | undefined;
  campaign_id?: string | null | undefined;
  case_id?: string | null | undefined;
  asset_id?: string | null | undefined;
  contract_id?: string | null | undefined;
  product_id?: string | null | undefined;
  solution_id?: string | null | undefined;
  custom_object_id?: string | null | undefined;
  type: ActivityType | null;
  title?: string | null | undefined;
  description?: string | null | undefined;
  note?: string | null | undefined;
  location?: string | null | undefined;
  location_address?: Address | undefined;
  all_day_event?: boolean | null | undefined;
  private?: boolean | null | undefined;
  group_event?: boolean | null | undefined;
  event_sub_type?: string | null | undefined;
  group_event_type?: string | null | undefined;
  child?: boolean | null | undefined;
  archived?: boolean | null | undefined;
  deleted?: boolean | null | undefined;
  show_as?: ShowAs | null | undefined;
  done?: boolean | null | undefined;
  start_datetime?: string | null | undefined;
  end_datetime?: string | null | undefined;
  duration_minutes?: number | null | undefined;
  activity_date?: string | null | undefined;
  end_date?: string | null | undefined;
  recurrent?: boolean | undefined;
  reminder_datetime?: string | null | undefined;
  reminder_set?: boolean | null | undefined;
  video_conference_url?: string | null | undefined;
  video_conference_id?: string | null | undefined;
  custom_fields?: Array<CustomFieldUnion> | undefined;
  attendees?: Array<ActivityAttendee> | undefined;
  custom_mappings?: { [k: string]: any } | null | undefined;
  updated_by?: string | null | undefined;
  created_by?: string | null | undefined;
  updated_at?: string | null | undefined;
  created_at?: string | null | undefined;
  pass_through?: Array<PassThroughBody> | undefined;
};

export const Activity$zodSchema: z.ZodType<Activity> = z.object({
  account_id: z.string().nullable().optional().describe(
    "The account related to the activity",
  ),
  activity_date: z.string().nullable().optional().describe(
    "The date of the activity",
  ),
  activity_datetime: z.string().nullable().optional().describe(
    "The date and time of the activity",
  ),
  all_day_event: z.boolean().nullable().optional().describe(
    "Whether the Activity is an all day event or not",
  ),
  archived: z.boolean().nullable().optional().describe(
    "Whether the activity is archived or not",
  ),
  asset_id: z.string().nullable().optional().describe(
    "The asset related to the activity",
  ),
  attendees: z.array(ActivityAttendee$zodSchema).optional(),
  campaign_id: z.string().nullable().optional().describe(
    "The campaign related to the activity",
  ),
  case_id: z.string().nullable().optional().describe(
    "The case related to the activity",
  ),
  child: z.boolean().nullable().optional().describe(
    "Whether the activity is a child of another activity or not",
  ),
  company_id: z.string().nullable().optional().describe(
    "The company related to the activity",
  ),
  contact_id: z.string().nullable().optional().describe(
    "The contact related to the activity",
  ),
  contract_id: z.string().nullable().optional().describe(
    "The contract related to the activity",
  ),
  created_at: z.string().nullable().optional().describe(
    "The date and time when the activity was created",
  ),
  created_by: z.string().nullable().optional().describe(
    "The user who created the activity",
  ),
  custom_fields: z.array(CustomFieldUnion$zodSchema).optional().describe(
    "Custom fields of the activity",
  ),
  custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe(
    "When custom mappings are configured on the resource, the result is included here.",
  ),
  custom_object_id: z.string().nullable().optional().describe(
    "The custom object related to the activity",
  ),
  deleted: z.boolean().nullable().optional().describe(
    "Whether the activity is deleted or not",
  ),
  description: z.string().nullable().optional().describe(
    "A description of the activity",
  ),
  done: z.boolean().nullable().optional().describe(
    "Whether the Activity is done or not",
  ),
  downstream_id: z.string().nullable().optional().describe(
    "The third-party API ID of original entity",
  ),
  duration_minutes: z.int().nullable().optional().describe(
    "The duration of the activity in minutes",
  ),
  duration_seconds: z.int().nullable().optional().describe(
    "The duration of the activity in seconds",
  ),
  end_date: z.string().nullable().optional().describe(
    "The end date of the activity",
  ),
  end_datetime: z.string().nullable().optional().describe(
    "The end date and time of the activity",
  ),
  event_sub_type: z.string().nullable().optional().describe(
    "The sub type of the group event",
  ),
  group_event: z.boolean().nullable().optional().describe(
    "Whether the Activity is a group event or not",
  ),
  group_event_type: z.string().nullable().optional().describe(
    "The type of the group event",
  ),
  id: z.string().optional().describe("The unique identifier of the activity"),
  lead_id: z.string().nullable().optional().describe(
    "The lead related to the activity",
  ),
  location: z.string().nullable().optional().describe(
    "The location of the activity",
  ),
  location_address: Address$zodSchema.optional(),
  note: z.string().nullable().optional().describe(
    "An internal note about the activity",
  ),
  opportunity_id: z.string().nullable().optional().describe(
    "The opportunity related to the activity",
  ),
  owner_id: z.string().nullable().optional().describe(
    "The owner of the activity",
  ),
  pass_through: z.array(PassThroughBody$zodSchema).optional().describe(
    "The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.",
  ),
  private: z.boolean().nullable().optional().describe(
    "Whether the Activity is private or not",
  ),
  product_id: z.string().nullable().optional().describe(
    "The product related to the activity",
  ),
  recurrent: z.boolean().optional().describe(
    "Whether the activity is recurrent or not",
  ),
  reminder_datetime: z.string().nullable().optional().describe(
    "The date and time of the reminder",
  ),
  reminder_set: z.boolean().nullable().optional().describe(
    "Whether the reminder is set or not",
  ),
  show_as: ShowAs$zodSchema.nullable().optional(),
  solution_id: z.string().nullable().optional().describe(
    "The solution related to the activity",
  ),
  start_datetime: z.string().nullable().optional().describe(
    "The start date and time of the activity",
  ),
  title: z.string().nullable().optional().describe("The title of the activity"),
  type: ActivityType$zodSchema.nullable().describe("The type of the activity"),
  updated_at: z.string().nullable().optional().describe(
    "The date and time when the activity was last updated",
  ),
  updated_by: z.string().nullable().optional().describe(
    "The user who last updated the activity",
  ),
  user_id: z.string().nullable().optional().describe(
    "The user related to the activity",
  ),
  video_conference_id: z.string().nullable().optional().describe(
    "The ID of the video conference",
  ),
  video_conference_url: z.string().nullable().optional().describe(
    "The URL of the video conference",
  ),
});

export type ActivityInput = {
  activity_datetime?: string | null | undefined;
  duration_seconds?: number | null | undefined;
  user_id?: string | null | undefined;
  account_id?: string | null | undefined;
  contact_id?: string | null | undefined;
  company_id?: string | null | undefined;
  opportunity_id?: string | null | undefined;
  lead_id?: string | null | undefined;
  owner_id?: string | null | undefined;
  campaign_id?: string | null | undefined;
  case_id?: string | null | undefined;
  asset_id?: string | null | undefined;
  contract_id?: string | null | undefined;
  product_id?: string | null | undefined;
  solution_id?: string | null | undefined;
  custom_object_id?: string | null | undefined;
  type: ActivityType | null;
  title?: string | null | undefined;
  description?: string | null | undefined;
  note?: string | null | undefined;
  location?: string | null | undefined;
  location_address?: Address | undefined;
  all_day_event?: boolean | null | undefined;
  private?: boolean | null | undefined;
  group_event?: boolean | null | undefined;
  event_sub_type?: string | null | undefined;
  group_event_type?: string | null | undefined;
  child?: boolean | null | undefined;
  archived?: boolean | null | undefined;
  deleted?: boolean | null | undefined;
  show_as?: ShowAs | null | undefined;
  done?: boolean | null | undefined;
  start_datetime?: string | null | undefined;
  end_datetime?: string | null | undefined;
  activity_date?: string | null | undefined;
  end_date?: string | null | undefined;
  recurrent?: boolean | undefined;
  reminder_datetime?: string | null | undefined;
  reminder_set?: boolean | null | undefined;
  video_conference_url?: string | null | undefined;
  video_conference_id?: string | null | undefined;
  custom_fields?: Array<CustomFieldUnion> | undefined;
  attendees?: Array<ActivityAttendeeInput> | undefined;
  pass_through?: Array<PassThroughBody> | undefined;
};

export const ActivityInput$zodSchema: z.ZodType<ActivityInput> = z.object({
  account_id: z.string().nullable().optional().describe(
    "The account related to the activity",
  ),
  activity_date: z.string().nullable().optional().describe(
    "The date of the activity",
  ),
  activity_datetime: z.string().nullable().optional().describe(
    "The date and time of the activity",
  ),
  all_day_event: z.boolean().nullable().optional().describe(
    "Whether the Activity is an all day event or not",
  ),
  archived: z.boolean().nullable().optional().describe(
    "Whether the activity is archived or not",
  ),
  asset_id: z.string().nullable().optional().describe(
    "The asset related to the activity",
  ),
  attendees: z.array(ActivityAttendeeInput$zodSchema).optional(),
  campaign_id: z.string().nullable().optional().describe(
    "The campaign related to the activity",
  ),
  case_id: z.string().nullable().optional().describe(
    "The case related to the activity",
  ),
  child: z.boolean().nullable().optional().describe(
    "Whether the activity is a child of another activity or not",
  ),
  company_id: z.string().nullable().optional().describe(
    "The company related to the activity",
  ),
  contact_id: z.string().nullable().optional().describe(
    "The contact related to the activity",
  ),
  contract_id: z.string().nullable().optional().describe(
    "The contract related to the activity",
  ),
  custom_fields: z.array(CustomFieldUnion$zodSchema).optional().describe(
    "Custom fields of the activity",
  ),
  custom_object_id: z.string().nullable().optional().describe(
    "The custom object related to the activity",
  ),
  deleted: z.boolean().nullable().optional().describe(
    "Whether the activity is deleted or not",
  ),
  description: z.string().nullable().optional().describe(
    "A description of the activity",
  ),
  done: z.boolean().nullable().optional().describe(
    "Whether the Activity is done or not",
  ),
  duration_seconds: z.int().nullable().optional().describe(
    "The duration of the activity in seconds",
  ),
  end_date: z.string().nullable().optional().describe(
    "The end date of the activity",
  ),
  end_datetime: z.string().nullable().optional().describe(
    "The end date and time of the activity",
  ),
  event_sub_type: z.string().nullable().optional().describe(
    "The sub type of the group event",
  ),
  group_event: z.boolean().nullable().optional().describe(
    "Whether the Activity is a group event or not",
  ),
  group_event_type: z.string().nullable().optional().describe(
    "The type of the group event",
  ),
  lead_id: z.string().nullable().optional().describe(
    "The lead related to the activity",
  ),
  location: z.string().nullable().optional().describe(
    "The location of the activity",
  ),
  location_address: Address$zodSchema.optional(),
  note: z.string().nullable().optional().describe(
    "An internal note about the activity",
  ),
  opportunity_id: z.string().nullable().optional().describe(
    "The opportunity related to the activity",
  ),
  owner_id: z.string().nullable().optional().describe(
    "The owner of the activity",
  ),
  pass_through: z.array(PassThroughBody$zodSchema).optional().describe(
    "The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.",
  ),
  private: z.boolean().nullable().optional().describe(
    "Whether the Activity is private or not",
  ),
  product_id: z.string().nullable().optional().describe(
    "The product related to the activity",
  ),
  recurrent: z.boolean().optional().describe(
    "Whether the activity is recurrent or not",
  ),
  reminder_datetime: z.string().nullable().optional().describe(
    "The date and time of the reminder",
  ),
  reminder_set: z.boolean().nullable().optional().describe(
    "Whether the reminder is set or not",
  ),
  show_as: ShowAs$zodSchema.nullable().optional(),
  solution_id: z.string().nullable().optional().describe(
    "The solution related to the activity",
  ),
  start_datetime: z.string().nullable().optional().describe(
    "The start date and time of the activity",
  ),
  title: z.string().nullable().optional().describe("The title of the activity"),
  type: ActivityType$zodSchema.nullable().describe("The type of the activity"),
  user_id: z.string().nullable().optional().describe(
    "The user related to the activity",
  ),
  video_conference_id: z.string().nullable().optional().describe(
    "The ID of the video conference",
  ),
  video_conference_url: z.string().nullable().optional().describe(
    "The URL of the video conference",
  ),
});
