/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";

/**
 * Status of the API. APIs with status live or beta are callable.
 */
export const ApiStatus = {
  Live: "live",
  Beta: "beta",
  Development: "development",
  Considering: "considering",
} as const;
/**
 * Status of the API. APIs with status live or beta are callable.
 */
export type ApiStatus = OpenEnum<typeof ApiStatus>;

export const ApiStatus$zodSchema = z.union([
  z.enum([
    "live",
    "beta",
    "development",
    "considering",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("Status of the API. APIs with status live or beta are callable.");
