/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import { Currency, Currency$zodSchema } from "./currency.js";
import {
  CustomFieldUnion,
  CustomFieldUnion$zodSchema,
} from "./customfieldunion.js";

/**
 * Type of the bank account.
 */
export const BankAccountType = {
  Bank: "bank",
  CreditCard: "credit_card",
} as const;
/**
 * Type of the bank account.
 */
export type BankAccountType = OpenEnum<typeof BankAccountType>;

export const BankAccountType$zodSchema = z.union([
  z.enum([
    "bank",
    "credit_card",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("Type of the bank account.");

/**
 * Current status of the bank feed.
 */
export const FeedStatus = {
  Pending: "pending",
  Rejected: "rejected",
} as const;
/**
 * Current status of the bank feed.
 */
export type FeedStatus = OpenEnum<typeof FeedStatus>;

export const FeedStatus$zodSchema = z.union([
  z.enum([
    "pending",
    "rejected",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("Current status of the bank feed.");

export type BankFeedAccount = {
  id: string;
  bank_account_type?: BankAccountType | undefined;
  source_account_id?: string | undefined;
  target_account_id?: string | undefined;
  target_account_name?: string | undefined;
  target_account_number?: string | undefined;
  currency?: Currency | null | undefined;
  feed_status?: FeedStatus | undefined;
  country?: string | null | undefined;
  custom_fields?: Array<CustomFieldUnion> | undefined;
  custom_mappings?: { [k: string]: any } | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  updated_by?: string | null | undefined;
  created_by?: string | null | undefined;
};

export const BankFeedAccount$zodSchema: z.ZodType<BankFeedAccount> = z.object({
  bank_account_type: BankAccountType$zodSchema.optional().describe(
    "Type of the bank account.",
  ),
  country: z.string().nullable().optional().describe(
    "Country code according to ISO 3166-1 alpha-2.",
  ),
  created_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date and time when the object was created.",
  ),
  created_by: z.string().nullable().optional().describe(
    "The user who created the object.",
  ),
  currency: Currency$zodSchema.nullable().optional().describe(
    "Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).",
  ),
  custom_fields: z.array(CustomFieldUnion$zodSchema).optional(),
  custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe(
    "When custom mappings are configured on the resource, the result is included here.",
  ),
  feed_status: FeedStatus$zodSchema.optional().describe(
    "Current status of the bank feed.",
  ),
  id: z.string().describe("A unique identifier for an object."),
  source_account_id: z.string().optional().describe(
    "The source account's unique identifier.",
  ),
  target_account_id: z.string().optional().describe(
    "The target account's unique identifier in the accounting connector.",
  ),
  target_account_name: z.string().optional().describe(
    "Name associated with the target account.",
  ),
  target_account_number: z.string().optional().describe(
    "Account number of the destination bank account.",
  ),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date and time when the object was last updated.",
  ),
  updated_by: z.string().nullable().optional().describe(
    "The user who last updated the object.",
  ),
});

export type BankFeedAccountInput = {
  bank_account_type?: BankAccountType | undefined;
  source_account_id?: string | undefined;
  target_account_id?: string | undefined;
  target_account_name?: string | undefined;
  target_account_number?: string | undefined;
  currency?: Currency | null | undefined;
  feed_status?: FeedStatus | undefined;
  country?: string | null | undefined;
  custom_fields?: Array<CustomFieldUnion> | undefined;
};

export const BankFeedAccountInput$zodSchema: z.ZodType<BankFeedAccountInput> = z
  .object({
    bank_account_type: BankAccountType$zodSchema.optional().describe(
      "Type of the bank account.",
    ),
    country: z.string().nullable().optional().describe(
      "Country code according to ISO 3166-1 alpha-2.",
    ),
    currency: Currency$zodSchema.nullable().optional().describe(
      "Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).",
    ),
    custom_fields: z.array(CustomFieldUnion$zodSchema).optional(),
    feed_status: FeedStatus$zodSchema.optional().describe(
      "Current status of the bank feed.",
    ),
    source_account_id: z.string().optional().describe(
      "The source account's unique identifier.",
    ),
    target_account_id: z.string().optional().describe(
      "The target account's unique identifier in the accounting connector.",
    ),
    target_account_name: z.string().optional().describe(
      "Name associated with the target account.",
    ),
    target_account_number: z.string().optional().describe(
      "Account number of the destination bank account.",
    ),
  });
