/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import { SortDirection, SortDirection$zodSchema } from "./sortdirection.js";

/**
 * The field to sort by
 */
export const BankAccountsSortSortBy = {
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
} as const;
/**
 * The field to sort by
 */
export type BankAccountsSortSortBy = OpenEnum<typeof BankAccountsSortSortBy>;

export const BankAccountsSortSortBy$zodSchema = z.union([
  z.enum([
    "created_at",
    "updated_at",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("The field to sort by");

export type BankAccountsSort = {
  by?: BankAccountsSortSortBy | undefined;
  direction?: SortDirection | undefined;
};

export const BankAccountsSort$zodSchema: z.ZodType<BankAccountsSort> = z.object(
  {
    by: BankAccountsSortSortBy$zodSchema.default("updated_at").describe(
      "The field to sort by",
    ),
    direction: SortDirection$zodSchema.default("asc").describe(
      "The direction in which to sort the results",
    ),
  },
);
