/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import { Currency, Currency$zodSchema } from "./currency.js";
import {
  CustomFieldUnion,
  CustomFieldUnion$zodSchema,
} from "./customfieldunion.js";
import {
  LinkedLedgerAccount,
  LinkedLedgerAccount$zodSchema,
} from "./linkedledgeraccount.js";
import { LinkedSupplier, LinkedSupplier$zodSchema } from "./linkedsupplier.js";
import {
  LinkedSupplierInput,
  LinkedSupplierInput$zodSchema,
} from "./linkedsupplierinput.js";
import {
  LinkedTrackingCategory,
  LinkedTrackingCategory$zodSchema,
} from "./linkedtrackingcategory.js";
import {
  PassThroughBody,
  PassThroughBody$zodSchema,
} from "./passthroughbody.js";
import { PaymentStatus, PaymentStatus$zodSchema } from "./paymentstatus.js";

/**
 * Type of payment
 */
export const BillPaymentType = {
  AccountsPayableCredit: "accounts_payable_credit",
  AccountsPayableOverpayment: "accounts_payable_overpayment",
  AccountsPayablePrepayment: "accounts_payable_prepayment",
  AccountsPayable: "accounts_payable",
} as const;
/**
 * Type of payment
 */
export type BillPaymentType = OpenEnum<typeof BillPaymentType>;

export const BillPaymentType$zodSchema = z.union([
  z.enum([
    "accounts_payable_credit",
    "accounts_payable_overpayment",
    "accounts_payable_prepayment",
    "accounts_payable",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("Type of payment");

/**
 * Type of entity this payment should be attributed to.
 */
export const BillPaymentAllocationType = {
  Bill: "bill",
  Expense: "expense",
  CreditMemo: "credit_memo",
  OverPayment: "over_payment",
  PrePayment: "pre_payment",
  JournalEntry: "journal_entry",
  Other: "other",
} as const;
/**
 * Type of entity this payment should be attributed to.
 */
export type BillPaymentAllocationType = OpenEnum<
  typeof BillPaymentAllocationType
>;

export const BillPaymentAllocationType$zodSchema = z.union([
  z.enum([
    "bill",
    "expense",
    "credit_memo",
    "over_payment",
    "pre_payment",
    "journal_entry",
    "other",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("Type of entity this payment should be attributed to.");

export type BillPaymentAllocation = {
  id?: string | null | undefined;
  type?: BillPaymentAllocationType | undefined;
  code?: string | undefined;
  amount?: number | null | undefined;
  allocation_id?: string | undefined;
};

export const BillPaymentAllocation$zodSchema: z.ZodType<BillPaymentAllocation> =
  z.object({
    allocation_id: z.string().optional().describe(
      "Unique identifier of the allocation",
    ),
    amount: z.number().nullable().optional().describe(
      "Amount of payment that should be attributed to this allocation. If null, the total_amount will be used.",
    ),
    code: z.string().optional(),
    id: z.string().nullable().optional().describe(
      "A unique identifier for an object.",
    ),
    type: BillPaymentAllocationType$zodSchema.optional().describe(
      "Type of entity this payment should be attributed to.",
    ),
  });

export type BillPayment = {
  id: string;
  downstream_id?: string | null | undefined;
  currency?: Currency | null | undefined;
  currency_rate?: number | null | undefined;
  total_amount: number | null;
  reference?: string | null | undefined;
  payment_method?: string | null | undefined;
  payment_method_reference?: string | null | undefined;
  payment_method_id?: string | null | undefined;
  account?: LinkedLedgerAccount | null | undefined;
  transaction_date: string | null;
  supplier?: LinkedSupplier | null | undefined;
  company_id?: string | null | undefined;
  reconciled?: boolean | null | undefined;
  status?: PaymentStatus | undefined;
  type?: BillPaymentType | undefined;
  allocations?: Array<BillPaymentAllocation> | undefined;
  note?: string | null | undefined;
  number?: string | null | undefined;
  tracking_categories?: Array<LinkedTrackingCategory | null> | null | undefined;
  custom_fields?: Array<CustomFieldUnion> | undefined;
  row_version?: string | null | undefined;
  display_id?: string | null | undefined;
  custom_mappings?: { [k: string]: any } | null | undefined;
  updated_by?: string | null | undefined;
  created_by?: string | null | undefined;
  created_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  pass_through?: Array<PassThroughBody> | undefined;
};

export const BillPayment$zodSchema: z.ZodType<BillPayment> = z.object({
  account: LinkedLedgerAccount$zodSchema.nullable().optional(),
  allocations: z.array(z.lazy(() => BillPaymentAllocation$zodSchema))
    .optional(),
  company_id: z.string().nullable().optional().describe(
    "The company ID the transaction belongs to",
  ),
  created_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date and time when the object was created.",
  ),
  created_by: z.string().nullable().optional().describe(
    "The user who created the object.",
  ),
  currency: Currency$zodSchema.nullable().optional().describe(
    "Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).",
  ),
  currency_rate: z.number().nullable().optional().describe(
    "Currency Exchange Rate at the time entity was recorded/generated.",
  ),
  custom_fields: z.array(CustomFieldUnion$zodSchema).optional(),
  custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe(
    "When custom mappings are configured on the resource, the result is included here.",
  ),
  display_id: z.string().nullable().optional().describe("Id to be displayed."),
  downstream_id: z.string().nullable().optional().describe(
    "The third-party API ID of original entity",
  ),
  id: z.string().describe("A unique identifier for an object."),
  note: z.string().nullable().optional().describe(
    "Note associated with the transaction",
  ),
  number: z.string().nullable().optional().describe(
    "Number associated with the transaction",
  ),
  pass_through: z.array(PassThroughBody$zodSchema).optional().describe(
    "The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.",
  ),
  payment_method: z.string().nullable().optional().describe(
    "Payment method used for the transaction, such as cash, credit card, bank transfer, or check",
  ),
  payment_method_id: z.string().nullable().optional().describe(
    "A unique identifier for an object.",
  ),
  payment_method_reference: z.string().nullable().optional().describe(
    "Optional reference message returned by payment method on processing",
  ),
  reconciled: z.boolean().nullable().optional().describe(
    "Indicates if the transaction has been reconciled.",
  ),
  reference: z.string().nullable().optional().describe(
    "Optional transaction reference message ie: Debit remittance detail.",
  ),
  row_version: z.string().nullable().optional().describe(
    "A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.",
  ),
  status: PaymentStatus$zodSchema.optional().describe("Status of payment"),
  supplier: LinkedSupplier$zodSchema.nullable().optional().describe(
    "The supplier this entity is linked to.",
  ),
  total_amount: z.number().nullable().describe(
    "The total amount of the transaction or record",
  ),
  tracking_categories: z.array(LinkedTrackingCategory$zodSchema.nullable())
    .nullable().optional().describe("A list of linked tracking categories."),
  transaction_date: z.iso.datetime({ offset: true }).nullable().describe(
    "The date of the transaction - YYYY:MM::DDThh:mm:ss.sTZD",
  ),
  type: BillPaymentType$zodSchema.optional().describe("Type of payment"),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date and time when the object was last updated.",
  ),
  updated_by: z.string().nullable().optional().describe(
    "The user who last updated the object.",
  ),
});

export type BillPaymentAllocationInput = {
  id?: string | null | undefined;
  type?: BillPaymentAllocationType | undefined;
  amount?: number | null | undefined;
  allocation_id?: string | undefined;
};

export const BillPaymentAllocationInput$zodSchema: z.ZodType<
  BillPaymentAllocationInput
> = z.object({
  allocation_id: z.string().optional().describe(
    "Unique identifier of the allocation",
  ),
  amount: z.number().nullable().optional().describe(
    "Amount of payment that should be attributed to this allocation. If null, the total_amount will be used.",
  ),
  id: z.string().nullable().optional().describe(
    "A unique identifier for an object.",
  ),
  type: BillPaymentAllocationType$zodSchema.optional().describe(
    "Type of entity this payment should be attributed to.",
  ),
});

export type BillPaymentInput = {
  currency?: Currency | null | undefined;
  currency_rate?: number | null | undefined;
  total_amount: number | null;
  reference?: string | null | undefined;
  payment_method?: string | null | undefined;
  payment_method_reference?: string | null | undefined;
  payment_method_id?: string | null | undefined;
  account?: LinkedLedgerAccount | null | undefined;
  transaction_date: string | null;
  supplier?: LinkedSupplierInput | null | undefined;
  company_id?: string | null | undefined;
  reconciled?: boolean | null | undefined;
  status?: PaymentStatus | undefined;
  type?: BillPaymentType | undefined;
  allocations?: Array<BillPaymentAllocationInput> | undefined;
  note?: string | null | undefined;
  number?: string | null | undefined;
  tracking_categories?: Array<LinkedTrackingCategory | null> | null | undefined;
  custom_fields?: Array<CustomFieldUnion> | undefined;
  row_version?: string | null | undefined;
  display_id?: string | null | undefined;
  pass_through?: Array<PassThroughBody> | undefined;
};

export const BillPaymentInput$zodSchema: z.ZodType<BillPaymentInput> = z.object(
  {
    account: LinkedLedgerAccount$zodSchema.nullable().optional(),
    allocations: z.array(z.lazy(() => BillPaymentAllocationInput$zodSchema))
      .optional(),
    company_id: z.string().nullable().optional().describe(
      "The company ID the transaction belongs to",
    ),
    currency: Currency$zodSchema.nullable().optional().describe(
      "Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).",
    ),
    currency_rate: z.number().nullable().optional().describe(
      "Currency Exchange Rate at the time entity was recorded/generated.",
    ),
    custom_fields: z.array(CustomFieldUnion$zodSchema).optional(),
    display_id: z.string().nullable().optional().describe(
      "Id to be displayed.",
    ),
    note: z.string().nullable().optional().describe(
      "Note associated with the transaction",
    ),
    number: z.string().nullable().optional().describe(
      "Number associated with the transaction",
    ),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe(
      "The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.",
    ),
    payment_method: z.string().nullable().optional().describe(
      "Payment method used for the transaction, such as cash, credit card, bank transfer, or check",
    ),
    payment_method_id: z.string().nullable().optional().describe(
      "A unique identifier for an object.",
    ),
    payment_method_reference: z.string().nullable().optional().describe(
      "Optional reference message returned by payment method on processing",
    ),
    reconciled: z.boolean().nullable().optional().describe(
      "Indicates if the transaction has been reconciled.",
    ),
    reference: z.string().nullable().optional().describe(
      "Optional transaction reference message ie: Debit remittance detail.",
    ),
    row_version: z.string().nullable().optional().describe(
      "A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.",
    ),
    status: PaymentStatus$zodSchema.optional().describe("Status of payment"),
    supplier: LinkedSupplierInput$zodSchema.nullable().optional().describe(
      "The supplier this entity is linked to.",
    ),
    total_amount: z.number().nullable().describe(
      "The total amount of the transaction or record",
    ),
    tracking_categories: z.array(LinkedTrackingCategory$zodSchema.nullable())
      .nullable().optional().describe("A list of linked tracking categories."),
    transaction_date: z.iso.datetime({ offset: true }).nullable().describe(
      "The date of the transaction - YYYY:MM::DDThh:mm:ss.sTZD",
    ),
    type: BillPaymentType$zodSchema.optional().describe("Type of payment"),
  },
);
