/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import { BankAccount, BankAccount$zodSchema } from "./bankaccount.js";
import { BillLineItem, BillLineItem$zodSchema } from "./billlineitem.js";
import {
  BillLineItemInput,
  BillLineItemInput$zodSchema,
} from "./billlineiteminput.js";
import { Currency, Currency$zodSchema } from "./currency.js";
import {
  CustomFieldUnion,
  CustomFieldUnion$zodSchema,
} from "./customfieldunion.js";
import {
  LinkedAttachment,
  LinkedAttachment$zodSchema,
} from "./linkedattachment.js";
import {
  LinkedLedgerAccount,
  LinkedLedgerAccount$zodSchema,
} from "./linkedledgeraccount.js";
import {
  LinkedPaymentAllocations,
  LinkedPaymentAllocations$zodSchema,
} from "./linkedpaymentallocations.js";
import { LinkedSupplier, LinkedSupplier$zodSchema } from "./linkedsupplier.js";
import {
  LinkedSupplierInput,
  LinkedSupplierInput$zodSchema,
} from "./linkedsupplierinput.js";
import {
  LinkedTrackingCategory,
  LinkedTrackingCategory$zodSchema,
} from "./linkedtrackingcategory.js";
import {
  PassThroughBody,
  PassThroughBody$zodSchema,
} from "./passthroughbody.js";

/**
 * Invoice status
 */
export const BillStatus = {
  Draft: "draft",
  Submitted: "submitted",
  Authorised: "authorised",
  PartiallyPaid: "partially_paid",
  Paid: "paid",
  Void: "void",
  Credit: "credit",
  Deleted: "deleted",
  Posted: "posted",
} as const;
/**
 * Invoice status
 */
export type BillStatus = OpenEnum<typeof BillStatus>;

export const BillStatus$zodSchema = z.union([
  z.enum([
    "draft",
    "submitted",
    "authorised",
    "partially_paid",
    "paid",
    "void",
    "credit",
    "deleted",
    "posted",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("Invoice status");

/**
 * Type of amortization
 */
export const BillAmortizationType = {
  Manual: "manual",
  Receipt: "receipt",
  Schedule: "schedule",
  Other: "other",
} as const;
/**
 * Type of amortization
 */
export type BillAmortizationType = OpenEnum<typeof BillAmortizationType>;

export const BillAmortizationType$zodSchema = z.union([
  z.enum([
    "manual",
    "receipt",
    "schedule",
    "other",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("Type of amortization");

export type Bill = {
  id?: string | undefined;
  downstream_id?: string | null | undefined;
  display_id?: string | null | undefined;
  bill_number?: string | null | undefined;
  supplier?: LinkedSupplier | null | undefined;
  company_id?: string | null | undefined;
  location_id?: string | null | undefined;
  department_id?: string | null | undefined;
  currency?: Currency | null | undefined;
  currency_rate?: number | null | undefined;
  tax_inclusive?: boolean | null | undefined;
  bill_date?: string | null | undefined;
  due_date?: string | null | undefined;
  paid_date?: string | null | undefined;
  po_number?: string | null | undefined;
  reference?: string | null | undefined;
  line_items?: Array<BillLineItem> | undefined;
  terms?: string | null | undefined;
  terms_id?: string | null | undefined;
  balance?: number | null | undefined;
  deposit?: number | null | undefined;
  sub_total?: number | null | undefined;
  total_tax?: number | null | undefined;
  total?: number | null | undefined;
  tax_code?: string | null | undefined;
  notes?: string | null | undefined;
  status?: BillStatus | null | undefined;
  ledger_account?: LinkedLedgerAccount | null | undefined;
  payment_method?: string | null | undefined;
  channel?: string | null | undefined;
  language?: string | null | undefined;
  accounting_by_row?: boolean | null | undefined;
  bank_account?: BankAccount | undefined;
  discount_percentage?: number | null | undefined;
  template_id?: string | null | undefined;
  approved_by?: string | null | undefined;
  amortization_type?: BillAmortizationType | null | undefined;
  tax_method?: string | null | undefined;
  document_received?: boolean | null | undefined;
  source_document_url?: string | null | undefined;
  payment_allocations?:
    | Array<LinkedPaymentAllocations | null>
    | null
    | undefined;
  tracking_categories?: Array<LinkedTrackingCategory | null> | null | undefined;
  updated_by?: string | null | undefined;
  created_by?: string | null | undefined;
  updated_at?: string | null | undefined;
  created_at?: string | null | undefined;
  row_version?: string | null | undefined;
  custom_fields?: Array<CustomFieldUnion> | undefined;
  custom_mappings?: { [k: string]: any } | null | undefined;
  pass_through?: Array<PassThroughBody> | undefined;
  accounting_period?: string | null | undefined;
  attachments?: Array<LinkedAttachment | null> | undefined;
};

export const Bill$zodSchema: z.ZodType<Bill> = z.object({
  accounting_by_row: z.boolean().nullable().optional().describe(
    "Indicates if accounting by row is used (true) or not (false). Accounting by row means that a separate ledger transaction is created for each row.",
  ),
  accounting_period: z.string().nullable().optional().describe(
    "Accounting period",
  ),
  amortization_type: BillAmortizationType$zodSchema.nullable().optional()
    .describe("Type of amortization"),
  approved_by: z.string().nullable().optional().describe(
    "The user who approved the bill",
  ),
  attachments: z.array(LinkedAttachment$zodSchema.nullable()).optional(),
  balance: z.number().nullable().optional().describe("Balance of bill due."),
  bank_account: BankAccount$zodSchema.optional(),
  bill_date: z.string().date().nullable().optional().describe(
    "Date bill was issued - YYYY-MM-DD.",
  ),
  bill_number: z.string().nullable().optional().describe(
    "Reference to supplier bill number",
  ),
  channel: z.string().nullable().optional().describe(
    "The channel through which the transaction is processed.",
  ),
  company_id: z.string().nullable().optional().describe(
    "The company ID the transaction belongs to",
  ),
  created_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date and time when the object was created.",
  ),
  created_by: z.string().nullable().optional().describe(
    "The user who created the object.",
  ),
  currency: Currency$zodSchema.nullable().optional().describe(
    "Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).",
  ),
  currency_rate: z.number().nullable().optional().describe(
    "Currency Exchange Rate at the time entity was recorded/generated.",
  ),
  custom_fields: z.array(CustomFieldUnion$zodSchema).optional(),
  custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe(
    "When custom mappings are configured on the resource, the result is included here.",
  ),
  department_id: z.string().nullable().optional().describe(
    "The ID of the department",
  ),
  deposit: z.number().nullable().optional().describe(
    "Amount of deposit made to this bill.",
  ),
  discount_percentage: z.number().nullable().optional().describe(
    "Discount percentage applied to this transaction.",
  ),
  display_id: z.string().nullable().optional().describe("Id to be displayed."),
  document_received: z.boolean().nullable().optional().describe(
    "Whether the document has been received",
  ),
  downstream_id: z.string().nullable().optional().describe(
    "The third-party API ID of original entity",
  ),
  due_date: z.string().date().nullable().optional().describe(
    "The due date is the date on which a payment is scheduled to be received - YYYY-MM-DD.",
  ),
  id: z.string().optional().describe("A unique identifier for an object."),
  language: z.string().nullable().optional().describe(
    "language code according to ISO 639-1. For the United States - EN",
  ),
  ledger_account: LinkedLedgerAccount$zodSchema.nullable().optional(),
  line_items: z.array(BillLineItem$zodSchema).optional(),
  location_id: z.string().nullable().optional().describe(
    "The ID of the location",
  ),
  notes: z.string().nullable().optional(),
  paid_date: z.string().date().nullable().optional().describe(
    "The paid date is the date on which a payment was sent to the supplier - YYYY-MM-DD.",
  ),
  pass_through: z.array(PassThroughBody$zodSchema).optional().describe(
    "The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.",
  ),
  payment_allocations: z.array(LinkedPaymentAllocations$zodSchema.nullable())
    .nullable().optional().describe("A list of linked payment allocations."),
  payment_method: z.string().nullable().optional().describe(
    "Payment method used for the transaction, such as cash, credit card, bank transfer, or check",
  ),
  po_number: z.string().nullable().optional().describe(
    "A PO Number uniquely identifies a purchase order and is generally defined by the buyer. The buyer will match the PO number in the invoice to the Purchase Order.",
  ),
  reference: z.string().nullable().optional().describe(
    "Optional reference identifier for the transaction.",
  ),
  row_version: z.string().nullable().optional().describe(
    "A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.",
  ),
  source_document_url: z.string().nullable().optional().describe(
    "URL link to a source document - shown as 'Go to [appName]' in the downstream app. Currently only supported for Xero.",
  ),
  status: BillStatus$zodSchema.nullable().optional().describe("Invoice status"),
  sub_total: z.number().nullable().optional().describe(
    "Subtotal amount, normally before tax.",
  ),
  supplier: LinkedSupplier$zodSchema.nullable().optional().describe(
    "The supplier this entity is linked to.",
  ),
  tax_code: z.string().nullable().optional().describe(
    "Applicable tax id/code override if tax is not supplied on a line item basis.",
  ),
  tax_inclusive: z.boolean().nullable().optional().describe(
    "Amounts are including tax",
  ),
  tax_method: z.string().nullable().optional().describe(
    "Method of tax calculation",
  ),
  template_id: z.string().nullable().optional().describe(
    "Optional bill template",
  ),
  terms: z.string().nullable().optional().describe("Terms of payment."),
  terms_id: z.string().nullable().optional().describe(
    "The ID of the payment terms",
  ),
  total: z.number().nullable().optional().describe(
    "Total amount of bill, including tax.",
  ),
  total_tax: z.number().nullable().optional().describe(
    "Total tax amount applied to this transaction.",
  ),
  tracking_categories: z.array(LinkedTrackingCategory$zodSchema.nullable())
    .nullable().optional().describe("A list of linked tracking categories."),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date and time when the object was last updated.",
  ),
  updated_by: z.string().nullable().optional().describe(
    "The user who last updated the object.",
  ),
});

export type BillInput = {
  display_id?: string | null | undefined;
  bill_number?: string | null | undefined;
  supplier?: LinkedSupplierInput | null | undefined;
  company_id?: string | null | undefined;
  location_id?: string | null | undefined;
  department_id?: string | null | undefined;
  currency?: Currency | null | undefined;
  currency_rate?: number | null | undefined;
  tax_inclusive?: boolean | null | undefined;
  bill_date?: string | null | undefined;
  due_date?: string | null | undefined;
  paid_date?: string | null | undefined;
  po_number?: string | null | undefined;
  reference?: string | null | undefined;
  line_items?: Array<BillLineItemInput> | undefined;
  terms?: string | null | undefined;
  terms_id?: string | null | undefined;
  balance?: number | null | undefined;
  deposit?: number | null | undefined;
  sub_total?: number | null | undefined;
  total_tax?: number | null | undefined;
  total?: number | null | undefined;
  tax_code?: string | null | undefined;
  notes?: string | null | undefined;
  status?: BillStatus | null | undefined;
  ledger_account?: LinkedLedgerAccount | null | undefined;
  payment_method?: string | null | undefined;
  channel?: string | null | undefined;
  language?: string | null | undefined;
  accounting_by_row?: boolean | null | undefined;
  bank_account?: BankAccount | undefined;
  discount_percentage?: number | null | undefined;
  template_id?: string | null | undefined;
  approved_by?: string | null | undefined;
  amortization_type?: BillAmortizationType | null | undefined;
  tax_method?: string | null | undefined;
  document_received?: boolean | null | undefined;
  source_document_url?: string | null | undefined;
  payment_allocations?:
    | Array<LinkedPaymentAllocations | null>
    | null
    | undefined;
  tracking_categories?: Array<LinkedTrackingCategory | null> | null | undefined;
  row_version?: string | null | undefined;
  custom_fields?: Array<CustomFieldUnion> | undefined;
  pass_through?: Array<PassThroughBody> | undefined;
  accounting_period?: string | null | undefined;
  attachments?: Array<LinkedAttachment | null> | undefined;
};

export const BillInput$zodSchema: z.ZodType<BillInput> = z.object({
  accounting_by_row: z.boolean().nullable().optional().describe(
    "Indicates if accounting by row is used (true) or not (false). Accounting by row means that a separate ledger transaction is created for each row.",
  ),
  accounting_period: z.string().nullable().optional().describe(
    "Accounting period",
  ),
  amortization_type: BillAmortizationType$zodSchema.nullable().optional()
    .describe("Type of amortization"),
  approved_by: z.string().nullable().optional().describe(
    "The user who approved the bill",
  ),
  attachments: z.array(LinkedAttachment$zodSchema.nullable()).optional(),
  balance: z.number().nullable().optional().describe("Balance of bill due."),
  bank_account: BankAccount$zodSchema.optional(),
  bill_date: z.string().date().nullable().optional().describe(
    "Date bill was issued - YYYY-MM-DD.",
  ),
  bill_number: z.string().nullable().optional().describe(
    "Reference to supplier bill number",
  ),
  channel: z.string().nullable().optional().describe(
    "The channel through which the transaction is processed.",
  ),
  company_id: z.string().nullable().optional().describe(
    "The company ID the transaction belongs to",
  ),
  currency: Currency$zodSchema.nullable().optional().describe(
    "Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).",
  ),
  currency_rate: z.number().nullable().optional().describe(
    "Currency Exchange Rate at the time entity was recorded/generated.",
  ),
  custom_fields: z.array(CustomFieldUnion$zodSchema).optional(),
  department_id: z.string().nullable().optional().describe(
    "The ID of the department",
  ),
  deposit: z.number().nullable().optional().describe(
    "Amount of deposit made to this bill.",
  ),
  discount_percentage: z.number().nullable().optional().describe(
    "Discount percentage applied to this transaction.",
  ),
  display_id: z.string().nullable().optional().describe("Id to be displayed."),
  document_received: z.boolean().nullable().optional().describe(
    "Whether the document has been received",
  ),
  due_date: z.string().date().nullable().optional().describe(
    "The due date is the date on which a payment is scheduled to be received - YYYY-MM-DD.",
  ),
  language: z.string().nullable().optional().describe(
    "language code according to ISO 639-1. For the United States - EN",
  ),
  ledger_account: LinkedLedgerAccount$zodSchema.nullable().optional(),
  line_items: z.array(BillLineItemInput$zodSchema).optional(),
  location_id: z.string().nullable().optional().describe(
    "The ID of the location",
  ),
  notes: z.string().nullable().optional(),
  paid_date: z.string().date().nullable().optional().describe(
    "The paid date is the date on which a payment was sent to the supplier - YYYY-MM-DD.",
  ),
  pass_through: z.array(PassThroughBody$zodSchema).optional().describe(
    "The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.",
  ),
  payment_allocations: z.array(LinkedPaymentAllocations$zodSchema.nullable())
    .nullable().optional().describe("A list of linked payment allocations."),
  payment_method: z.string().nullable().optional().describe(
    "Payment method used for the transaction, such as cash, credit card, bank transfer, or check",
  ),
  po_number: z.string().nullable().optional().describe(
    "A PO Number uniquely identifies a purchase order and is generally defined by the buyer. The buyer will match the PO number in the invoice to the Purchase Order.",
  ),
  reference: z.string().nullable().optional().describe(
    "Optional reference identifier for the transaction.",
  ),
  row_version: z.string().nullable().optional().describe(
    "A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.",
  ),
  source_document_url: z.string().nullable().optional().describe(
    "URL link to a source document - shown as 'Go to [appName]' in the downstream app. Currently only supported for Xero.",
  ),
  status: BillStatus$zodSchema.nullable().optional().describe("Invoice status"),
  sub_total: z.number().nullable().optional().describe(
    "Subtotal amount, normally before tax.",
  ),
  supplier: LinkedSupplierInput$zodSchema.nullable().optional().describe(
    "The supplier this entity is linked to.",
  ),
  tax_code: z.string().nullable().optional().describe(
    "Applicable tax id/code override if tax is not supplied on a line item basis.",
  ),
  tax_inclusive: z.boolean().nullable().optional().describe(
    "Amounts are including tax",
  ),
  tax_method: z.string().nullable().optional().describe(
    "Method of tax calculation",
  ),
  template_id: z.string().nullable().optional().describe(
    "Optional bill template",
  ),
  terms: z.string().nullable().optional().describe("Terms of payment."),
  terms_id: z.string().nullable().optional().describe(
    "The ID of the payment terms",
  ),
  total: z.number().nullable().optional().describe(
    "Total amount of bill, including tax.",
  ),
  total_tax: z.number().nullable().optional().describe(
    "Total tax amount applied to this transaction.",
  ),
  tracking_categories: z.array(LinkedTrackingCategory$zodSchema.nullable())
    .nullable().optional().describe("A list of linked tracking categories."),
});
