/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import {
  PassThroughBody,
  PassThroughBody$zodSchema,
} from "./passthroughbody.js";

/**
 * The type of the category.
 */
export const CategoryType = {
  Supplier: "supplier",
  Expense: "expense",
  Revenue: "revenue",
  Customer: "customer",
} as const;
/**
 * The type of the category.
 */
export type CategoryType = OpenEnum<typeof CategoryType>;

export const CategoryType$zodSchema = z.union([
  z.enum([
    "supplier",
    "expense",
    "revenue",
    "customer",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("The type of the category.");

/**
 * Based on the status some functionality is enabled or disabled.
 */
export const CategoryStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
/**
 * Based on the status some functionality is enabled or disabled.
 */
export type CategoryStatus = OpenEnum<typeof CategoryStatus>;

export const CategoryStatus$zodSchema = z.union([
  z.enum([
    "active",
    "inactive",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("Based on the status some functionality is enabled or disabled.");

export type Category = {
  id?: string | undefined;
  name?: string | undefined;
  display_id?: string | null | undefined;
  type?: CategoryType | undefined;
  status?: CategoryStatus | undefined;
  custom_mappings?: { [k: string]: any } | null | undefined;
  row_version?: string | null | undefined;
  updated_by?: string | null | undefined;
  created_by?: string | null | undefined;
  updated_at?: string | null | undefined;
  created_at?: string | null | undefined;
  pass_through?: Array<PassThroughBody> | undefined;
};

export const Category$zodSchema: z.ZodType<Category> = z.object({
  created_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date and time when the object was created.",
  ),
  created_by: z.string().nullable().optional().describe(
    "The user who created the object.",
  ),
  custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe(
    "When custom mappings are configured on the resource, the result is included here.",
  ),
  display_id: z.string().nullable().optional().describe(
    "Display ID of the category",
  ),
  id: z.string().optional().describe("A unique identifier for an object."),
  name: z.string().optional().describe("The name of the category."),
  pass_through: z.array(PassThroughBody$zodSchema).optional().describe(
    "The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.",
  ),
  row_version: z.string().nullable().optional().describe(
    "A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.",
  ),
  status: CategoryStatus$zodSchema.optional().describe(
    "Based on the status some functionality is enabled or disabled.",
  ),
  type: CategoryType$zodSchema.optional().describe("The type of the category."),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date and time when the object was last updated.",
  ),
  updated_by: z.string().nullable().optional().describe(
    "The user who last updated the object.",
  ),
});
