/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Collection = {
  id: string;
  parent_id?: string | null | undefined;
  type?: string | null | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  custom_mappings?: { [k: string]: any } | null | undefined;
  updated_at?: string | null | undefined;
  created_at?: string | null | undefined;
};

export const Collection$zodSchema: z.ZodType<Collection> = z.object({
  created_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date and time when the object was created.",
  ),
  custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe(
    "When custom mappings are configured on the resource, the result is included here.",
  ),
  description: z.string().nullable().optional().describe(
    "Description of the collection",
  ),
  id: z.string().describe("A unique identifier for an object."),
  name: z.string().nullable().optional().describe("Name of the collection"),
  parent_id: z.string().nullable().optional().describe(
    "The collections's parent ID",
  ),
  type: z.string().nullable().optional().describe("The collections's type"),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date and time when the object was last updated.",
  ),
});
