/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CollectionTag = {
  id: string | null;
  name?: string | null | undefined;
  custom_mappings?: { [k: string]: any } | null | undefined;
};

export const CollectionTag$zodSchema: z.ZodType<CollectionTag> = z.object({
  custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe(
    "When custom mappings are configured on the resource, the result is included here.",
  ),
  id: z.string().nullable().describe("A unique identifier for an object."),
  name: z.string().nullable().optional().describe("The name of the tag."),
});
