/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import { SortDirection, SortDirection$zodSchema } from "./sortdirection.js";

/**
 * The field on which to sort the Collections
 */
export const CollectionsSortBy = {
  Name: "name",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
} as const;
/**
 * The field on which to sort the Collections
 */
export type CollectionsSortBy = OpenEnum<typeof CollectionsSortBy>;

export const CollectionsSortBy$zodSchema = z.union([
  z.enum([
    "name",
    "created_at",
    "updated_at",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("The field on which to sort the Collections");

export type CollectionsSort = {
  by?: CollectionsSortBy | undefined;
  direction?: SortDirection | undefined;
};

export const CollectionsSort$zodSchema: z.ZodType<CollectionsSort> = z.object({
  by: CollectionsSortBy$zodSchema.optional().describe(
    "The field on which to sort the Collections",
  ),
  direction: SortDirection$zodSchema.default("asc").describe(
    "The direction in which to sort the results",
  ),
});
