/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestResponse,
  BadRequestResponse$zodSchema,
} from "./badrequestresponse.js";
import {
  ConnectorsFilter,
  ConnectorsFilter$zodSchema,
} from "./connectorsfilter.js";
import {
  GetConnectorsResponse,
  GetConnectorsResponse$zodSchema,
} from "./getconnectorsresponse.js";
import {
  PaymentRequiredResponse,
  PaymentRequiredResponse$zodSchema,
} from "./paymentrequiredresponse.js";
import {
  UnauthorizedResponse,
  UnauthorizedResponse$zodSchema,
} from "./unauthorizedresponse.js";
import {
  UnexpectedErrorResponse,
  UnexpectedErrorResponse$zodSchema,
} from "./unexpectederrorresponse.js";

export type ConnectorConnectorsAllGlobals = {
  xApideckAppId?: string | undefined;
};

export const ConnectorConnectorsAllGlobals$zodSchema: z.ZodType<
  ConnectorConnectorsAllGlobals
> = z.object({
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
});

export type ConnectorConnectorsAllRequest = {
  xApideckAppId?: string | undefined;
  cursor?: string | null | undefined;
  limit?: number | undefined;
  filter?: ConnectorsFilter | undefined;
};

export const ConnectorConnectorsAllRequest$zodSchema: z.ZodType<
  ConnectorConnectorsAllRequest
> = z.object({
  cursor: z.string().describe(
    "Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response.",
  ).nullable().optional(),
  filter: ConnectorsFilter$zodSchema.optional().describe("Apply filters"),
  limit: z.int().default(20).describe(
    "Number of results to return. Minimum 1, Maximum 200, Default 20",
  ),
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
});

export type ConnectorConnectorsAllResponseResult =
  | GetConnectorsResponse
  | BadRequestResponse
  | UnauthorizedResponse
  | PaymentRequiredResponse
  | UnexpectedErrorResponse;

export const ConnectorConnectorsAllResponseResult$zodSchema: z.ZodType<
  ConnectorConnectorsAllResponseResult
> = z.union([
  GetConnectorsResponse$zodSchema,
  BadRequestResponse$zodSchema,
  UnauthorizedResponse$zodSchema,
  PaymentRequiredResponse$zodSchema,
  UnexpectedErrorResponse$zodSchema,
]);

export type ConnectorConnectorsAllResponse = {
  Result:
    | GetConnectorsResponse
    | BadRequestResponse
    | UnauthorizedResponse
    | PaymentRequiredResponse
    | UnexpectedErrorResponse;
};

export const ConnectorConnectorsAllResponse$zodSchema: z.ZodType<
  ConnectorConnectorsAllResponse
> = z.object({
  Result: z.union([
    GetConnectorsResponse$zodSchema,
    BadRequestResponse$zodSchema,
    UnauthorizedResponse$zodSchema,
    PaymentRequiredResponse$zodSchema,
    UnexpectedErrorResponse$zodSchema,
  ]),
});
