/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";

/**
 * [Connection state flow](#section/Connection-state)
 */
export const ConnectionState = {
  Available: "available",
  Callable: "callable",
  Added: "added",
  Authorized: "authorized",
  Invalid: "invalid",
} as const;
/**
 * [Connection state flow](#section/Connection-state)
 */
export type ConnectionState = OpenEnum<typeof ConnectionState>;

export const ConnectionState$zodSchema = z.union([
  z.enum([
    "available",
    "callable",
    "added",
    "authorized",
    "invalid",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("[Connection state flow](#section/Connection-state)");
