/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthType, AuthType$zodSchema } from "./authtype.js";
import {
  ConnectionHealth,
  ConnectionHealth$zodSchema,
} from "./connectionhealth.js";
import {
  ConnectionState,
  ConnectionState$zodSchema,
} from "./connectionstate.js";

export type ConsumerConnection = {
  id?: string | undefined;
  name?: string | undefined;
  icon?: string | undefined;
  logo?: string | undefined;
  website?: string | undefined;
  tag_line?: string | undefined;
  service_id?: string | undefined;
  unified_api?: string | undefined;
  consumer_id?: string | undefined;
  auth_type?: AuthType | undefined;
  enabled?: boolean | undefined;
  settings?: { [k: string]: any } | null | undefined;
  metadata?: { [k: string]: any } | null | undefined;
  created_at?: string | undefined;
  updated_at?: string | null | undefined;
  state?: ConnectionState | undefined;
  health?: ConnectionHealth | undefined;
  credentials_expire_at?: string | null | undefined;
  last_refresh_failed_at?: string | null | undefined;
};

export const ConsumerConnection$zodSchema: z.ZodType<ConsumerConnection> = z
  .object({
    auth_type: AuthType$zodSchema.optional().describe(
      "Type of authorization used by the connector",
    ),
    consumer_id: z.string().optional(),
    created_at: z.string().optional(),
    credentials_expire_at: z.string().nullable().optional().describe(
      "ISO 8601 timestamp indicating when credentials will be cleared if token refresh continues to fail. Only present when connection health is pending_refresh and a retention window is active.",
    ),
    enabled: z.boolean().optional(),
    health: ConnectionHealth$zodSchema.optional().describe(
      "The operational health status of the connection",
    ),
    icon: z.string().optional(),
    id: z.string().optional(),
    last_refresh_failed_at: z.string().nullable().optional().describe(
      "ISO 8601 timestamp of the most recent token refresh failure. Only present when connection has experienced refresh failures.",
    ),
    logo: z.string().optional(),
    metadata: z.record(z.string(), z.any()).nullable().optional().describe(
      "Attach your own consumer specific metadata",
    ),
    name: z.string().optional(),
    service_id: z.string().optional(),
    settings: z.record(z.string(), z.any()).nullable().optional().describe(
      "Connection settings. Values will persist to `form_fields` with corresponding id",
    ),
    state: ConnectionState$zodSchema.optional().describe(
      "[Connection state flow](#section/Connection-state)",
    ),
    tag_line: z.string().optional(),
    unified_api: z.string().optional(),
    updated_at: z.string().nullable().optional(),
    website: z.string().optional(),
  });
