/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { UnifiedId, UnifiedId$zodSchema } from "./unifiedid.js";

/**
 * Bank Account created
 */
export type CreateBankAccountResponse = {
  status_code: number;
  status: string;
  service?: string | undefined;
  resource?: string | undefined;
  operation?: string | undefined;
  data: UnifiedId;
};

export const CreateBankAccountResponse$zodSchema: z.ZodType<
  CreateBankAccountResponse
> = z.object({
  data: UnifiedId$zodSchema.describe(
    "A object containing a unique identifier for the resource that was created, updated, or deleted.",
  ),
  operation: z.string().optional().describe("Operation performed"),
  resource: z.string().optional().describe("Unified API resource name"),
  service: z.string().optional().describe("Apideck ID of service provider"),
  status: z.string().describe("HTTP Response Status"),
  status_code: z.int().describe("HTTP Response Status Code"),
}).describe("Bank Account created");
