/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Status, Status$zodSchema } from "./status.js";
import { UnifiedApiId, UnifiedApiId$zodSchema } from "./unifiedapiid.js";
import {
  WebhookEventType,
  WebhookEventType$zodSchema,
} from "./webhookeventtype.js";

export type CreateWebhookRequest = {
  description?: string | null | undefined;
  unified_api: UnifiedApiId;
  status: Status;
  delivery_url: string;
  events: Array<WebhookEventType>;
};

export const CreateWebhookRequest$zodSchema: z.ZodType<CreateWebhookRequest> = z
  .object({
    delivery_url: z.string().describe(
      "The delivery url of the webhook endpoint.",
    ),
    description: z.string().nullable().optional().describe(
      "A description of the object.",
    ),
    events: z.array(WebhookEventType$zodSchema).describe(
      "The list of subscribed events for this webhook. [`*`] indicates that all events are enabled.",
    ),
    status: Status$zodSchema.describe("The status of the webhook."),
    unified_api: UnifiedApiId$zodSchema.describe("Name of Apideck Unified API"),
  });
