/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreditNotesFilter = { updated_since?: string | undefined };

export const CreditNotesFilter$zodSchema: z.ZodType<CreditNotesFilter> = z
  .object({
    updated_since: z.iso.datetime({ offset: true }).optional(),
  });
