/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestResponse,
  BadRequestResponse$zodSchema,
} from "./badrequestresponse.js";
import {
  DeleteOpportunityResponse,
  DeleteOpportunityResponse$zodSchema,
} from "./deleteopportunityresponse.js";
import {
  NotFoundResponse,
  NotFoundResponse$zodSchema,
} from "./notfoundresponse.js";
import {
  PaymentRequiredResponse,
  PaymentRequiredResponse$zodSchema,
} from "./paymentrequiredresponse.js";
import {
  UnauthorizedResponse,
  UnauthorizedResponse$zodSchema,
} from "./unauthorizedresponse.js";
import {
  UnexpectedErrorResponse,
  UnexpectedErrorResponse$zodSchema,
} from "./unexpectederrorresponse.js";
import {
  UnprocessableResponse,
  UnprocessableResponse$zodSchema,
} from "./unprocessableresponse.js";

export type CrmOpportunitiesDeleteGlobals = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
};

export const CrmOpportunitiesDeleteGlobals$zodSchema: z.ZodType<
  CrmOpportunitiesDeleteGlobals
> = z.object({
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
});

export type CrmOpportunitiesDeleteRequest = {
  id: string;
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
  xApideckServiceId?: string | undefined;
  raw?: boolean | undefined;
};

export const CrmOpportunitiesDeleteRequest$zodSchema: z.ZodType<
  CrmOpportunitiesDeleteRequest
> = z.object({
  id: z.string().describe("ID of the record you are acting upon."),
  raw: z.boolean().default(false).describe(
    "Include raw response. Mostly used for debugging purposes",
  ),
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
  xApideckServiceId: z.string().describe(
    "Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.",
  ).optional(),
});

export type CrmOpportunitiesDeleteResponse =
  | DeleteOpportunityResponse
  | BadRequestResponse
  | UnauthorizedResponse
  | PaymentRequiredResponse
  | NotFoundResponse
  | UnprocessableResponse
  | UnexpectedErrorResponse;

export const CrmOpportunitiesDeleteResponse$zodSchema: z.ZodType<
  CrmOpportunitiesDeleteResponse
> = z.union([
  DeleteOpportunityResponse$zodSchema,
  BadRequestResponse$zodSchema,
  UnauthorizedResponse$zodSchema,
  PaymentRequiredResponse$zodSchema,
  NotFoundResponse$zodSchema,
  UnprocessableResponse$zodSchema,
  UnexpectedErrorResponse$zodSchema,
]);
