/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CustomMappingInput = { value?: string | undefined };

export const CustomMappingInput$zodSchema: z.ZodType<CustomMappingInput> = z
  .object({
    value: z.string().optional().describe("Target Field Mapping value"),
  });
