/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Deduction = {
  name?: string | null | undefined;
  amount?: number | null | undefined;
};

export const Deduction$zodSchema: z.ZodType<Deduction> = z.object({
  amount: z.number().nullable().optional().describe("The amount deducted."),
  name: z.string().nullable().optional().describe("The name of the deduction."),
});
