/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { UnifiedId, UnifiedId$zodSchema } from "./unifiedid.js";

/**
 * Customers
 */
export type DeleteCustomerResponse = {
  status_code: number;
  status: string;
  service: string;
  resource: string;
  operation: string;
  data: UnifiedId;
  _raw?: { [k: string]: any } | null | undefined;
};

export const DeleteCustomerResponse$zodSchema: z.ZodType<
  DeleteCustomerResponse
> = z.object({
  _raw: z.record(z.string(), z.any()).nullable().optional().describe(
    "Raw response from the integration when raw=true query param is provided",
  ),
  data: UnifiedId$zodSchema.describe(
    "A object containing a unique identifier for the resource that was created, updated, or deleted.",
  ),
  operation: z.string().describe("Operation performed"),
  resource: z.string().describe("Unified API resource name"),
  service: z.string().describe("Apideck ID of service provider"),
  status: z.string().describe("HTTP Response Status"),
  status_code: z.int().describe("HTTP Response Status Code"),
}).describe("Customers");
