/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Address, Address$zodSchema } from "./address.js";

/**
 * The supplier this entity is linked to.
 *
 * @deprecated class: This field is deprecated and may be removed in a future version..
 */
export type DeprecatedLinkedSupplierInput = {
  display_name?: string | null | undefined;
  address?: Address | undefined;
};

export const DeprecatedLinkedSupplierInput$zodSchema: z.ZodType<
  DeprecatedLinkedSupplierInput
> = z.object({
  address: Address$zodSchema.optional(),
  display_name: z.string().nullable().optional().describe(
    "The display name of the supplier.",
  ),
}).describe("The supplier this entity is linked to.");
