/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";

/**
 * Email type
 */
export const EmailType = {
  Primary: "primary",
  Secondary: "secondary",
  Work: "work",
  Personal: "personal",
  Billing: "billing",
  Other: "other",
} as const;
/**
 * Email type
 */
export type EmailType = OpenEnum<typeof EmailType>;

export const EmailType$zodSchema = z.union([
  z.enum([
    "primary",
    "secondary",
    "work",
    "personal",
    "billing",
    "other",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("Email type");

export type Email = {
  id?: string | null | undefined;
  email: string | null;
  type?: EmailType | null | undefined;
};

export const Email$zodSchema: z.ZodType<Email> = z.object({
  email: z.string().nullable().describe("Email address"),
  id: z.string().nullable().optional().describe(
    "Unique identifier for the email address",
  ),
  type: EmailType$zodSchema.nullable().optional().describe("Email type"),
});
