/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import {
  LinkedLedgerAccount,
  LinkedLedgerAccount$zodSchema,
} from "./linkedledgeraccount.js";
import { LinkedTaxRate, LinkedTaxRate$zodSchema } from "./linkedtaxrate.js";
import {
  LinkedTaxRateInput,
  LinkedTaxRateInput$zodSchema,
} from "./linkedtaxrateinput.js";
import {
  PassThroughBody,
  PassThroughBody$zodSchema,
} from "./passthroughbody.js";

/**
 * The status of the expense category.
 */
export const ExpenseCategoryStatus = {
  Active: "active",
  Inactive: "inactive",
} as const;
/**
 * The status of the expense category.
 */
export type ExpenseCategoryStatus = OpenEnum<typeof ExpenseCategoryStatus>;

export const ExpenseCategoryStatus$zodSchema = z.union([
  z.enum([
    "active",
    "inactive",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("The status of the expense category.");

export type ExpenseCategory = {
  id?: string | undefined;
  display_id?: string | null | undefined;
  name: string;
  code?: string | null | undefined;
  description?: string | null | undefined;
  status?: ExpenseCategoryStatus | null | undefined;
  account?: LinkedLedgerAccount | null | undefined;
  offset_account?: LinkedLedgerAccount | null | undefined;
  tax_rate?: LinkedTaxRate | undefined;
  rate_required?: boolean | null | undefined;
  default_rate?: number | null | undefined;
  custom_mappings?: { [k: string]: any } | null | undefined;
  downstream_id?: string | null | undefined;
  row_version?: string | null | undefined;
  updated_by?: string | null | undefined;
  created_by?: string | null | undefined;
  updated_at?: string | null | undefined;
  created_at?: string | null | undefined;
  pass_through?: Array<PassThroughBody> | undefined;
};

export const ExpenseCategory$zodSchema: z.ZodType<ExpenseCategory> = z.object({
  account: LinkedLedgerAccount$zodSchema.nullable().optional(),
  code: z.string().nullable().optional().describe(
    "The code or external identifier of the expense category.",
  ),
  created_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date and time when the object was created.",
  ),
  created_by: z.string().nullable().optional().describe(
    "The user who created the object.",
  ),
  custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe(
    "When custom mappings are configured on the resource, the result is included here.",
  ),
  default_rate: z.number().nullable().optional().describe(
    "Default rate when rate_required is true (e.g. 0.67 for mileage).",
  ),
  description: z.string().nullable().optional().describe(
    "The description of the expense category.",
  ),
  display_id: z.string().nullable().optional().describe("Id to be displayed."),
  downstream_id: z.string().nullable().optional().describe(
    "The third-party API ID of original entity",
  ),
  id: z.string().optional().describe("A unique identifier for an object."),
  name: z.string().describe("The name of the expense category."),
  offset_account: LinkedLedgerAccount$zodSchema.nullable().optional(),
  pass_through: z.array(PassThroughBody$zodSchema).optional().describe(
    "The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.",
  ),
  rate_required: z.boolean().nullable().optional().describe(
    "Whether the expense category requires rate/quantity entry (e.g. mileage at $/mile).",
  ),
  row_version: z.string().nullable().optional().describe(
    "A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.",
  ),
  status: ExpenseCategoryStatus$zodSchema.nullable().optional().describe(
    "The status of the expense category.",
  ),
  tax_rate: LinkedTaxRate$zodSchema.optional(),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date and time when the object was last updated.",
  ),
  updated_by: z.string().nullable().optional().describe(
    "The user who last updated the object.",
  ),
});

export type ExpenseCategoryInput = {
  display_id?: string | null | undefined;
  name: string;
  code?: string | null | undefined;
  description?: string | null | undefined;
  status?: ExpenseCategoryStatus | null | undefined;
  account?: LinkedLedgerAccount | null | undefined;
  offset_account?: LinkedLedgerAccount | null | undefined;
  tax_rate?: LinkedTaxRateInput | undefined;
  rate_required?: boolean | null | undefined;
  default_rate?: number | null | undefined;
  row_version?: string | null | undefined;
  pass_through?: Array<PassThroughBody> | undefined;
};

export const ExpenseCategoryInput$zodSchema: z.ZodType<ExpenseCategoryInput> = z
  .object({
    account: LinkedLedgerAccount$zodSchema.nullable().optional(),
    code: z.string().nullable().optional().describe(
      "The code or external identifier of the expense category.",
    ),
    default_rate: z.number().nullable().optional().describe(
      "Default rate when rate_required is true (e.g. 0.67 for mileage).",
    ),
    description: z.string().nullable().optional().describe(
      "The description of the expense category.",
    ),
    display_id: z.string().nullable().optional().describe(
      "Id to be displayed.",
    ),
    name: z.string().describe("The name of the expense category."),
    offset_account: LinkedLedgerAccount$zodSchema.nullable().optional(),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe(
      "The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.",
    ),
    rate_required: z.boolean().nullable().optional().describe(
      "Whether the expense category requires rate/quantity entry (e.g. mileage at $/mile).",
    ),
    row_version: z.string().nullable().optional().describe(
      "A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.",
    ),
    status: ExpenseCategoryStatus$zodSchema.nullable().optional().describe(
      "The status of the expense category.",
    ),
    tax_rate: LinkedTaxRateInput$zodSchema.optional(),
  });
