/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestResponse,
  BadRequestResponse$zodSchema,
} from "./badrequestresponse.js";
import {
  CreateUploadSessionRequest,
  CreateUploadSessionRequest$zodSchema,
} from "./createuploadsessionrequest.js";
import {
  CreateUploadSessionResponse,
  CreateUploadSessionResponse$zodSchema,
} from "./createuploadsessionresponse.js";
import {
  NotFoundResponse,
  NotFoundResponse$zodSchema,
} from "./notfoundresponse.js";
import {
  PaymentRequiredResponse,
  PaymentRequiredResponse$zodSchema,
} from "./paymentrequiredresponse.js";
import {
  UnauthorizedResponse,
  UnauthorizedResponse$zodSchema,
} from "./unauthorizedresponse.js";
import {
  UnexpectedErrorResponse,
  UnexpectedErrorResponse$zodSchema,
} from "./unexpectederrorresponse.js";
import {
  UnprocessableResponse,
  UnprocessableResponse$zodSchema,
} from "./unprocessableresponse.js";

export const FileStorageUploadSessionsAddOpServerList = [
  "https://upload.apideck.com",
] as const;

export type FileStorageUploadSessionsAddGlobals = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
};

export const FileStorageUploadSessionsAddGlobals$zodSchema: z.ZodType<
  FileStorageUploadSessionsAddGlobals
> = z.object({
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
});

export type FileStorageUploadSessionsAddRequest = {
  raw?: boolean | undefined;
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
  xApideckServiceId?: string | undefined;
  body: CreateUploadSessionRequest;
};

export const FileStorageUploadSessionsAddRequest$zodSchema: z.ZodType<
  FileStorageUploadSessionsAddRequest
> = z.object({
  body: CreateUploadSessionRequest$zodSchema,
  raw: z.boolean().default(false).describe(
    "Include raw response. Mostly used for debugging purposes",
  ),
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
  xApideckServiceId: z.string().describe(
    "Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.",
  ).optional(),
});

export type FileStorageUploadSessionsAddResponse =
  | CreateUploadSessionResponse
  | BadRequestResponse
  | UnauthorizedResponse
  | PaymentRequiredResponse
  | NotFoundResponse
  | UnprocessableResponse
  | UnexpectedErrorResponse;

export const FileStorageUploadSessionsAddResponse$zodSchema: z.ZodType<
  FileStorageUploadSessionsAddResponse
> = z.union([
  CreateUploadSessionResponse$zodSchema,
  BadRequestResponse$zodSchema,
  UnauthorizedResponse$zodSchema,
  PaymentRequiredResponse$zodSchema,
  NotFoundResponse$zodSchema,
  UnprocessableResponse$zodSchema,
  UnexpectedErrorResponse$zodSchema,
]);
