/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import {
  SimpleFormFieldOption,
  SimpleFormFieldOption$zodSchema,
} from "./simpleformfieldoption.js";

export const FormFieldOptionGroupOptionType = {
  Group: "group",
} as const;
export type FormFieldOptionGroupOptionType = OpenEnum<
  typeof FormFieldOptionGroupOptionType
>;

export const FormFieldOptionGroupOptionType$zodSchema = z.union([
  z.enum([
    "group",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]);

export type FormFieldOptionGroup = {
  id?: string | undefined;
  label: string;
  options: Array<SimpleFormFieldOption>;
  option_type: FormFieldOptionGroupOptionType;
};

export const FormFieldOptionGroup$zodSchema: z.ZodType<FormFieldOptionGroup> = z
  .object({
    id: z.string().optional(),
    label: z.string(),
    option_type: FormFieldOptionGroupOptionType$zodSchema,
    options: z.array(SimpleFormFieldOption$zodSchema),
  });
