/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AccountingLocation,
  AccountingLocation$zodSchema,
} from "./accountinglocation.js";
import { Links, Links$zodSchema } from "./links.js";
import { Meta, Meta$zodSchema } from "./meta.js";

/**
 * Locations
 */
export type GetAccountingLocationsResponse = {
  status_code: number;
  status: string;
  service: string;
  resource: string;
  operation: string;
  data: Array<AccountingLocation>;
  meta?: Meta | undefined;
  links?: Links | undefined;
  _raw?: { [k: string]: any } | null | undefined;
};

export const GetAccountingLocationsResponse$zodSchema: z.ZodType<
  GetAccountingLocationsResponse
> = z.object({
  _raw: z.record(z.string(), z.any()).nullable().optional().describe(
    "Raw response from the integration when raw=true query param is provided",
  ),
  data: z.array(AccountingLocation$zodSchema),
  links: Links$zodSchema.optional().describe(
    "Links to navigate to previous or next pages through the API",
  ),
  meta: Meta$zodSchema.optional().describe("Response metadata"),
  operation: z.string().describe("Operation performed"),
  resource: z.string().describe("Unified API resource name"),
  service: z.string().describe("Apideck ID of service provider"),
  status: z.string().describe("HTTP Response Status"),
  status_code: z.int().describe("HTTP Response Status Code"),
}).describe("Locations");
