/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AccountingBankAccount,
  AccountingBankAccount$zodSchema,
} from "./accountingbankaccount.js";
import { Links, Links$zodSchema } from "./links.js";
import { Meta, Meta$zodSchema } from "./meta.js";

/**
 * Bank Accounts
 */
export type GetBankAccountsResponse = {
  status_code: number;
  status: string;
  service?: string | undefined;
  resource?: string | undefined;
  operation?: string | undefined;
  data: Array<AccountingBankAccount>;
  meta?: Meta | undefined;
  links?: Links | undefined;
};

export const GetBankAccountsResponse$zodSchema: z.ZodType<
  GetBankAccountsResponse
> = z.object({
  data: z.array(AccountingBankAccount$zodSchema),
  links: Links$zodSchema.optional().describe(
    "Links to navigate to previous or next pages through the API",
  ),
  meta: Meta$zodSchema.optional().describe("Response metadata"),
  operation: z.string().optional().describe("Operation performed"),
  resource: z.string().optional().describe("Unified API resource name"),
  service: z.string().optional().describe("Apideck ID of service provider"),
  status: z.string().describe("HTTP Response Status"),
  status_code: z.int().describe("HTTP Response Status Code"),
}).describe("Bank Accounts");
