/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Lead, Lead$zodSchema } from "./lead.js";

/**
 * Lead
 */
export type GetLeadResponse = {
  status_code: number;
  status: string;
  service: string;
  resource: string;
  operation: string;
  data: Lead;
  _raw?: { [k: string]: any } | null | undefined;
};

export const GetLeadResponse$zodSchema: z.ZodType<GetLeadResponse> = z.object({
  _raw: z.record(z.string(), z.any()).nullable().optional().describe(
    "Raw response from the integration when raw=true query param is provided",
  ),
  data: Lead$zodSchema,
  operation: z.string().describe("Operation performed"),
  resource: z.string().describe("Unified API resource name"),
  service: z.string().describe("Apideck ID of service provider"),
  status: z.string().describe("HTTP Response Status"),
  status_code: z.int().describe("HTTP Response Status Code"),
}).describe("Lead");
