/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Quote, Quote$zodSchema } from "./quote.js";

/**
 * Quotes
 */
export type GetQuoteResponse = {
  status_code: number;
  status: string;
  service: string;
  resource: string;
  operation: string;
  data: Quote;
};

export const GetQuoteResponse$zodSchema: z.ZodType<GetQuoteResponse> = z.object(
  {
    data: Quote$zodSchema,
    operation: z.string().describe("Operation performed"),
    resource: z.string().describe("Unified API resource name"),
    service: z.string().describe("Apideck ID of service provider"),
    status: z.string().describe("HTTP Response Status"),
    status_code: z.int().describe("HTTP Response Status Code"),
  },
).describe("Quotes");
