/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestResponse,
  BadRequestResponse$zodSchema,
} from "./badrequestresponse.js";
import { HrisCompanyInput, HrisCompanyInput$zodSchema } from "./hriscompany.js";
import {
  NotFoundResponse,
  NotFoundResponse$zodSchema,
} from "./notfoundresponse.js";
import {
  PaymentRequiredResponse,
  PaymentRequiredResponse$zodSchema,
} from "./paymentrequiredresponse.js";
import {
  UnauthorizedResponse,
  UnauthorizedResponse$zodSchema,
} from "./unauthorizedresponse.js";
import {
  UnexpectedErrorResponse,
  UnexpectedErrorResponse$zodSchema,
} from "./unexpectederrorresponse.js";
import {
  UnprocessableResponse,
  UnprocessableResponse$zodSchema,
} from "./unprocessableresponse.js";
import {
  UpdateHrisCompanyResponse,
  UpdateHrisCompanyResponse$zodSchema,
} from "./updatehriscompanyresponse.js";

export type HrisCompaniesUpdateGlobals = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
};

export const HrisCompaniesUpdateGlobals$zodSchema: z.ZodType<
  HrisCompaniesUpdateGlobals
> = z.object({
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
});

export type HrisCompaniesUpdateRequest = {
  id: string;
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
  xApideckServiceId?: string | undefined;
  raw?: boolean | undefined;
  body: HrisCompanyInput;
};

export const HrisCompaniesUpdateRequest$zodSchema: z.ZodType<
  HrisCompaniesUpdateRequest
> = z.object({
  body: HrisCompanyInput$zodSchema,
  id: z.string().describe("ID of the record you are acting upon."),
  raw: z.boolean().default(false).describe(
    "Include raw response. Mostly used for debugging purposes",
  ),
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
  xApideckServiceId: z.string().describe(
    "Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.",
  ).optional(),
});

export type HrisCompaniesUpdateResponse =
  | UpdateHrisCompanyResponse
  | BadRequestResponse
  | UnauthorizedResponse
  | PaymentRequiredResponse
  | NotFoundResponse
  | UnprocessableResponse
  | UnexpectedErrorResponse;

export const HrisCompaniesUpdateResponse$zodSchema: z.ZodType<
  HrisCompaniesUpdateResponse
> = z.union([
  UpdateHrisCompanyResponse$zodSchema,
  BadRequestResponse$zodSchema,
  UnauthorizedResponse$zodSchema,
  PaymentRequiredResponse$zodSchema,
  NotFoundResponse$zodSchema,
  UnprocessableResponse$zodSchema,
  UnexpectedErrorResponse$zodSchema,
]);
