/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";

/**
 * The type of invoice item, indicating whether it is an inventory item, a service, or another type.
 */
export const InvoiceItemsFilterInvoiceItemType = {
  Inventory: "inventory",
  Service: "service",
  Other: "other",
} as const;
/**
 * The type of invoice item, indicating whether it is an inventory item, a service, or another type.
 */
export type InvoiceItemsFilterInvoiceItemType = OpenEnum<
  typeof InvoiceItemsFilterInvoiceItemType
>;

export const InvoiceItemsFilterInvoiceItemType$zodSchema = z.union([
  z.enum([
    "inventory",
    "service",
    "other",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe(
  "The type of invoice item, indicating whether it is an inventory item, a service, or another type.",
);

/**
 * The kind of transaction, indicating whether it is a sales transaction or a purchase transaction.
 */
export const InvoiceItemsFilterTransactionType = {
  Sale: "sale",
  Purchase: "purchase",
} as const;
/**
 * The kind of transaction, indicating whether it is a sales transaction or a purchase transaction.
 */
export type InvoiceItemsFilterTransactionType = OpenEnum<
  typeof InvoiceItemsFilterTransactionType
>;

export const InvoiceItemsFilterTransactionType$zodSchema = z.union([
  z.enum([
    "sale",
    "purchase",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe(
  "The kind of transaction, indicating whether it is a sales transaction or a purchase transaction.",
);

export type InvoiceItemsFilter = {
  updated_since?: string | undefined;
  name?: string | undefined;
  type?: InvoiceItemsFilterInvoiceItemType | null | undefined;
  transaction_type?: InvoiceItemsFilterTransactionType | null | undefined;
};

export const InvoiceItemsFilter$zodSchema: z.ZodType<InvoiceItemsFilter> = z
  .object({
    name: z.string().optional().describe("Name of Invoice Items to search for"),
    transaction_type: InvoiceItemsFilterTransactionType$zodSchema.nullable()
      .optional().describe(
        "The kind of transaction, indicating whether it is a sales transaction or a purchase transaction.",
      ),
    type: InvoiceItemsFilterInvoiceItemType$zodSchema.nullable().optional()
      .describe(
        "The type of invoice item, indicating whether it is an inventory item, a service, or another type.",
      ),
    updated_since: z.iso.datetime({ offset: true }).optional(),
  });
