/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestResponse,
  BadRequestResponse$zodSchema,
} from "./badrequestresponse.js";
import {
  CollectionTicketCommentInput,
  CollectionTicketCommentInput$zodSchema,
} from "./collectionticketcommentinput.js";
import {
  NotFoundResponse,
  NotFoundResponse$zodSchema,
} from "./notfoundresponse.js";
import {
  PaymentRequiredResponse,
  PaymentRequiredResponse$zodSchema,
} from "./paymentrequiredresponse.js";
import {
  UnauthorizedResponse,
  UnauthorizedResponse$zodSchema,
} from "./unauthorizedresponse.js";
import {
  UnexpectedErrorResponse,
  UnexpectedErrorResponse$zodSchema,
} from "./unexpectederrorresponse.js";
import {
  UnprocessableResponse,
  UnprocessableResponse$zodSchema,
} from "./unprocessableresponse.js";
import {
  UpdateCommentResponse,
  UpdateCommentResponse$zodSchema,
} from "./updatecommentresponse.js";

export type IssueTrackingCollectionTicketCommentsUpdateGlobals = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
};

export const IssueTrackingCollectionTicketCommentsUpdateGlobals$zodSchema:
  z.ZodType<IssueTrackingCollectionTicketCommentsUpdateGlobals> = z.object({
    xApideckAppId: z.string().describe("The ID of your Unify application")
      .optional(),
    xApideckConsumerId: z.string().describe(
      "ID of the consumer which you want to get or push data from",
    ).optional(),
  });

export type IssueTrackingCollectionTicketCommentsUpdateRequest = {
  id: string;
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
  xApideckServiceId?: string | undefined;
  raw?: boolean | undefined;
  collection_id: string;
  ticket_id: string;
  body: CollectionTicketCommentInput;
};

export const IssueTrackingCollectionTicketCommentsUpdateRequest$zodSchema:
  z.ZodType<IssueTrackingCollectionTicketCommentsUpdateRequest> = z.object({
    body: CollectionTicketCommentInput$zodSchema,
    collection_id: z.string().describe("The collection ID"),
    id: z.string().describe("ID of the record you are acting upon."),
    raw: z.boolean().default(false).describe(
      "Include raw response. Mostly used for debugging purposes",
    ),
    ticket_id: z.string().describe("ID of the ticket you are acting upon."),
    xApideckAppId: z.string().describe("The ID of your Unify application")
      .optional(),
    xApideckConsumerId: z.string().describe(
      "ID of the consumer which you want to get or push data from",
    ).optional(),
    xApideckServiceId: z.string().describe(
      "Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.",
    ).optional(),
  });

export type IssueTrackingCollectionTicketCommentsUpdateResponse =
  | UpdateCommentResponse
  | BadRequestResponse
  | UnauthorizedResponse
  | PaymentRequiredResponse
  | NotFoundResponse
  | UnprocessableResponse
  | UnexpectedErrorResponse;

export const IssueTrackingCollectionTicketCommentsUpdateResponse$zodSchema:
  z.ZodType<IssueTrackingCollectionTicketCommentsUpdateResponse> = z.union([
    UpdateCommentResponse$zodSchema,
    BadRequestResponse$zodSchema,
    UnauthorizedResponse$zodSchema,
    PaymentRequiredResponse$zodSchema,
    NotFoundResponse$zodSchema,
    UnprocessableResponse$zodSchema,
    UnexpectedErrorResponse$zodSchema,
  ]);
