/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IssuesFilter = {
  status?: Array<string> | undefined;
  since?: string | undefined;
  assignee_id?: string | undefined;
};

export const IssuesFilter$zodSchema: z.ZodType<IssuesFilter> = z.object({
  assignee_id: z.string().optional().describe(
    "Only return tickets assigned to a specific user",
  ),
  since: z.iso.datetime({ offset: true }).optional().describe(
    "Only return tickets since a specific date",
  ),
  status: z.array(z.string()).optional().describe(
    "Filter by ticket status, can be `open`, `closed` or `all`. Will passthrough if none of the above match",
  ),
});
