/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import { SortDirection, SortDirection$zodSchema } from "./sortdirection.js";

/**
 * The field on which to sort the Ledger Accounts
 */
export const LedgerAccountsSortBy = {
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
} as const;
/**
 * The field on which to sort the Ledger Accounts
 */
export type LedgerAccountsSortBy = OpenEnum<typeof LedgerAccountsSortBy>;

export const LedgerAccountsSortBy$zodSchema = z.union([
  z.enum([
    "created_at",
    "updated_at",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("The field on which to sort the Ledger Accounts");

export type LedgerAccountsSort = {
  by?: LedgerAccountsSortBy | undefined;
  direction?: SortDirection | undefined;
};

export const LedgerAccountsSort$zodSchema: z.ZodType<LedgerAccountsSort> = z
  .object({
    by: LedgerAccountsSortBy$zodSchema.optional().describe(
      "The field on which to sort the Ledger Accounts",
    ),
    direction: SortDirection$zodSchema.default("asc").describe(
      "The direction in which to sort the results",
    ),
  });
