/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type LinkedWorktag = {
  id?: string | undefined;
  value?: string | null | undefined;
};

export const LinkedWorktag$zodSchema: z.ZodType<LinkedWorktag> = z.object({
  id: z.string().optional().describe("The unique identifier for the worktag."),
  value: z.string().nullable().optional().describe("The value of the worktag."),
});
