/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ResourceStatus, ResourceStatus$zodSchema } from "./resourcestatus.js";

export type LinkedConnectorResource = {
  id?: string | undefined;
  name?: string | undefined;
  status?: ResourceStatus | undefined;
  downstream_id?: string | undefined;
  downstream_name?: string | undefined;
};

export const LinkedConnectorResource$zodSchema: z.ZodType<
  LinkedConnectorResource
> = z.object({
  downstream_id: z.string().optional().describe(
    "ID of the resource in the Connector's API (downstream)",
  ),
  downstream_name: z.string().optional().describe(
    "Name of the resource in the Connector's API (downstream)",
  ),
  id: z.string().optional().describe(
    "ID of the resource, typically a lowercased version of name.",
  ),
  name: z.string().optional().describe("Name of the resource (plural)"),
  status: ResourceStatus$zodSchema.optional().describe(
    "Status of the resource. Resources with status live or beta are callable.",
  ),
});
