/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";

/**
 * The type of account being referenced. Use `ledger_account` for GL accounts from the chart of accounts, or `bank_account` for bank account entities. When not specified, the connector will use its default behavior.
 */
export const LinkedFinancialAccountAccountType = {
  LedgerAccount: "ledger_account",
  BankAccount: "bank_account",
  Employee: "employee",
} as const;
/**
 * The type of account being referenced. Use `ledger_account` for GL accounts from the chart of accounts, or `bank_account` for bank account entities. When not specified, the connector will use its default behavior.
 */
export type LinkedFinancialAccountAccountType = OpenEnum<
  typeof LinkedFinancialAccountAccountType
>;

export const LinkedFinancialAccountAccountType$zodSchema = z.union([
  z.enum([
    "ledger_account",
    "bank_account",
    "employee",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe(
  "The type of account being referenced. Use `ledger_account` for GL accounts from the chart of accounts, or `bank_account` for bank account entities. When not specified, the connector will use its default behavior.",
);

/**
 * A flexible account reference that can represent a ledger account (GL account), a bank account, or an employee payable account, depending on the connector's requirements.
 */
export type LinkedFinancialAccount = {
  id?: string | undefined;
  type?: LinkedFinancialAccountAccountType | null | undefined;
  code?: string | undefined;
  display_id?: string | null | undefined;
  account_number?: string | null | undefined;
  name?: string | undefined;
  downstream_id?: string | null | undefined;
};

export const LinkedFinancialAccount$zodSchema: z.ZodType<
  LinkedFinancialAccount
> = z.object({
  account_number: z.string().nullable().optional().describe(
    "The bank account number",
  ),
  code: z.string().optional().describe("The account code of the account"),
  display_id: z.string().nullable().optional().describe("Id to be displayed."),
  downstream_id: z.string().nullable().optional().describe(
    "The third-party API ID of original entity",
  ),
  id: z.string().optional().describe(
    "The unique identifier for the account. This can be a ledger account ID or bank account ID depending on the `type` field.",
  ),
  name: z.string().optional().describe("The name of the account."),
  type: LinkedFinancialAccountAccountType$zodSchema.nullable().optional()
    .describe(
      "The type of account being referenced. Use `ledger_account` for GL accounts from the chart of accounts, or `bank_account` for bank account entities. When not specified, the connector will use its default behavior.",
    ),
}).describe(
  "A flexible account reference that can represent a ledger account (GL account), a bank account, or an employee payable account, depending on the connector's requirements.",
);

/**
 * A flexible account reference that can represent a ledger account (GL account), a bank account, or an employee payable account, depending on the connector's requirements.
 */
export type LinkedFinancialAccountInput = {
  id?: string | undefined;
  type?: LinkedFinancialAccountAccountType | null | undefined;
  code?: string | undefined;
  display_id?: string | null | undefined;
  account_number?: string | null | undefined;
};

export const LinkedFinancialAccountInput$zodSchema: z.ZodType<
  LinkedFinancialAccountInput
> = z.object({
  account_number: z.string().nullable().optional().describe(
    "The bank account number",
  ),
  code: z.string().optional().describe("The account code of the account"),
  display_id: z.string().nullable().optional().describe("Id to be displayed."),
  id: z.string().optional().describe(
    "The unique identifier for the account. This can be a ledger account ID or bank account ID depending on the `type` field.",
  ),
  type: LinkedFinancialAccountAccountType$zodSchema.nullable().optional()
    .describe(
      "The type of account being referenced. Use `ledger_account` for GL accounts from the chart of accounts, or `bank_account` for bank account entities. When not specified, the connector will use its default behavior.",
    ),
}).describe(
  "A flexible account reference that can represent a ledger account (GL account), a bank account, or an employee payable account, depending on the connector's requirements.",
);
