/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EcommerceOrderStatus,
  EcommerceOrderStatus$zodSchema,
} from "./ecommerceorderstatus.js";

/**
 * The order this entity is linked to.
 */
export type LinkedEcommerceOrder = {
  id?: string | undefined;
  total?: string | null | undefined;
  status?: EcommerceOrderStatus | null | undefined;
};

export const LinkedEcommerceOrder$zodSchema: z.ZodType<LinkedEcommerceOrder> = z
  .object({
    id: z.string().optional().describe("A unique identifier for an object."),
    status: EcommerceOrderStatus$zodSchema.nullable().optional().describe(
      "Current status of the order.",
    ),
    total: z.string().nullable().optional().describe(
      "The total amount of the order.",
    ),
  }).describe("The order this entity is linked to.");
