/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type LinkedSubsidiary = {
  id?: string | undefined;
  display_id?: string | null | undefined;
  name?: string | null | undefined;
};

export const LinkedSubsidiary$zodSchema: z.ZodType<LinkedSubsidiary> = z.object(
  {
    display_id: z.string().nullable().optional().describe(
      "Id to be displayed.",
    ),
    id: z.string().optional().describe("A unique identifier for an object."),
    name: z.string().nullable().optional().describe(
      "The name of the resource.",
    ),
  },
);
