/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BalanceByPeriod,
  BalanceByPeriod$zodSchema,
} from "./balancebyperiod.js";
import { Currency, Currency$zodSchema } from "./currency.js";

export type OutstandingBalanceByCurrency = {
  currency?: Currency | null | undefined;
  total_amount?: number | undefined;
  balances_by_period?: Array<BalanceByPeriod> | undefined;
};

export const OutstandingBalanceByCurrency$zodSchema: z.ZodType<
  OutstandingBalanceByCurrency
> = z.object({
  balances_by_period: z.array(BalanceByPeriod$zodSchema).optional(),
  currency: Currency$zodSchema.nullable().optional().describe(
    "Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).",
  ),
  total_amount: z.number().optional().describe(
    "Total amount of the outstanding balance.",
  ),
});
