/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  OutstandingBalanceByCurrency,
  OutstandingBalanceByCurrency$zodSchema,
} from "./outstandingbalancebycurrency.js";

export type OutstandingBalanceByCustomer = {
  customer_id?: string | undefined;
  customer_name?: string | undefined;
  outstanding_balances_by_currency?:
    | Array<OutstandingBalanceByCurrency>
    | undefined;
};

export const OutstandingBalanceByCustomer$zodSchema: z.ZodType<
  OutstandingBalanceByCustomer
> = z.object({
  customer_id: z.string().optional().describe(
    "Unique identifier for the customer.",
  ),
  customer_name: z.string().optional().describe("Full name of the customer."),
  outstanding_balances_by_currency: z.array(
    OutstandingBalanceByCurrency$zodSchema,
  ).optional(),
});
