/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ExtendPath = { path: string; value?: any | undefined };

export const ExtendPath$zodSchema: z.ZodType<ExtendPath> = z.object({
  path: z.string().describe(
    "JSONPath string specifying where to apply the value.",
  ),
  value: z.any().optional().describe(
    "The value to set at the specified path, can be any type.",
  ),
});

export type PassThroughBody = {
  service_id: string;
  operation_id?: string | undefined;
  extend_object?: { [k: string]: any } | undefined;
  extend_paths?: Array<ExtendPath> | undefined;
};

export const PassThroughBody$zodSchema: z.ZodType<PassThroughBody> = z.object({
  extend_object: z.record(z.string(), z.any()).optional().describe(
    "Simple object allowing any properties for direct extension.",
  ),
  extend_paths: z.array(z.lazy(() => ExtendPath$zodSchema)).optional().describe(
    "Array of objects for structured data modifications via paths.",
  ),
  operation_id: z.string().optional().describe(
    "Optional identifier for a workflow operation to which this pass_through should be applied. This is useful for Unify calls that are making more than one downstream request.",
  ),
  service_id: z.string().describe(
    "Identifier for the service to which this pass_through should be applied.",
  ),
});
