/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";

/**
 * Frequency of employee compensation.
 */
export const PaymentFrequency = {
  Weekly: "weekly",
  Biweekly: "biweekly",
  Monthly: "monthly",
  ProRata: "pro-rata",
  Other: "other",
} as const;
/**
 * Frequency of employee compensation.
 */
export type PaymentFrequency = OpenEnum<typeof PaymentFrequency>;

export const PaymentFrequency$zodSchema = z.union([
  z.enum([
    "weekly",
    "biweekly",
    "monthly",
    "pro-rata",
    "other",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("Frequency of employee compensation.");
