/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";

export const PaymentsFilterType = {
  AccountsReceivable: "accounts_receivable",
  AccountsPayable: "accounts_payable",
  AccountsReceivableCredit: "accounts_receivable_credit",
  AccountsPayableCredit: "accounts_payable_credit",
  AccountsReceivableOverpayment: "accounts_receivable_overpayment",
  AccountsPayableOverpayment: "accounts_payable_overpayment",
  AccountsReceivablePrepayment: "accounts_receivable_prepayment",
  AccountsPayablePrepayment: "accounts_payable_prepayment",
} as const;
export type PaymentsFilterType = OpenEnum<typeof PaymentsFilterType>;

export const PaymentsFilterType$zodSchema = z.union([
  z.enum([
    "accounts_receivable",
    "accounts_payable",
    "accounts_receivable_credit",
    "accounts_payable_credit",
    "accounts_receivable_overpayment",
    "accounts_payable_overpayment",
    "accounts_receivable_prepayment",
    "accounts_payable_prepayment",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]);

export type PaymentsFilter = {
  updated_since?: string | undefined;
  invoice_id?: string | undefined;
  supplier_id?: string | undefined;
  customer_id?: string | undefined;
  type?: PaymentsFilterType | undefined;
};

export const PaymentsFilter$zodSchema: z.ZodType<PaymentsFilter> = z.object({
  customer_id: z.string().optional().describe("Filter by customer id"),
  invoice_id: z.string().optional(),
  supplier_id: z.string().optional(),
  type: PaymentsFilterType$zodSchema.optional(),
  updated_since: z.iso.datetime({ offset: true }).optional(),
});
