/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PayrollsFilter = {
  start_date?: string | undefined;
  end_date?: string | undefined;
};

export const PayrollsFilter$zodSchema: z.ZodType<PayrollsFilter> = z.object({
  end_date: z.string().optional().describe(
    "Return payrolls whose pay period is before the end date",
  ),
  start_date: z.string().optional().describe(
    "Return payrolls whose pay period is after the start date",
  ),
});
