/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Compensation, Compensation$zodSchema } from "./compensation.js";
import { PayrollTotals, PayrollTotals$zodSchema } from "./payrolltotals.js";

export type Payroll = {
  id: string | null;
  company_id?: string | null | undefined;
  processed: boolean | null;
  processed_date?: string | null | undefined;
  check_date: string | null;
  start_date: string | null;
  end_date: string | null;
  totals?: PayrollTotals | undefined;
  compensations?: Array<Compensation> | undefined;
  custom_mappings?: { [k: string]: any } | null | undefined;
};

export const Payroll$zodSchema: z.ZodType<Payroll> = z.object({
  check_date: z.string().nullable().describe(
    "The date on which employees will be paid for the payroll.",
  ),
  company_id: z.string().nullable().optional().describe(
    "The unique identifier of the company.",
  ),
  compensations: z.array(Compensation$zodSchema).optional().describe(
    "An array of compensations for the payroll.",
  ),
  custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe(
    "When custom mappings are configured on the resource, the result is included here.",
  ),
  end_date: z.string().nullable().describe(
    "The end date, inclusive, of the pay period.",
  ),
  id: z.string().nullable().describe("A unique identifier for an object."),
  processed: z.boolean().nullable().describe(
    "Whether or not the payroll has been successfully processed. Note that processed payrolls cannot be updated.",
  ),
  processed_date: z.string().nullable().optional().describe(
    "The date the payroll was processed.",
  ),
  start_date: z.string().nullable().describe(
    "The start date, inclusive, of the pay period.",
  ),
  totals: PayrollTotals$zodSchema.optional().describe(
    "The overview of the payroll totals.",
  ),
});
