/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Gender, Gender$zodSchema } from "./gender.js";

export type Person = {
  id?: string | null | undefined;
  first_name?: string | null | undefined;
  last_name?: string | null | undefined;
  middle_name?: string | null | undefined;
  gender?: Gender | null | undefined;
  initials?: string | null | undefined;
  birthday?: string | null | undefined;
  deceased_on?: string | null | undefined;
  custom_mappings?: { [k: string]: any } | null | undefined;
};

export const Person$zodSchema: z.ZodType<Person> = z.object({
  birthday: z.string().date().nullable().optional().describe("Date of birth"),
  custom_mappings: z.record(z.string(), z.any()).nullable().optional().describe(
    "When custom mappings are configured on the resource, the result is included here.",
  ),
  deceased_on: z.string().date().nullable().optional().describe(
    "Date of death",
  ),
  first_name: z.string().nullable().optional().describe(
    "The first name of the person.",
  ),
  gender: Gender$zodSchema.nullable().optional().describe(
    "The gender represents the gender identity of a person.",
  ),
  id: z.string().nullable().optional().describe(
    "A unique identifier for an object.",
  ),
  initials: z.string().nullable().optional().describe("Initials of the person"),
  last_name: z.string().nullable().optional().describe(
    "The last name of the person.",
  ),
  middle_name: z.string().nullable().optional().describe(
    "Middle name of the person.",
  ),
});
