/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";

/**
 * The accounting method used for the report: cash or accrual.
 */
export const ProfitAndLossFilterAccountingMethod = {
  Cash: "cash",
  Accrual: "accrual",
} as const;
/**
 * The accounting method used for the report: cash or accrual.
 */
export type ProfitAndLossFilterAccountingMethod = OpenEnum<
  typeof ProfitAndLossFilterAccountingMethod
>;

export const ProfitAndLossFilterAccountingMethod$zodSchema = z.union([
  z.enum([
    "cash",
    "accrual",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("The accounting method used for the report: cash or accrual.");

export type ProfitAndLossFilter = {
  customer_id?: string | undefined;
  start_date?: string | undefined;
  end_date?: string | undefined;
  location_id?: string | undefined;
  accounting_method?: ProfitAndLossFilterAccountingMethod | undefined;
};

export const ProfitAndLossFilter$zodSchema: z.ZodType<ProfitAndLossFilter> = z
  .object({
    accounting_method: ProfitAndLossFilterAccountingMethod$zodSchema.optional()
      .describe("The accounting method used for the report: cash or accrual."),
    customer_id: z.string().optional().describe("Filter by customer id"),
    end_date: z.string().optional().describe(
      "Filter by end date. If end date is given, start date is required.",
    ),
    location_id: z.string().optional().describe("Filter by location id"),
    start_date: z.string().optional().describe(
      "Filter by start date. If start date is given, end date is required.",
    ),
  });
