/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import { SortDirection, SortDirection$zodSchema } from "./sortdirection.js";

/**
 * The field to sort by
 */
export const ProjectsSortSortBy = {
  Name: "name",
  Status: "status",
  StartDate: "start_date",
  EndDate: "end_date",
  BudgetAmount: "budget_amount",
  ActualAmount: "actual_amount",
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
} as const;
/**
 * The field to sort by
 */
export type ProjectsSortSortBy = OpenEnum<typeof ProjectsSortSortBy>;

export const ProjectsSortSortBy$zodSchema = z.union([
  z.enum([
    "name",
    "status",
    "start_date",
    "end_date",
    "budget_amount",
    "actual_amount",
    "created_at",
    "updated_at",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("The field to sort by");

export type ProjectsSort = {
  by?: ProjectsSortSortBy | undefined;
  direction?: SortDirection | undefined;
};

export const ProjectsSort$zodSchema: z.ZodType<ProjectsSort> = z.object({
  by: ProjectsSortSortBy$zodSchema.optional().describe("The field to sort by"),
  direction: SortDirection$zodSchema.default("asc").describe(
    "The direction in which to sort the results",
  ),
});
