/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";

export type ProxyDeleteProxyGlobals = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
};

export const ProxyDeleteProxyGlobals$zodSchema: z.ZodType<
  ProxyDeleteProxyGlobals
> = z.object({
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
});

export type ProxyDeleteProxyRequest = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
  xApideckServiceId: string;
  xApideckUnifiedApi?: string | undefined;
  xApideckDownstreamUrl: string;
  xApideckDownstreamAuthorization?: string | undefined;
};

export const ProxyDeleteProxyRequest$zodSchema: z.ZodType<
  ProxyDeleteProxyRequest
> = z.object({
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
  xApideckDownstreamAuthorization: z.string().describe(
    "Downstream authorization header. This will skip the Vault token injection.",
  ).optional(),
  xApideckDownstreamUrl: z.string().describe("Downstream URL"),
  xApideckServiceId: z.string().describe(
    "Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.",
  ),
  xApideckUnifiedApi: z.string().describe(
    "Specify which unified API to use for the connection lookup. Required for multi-API connectors (e.g., Workday) to ensure the correct credentials are used.",
  ).optional(),
});

export type ProxyDeleteProxyResponseResult =
  | { [k: string]: any }
  | Uint8Array
  | string
  | Uint8Array
  | string
  | string
  | string
  | string
  | Unauthorized
  | { [k: string]: any }
  | string
  | string
  | string;

export const ProxyDeleteProxyResponseResult$zodSchema: z.ZodType<
  ProxyDeleteProxyResponseResult
> = z.union([
  z.record(z.string(), z.any()).describe("Ok"),
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  z.string().describe("Ok"),
  z.string().describe("Ok"),
  z.string().describe("Ok"),
  Unauthorized$zodSchema,
  z.record(z.string(), z.any()).describe("Proxy error"),
  z.string().describe("Proxy error"),
  z.string().describe("Proxy error"),
  z.string().describe("Proxy error"),
]);

export type ProxyDeleteProxyResponse = {
  Headers: { [k: string]: Array<string> };
  Result:
    | { [k: string]: any }
    | Uint8Array
    | string
    | Uint8Array
    | string
    | string
    | string
    | string
    | Unauthorized
    | { [k: string]: any }
    | string
    | string
    | string;
};

export const ProxyDeleteProxyResponse$zodSchema: z.ZodType<
  ProxyDeleteProxyResponse
> = z.object({
  Headers: z.record(z.string(), z.array(z.string())).default({}),
  Result: z.union([
    z.record(z.string(), z.any()).describe("Ok"),
    z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ),
    z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ),
    z.string().describe("Ok"),
    z.string().describe("Ok"),
    z.string().describe("Ok"),
    Unauthorized$zodSchema,
    z.record(z.string(), z.any()).describe("Proxy error"),
    z.string().describe("Proxy error"),
    z.string().describe("Proxy error"),
    z.string().describe("Proxy error"),
  ]),
});
