/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";
import { Unauthorized, Unauthorized$zodSchema } from "./unauthorized.js";

export type ProxyPutProxyGlobals = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
};

export const ProxyPutProxyGlobals$zodSchema: z.ZodType<ProxyPutProxyGlobals> = z
  .object({
    xApideckAppId: z.string().describe("The ID of your Unify application")
      .optional(),
    xApideckConsumerId: z.string().describe(
      "ID of the consumer which you want to get or push data from",
    ).optional(),
  });

export type ProxyPutProxyRequestBody2 = {};

export const ProxyPutProxyRequestBody2$zodSchema: z.ZodType<
  ProxyPutProxyRequestBody2
> = z.object({});

export type ProxyPutProxyRequestBody1 = {};

export const ProxyPutProxyRequestBody1$zodSchema: z.ZodType<
  ProxyPutProxyRequestBody1
> = z.object({});

export type ProxyPutProxyRequest = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
  xApideckServiceId: string;
  xApideckUnifiedApi?: string | undefined;
  xApideckDownstreamUrl: string;
  xApideckDownstreamAuthorization?: string | undefined;
  xApideckTimeout?: number | undefined;
  body?: Uint8Array | string | undefined;
};

export const ProxyPutProxyRequest$zodSchema: z.ZodType<ProxyPutProxyRequest> = z
  .object({
    body: z.string().describe("Base64-encoded binary content").transform(
      b64$.bytesFromBase64,
    ).optional(),
    xApideckAppId: z.string().describe("The ID of your Unify application")
      .optional(),
    xApideckConsumerId: z.string().describe(
      "ID of the consumer which you want to get or push data from",
    ).optional(),
    xApideckDownstreamAuthorization: z.string().describe(
      "Downstream authorization header. This will skip the Vault token injection.",
    ).optional(),
    xApideckDownstreamUrl: z.string().describe("Downstream URL"),
    xApideckServiceId: z.string().describe(
      "Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.",
    ),
    xApideckTimeout: z.int().default(28000).describe(
      "Override the default downstream request timeout in milliseconds. The default is 28000 (28 seconds).",
    ),
    xApideckUnifiedApi: z.string().describe(
      "Specify which unified API to use for the connection lookup. Required for multi-API connectors (e.g., Workday) to ensure the correct credentials are used.",
    ).optional(),
  });

export type ProxyPutProxyResponseResult =
  | { [k: string]: any }
  | Uint8Array
  | string
  | Uint8Array
  | string
  | string
  | string
  | string
  | Unauthorized
  | { [k: string]: any }
  | string
  | string
  | string;

export const ProxyPutProxyResponseResult$zodSchema: z.ZodType<
  ProxyPutProxyResponseResult
> = z.union([
  z.record(z.string(), z.any()).describe("Ok"),
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  z.string().describe("Ok"),
  z.string().describe("Ok"),
  z.string().describe("Ok"),
  Unauthorized$zodSchema,
  z.record(z.string(), z.any()).describe("Proxy error"),
  z.string().describe("Proxy error"),
  z.string().describe("Proxy error"),
  z.string().describe("Proxy error"),
]);

export type ProxyPutProxyResponse = {
  Headers: { [k: string]: Array<string> };
  Result:
    | { [k: string]: any }
    | Uint8Array
    | string
    | Uint8Array
    | string
    | string
    | string
    | string
    | Unauthorized
    | { [k: string]: any }
    | string
    | string
    | string;
};

export const ProxyPutProxyResponse$zodSchema: z.ZodType<ProxyPutProxyResponse> =
  z.object({
    Headers: z.record(z.string(), z.array(z.string())).default({}),
    Result: z.union([
      z.record(z.string(), z.any()).describe("Ok"),
      z.string().describe("Base64-encoded binary content").transform(
        b64$.bytesFromBase64,
      ),
      z.string().describe("Base64-encoded binary content").transform(
        b64$.bytesFromBase64,
      ),
      z.string().describe("Ok"),
      z.string().describe("Ok"),
      z.string().describe("Ok"),
      Unauthorized$zodSchema,
      z.record(z.string(), z.any()).describe("Proxy error"),
      z.string().describe("Proxy error"),
      z.string().describe("Proxy error"),
      z.string().describe("Proxy error"),
    ]),
  });
