/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Address, Address$zodSchema } from "./address.js";
import { AllocationInput, AllocationInput$zodSchema } from "./allocation.js";
import { Currency, Currency$zodSchema } from "./currency.js";
import {
  CustomFieldUnion,
  CustomFieldUnion$zodSchema,
} from "./customfieldunion.js";
import {
  InvoiceLineItemInput,
  InvoiceLineItemInput$zodSchema,
} from "./invoicelineitem.js";
import {
  LinkedCustomerInput,
  LinkedCustomerInput$zodSchema,
} from "./linkedcustomerinput.js";
import {
  LinkedDepartmentInput,
  LinkedDepartmentInput$zodSchema,
} from "./linkeddepartmentinput.js";
import {
  LinkedLedgerAccount,
  LinkedLedgerAccount$zodSchema,
} from "./linkedledgeraccount.js";
import {
  LinkedLocationInput,
  LinkedLocationInput$zodSchema,
} from "./linkedlocationinput.js";
import {
  LinkedTrackingCategory,
  LinkedTrackingCategory$zodSchema,
} from "./linkedtrackingcategory.js";
import {
  PassThroughBody,
  PassThroughBody$zodSchema,
} from "./passthroughbody.js";
import { RefundStatus, RefundStatus$zodSchema } from "./refundstatus.js";
import { RefundType, RefundType$zodSchema } from "./refundtype.js";

export type RefundInput = {
  number?: string | null | undefined;
  customer?: LinkedCustomerInput | null | undefined;
  company_id?: string | null | undefined;
  currency?: Currency | null | undefined;
  currency_rate?: number | null | undefined;
  tax_inclusive?: boolean | null | undefined;
  sub_total?: number | null | undefined;
  total_amount: number | null;
  total_tax?: number | null | undefined;
  refund_date?: string | null | undefined;
  status?: RefundStatus | undefined;
  type?: RefundType | undefined;
  payment_method?: string | null | undefined;
  payment_method_reference?: string | null | undefined;
  payment_method_id?: string | null | undefined;
  account?: LinkedLedgerAccount | null | undefined;
  line_items?: Array<InvoiceLineItemInput> | undefined;
  allocations?: Array<AllocationInput> | undefined;
  tax_code?: string | null | undefined;
  discount_percentage?: number | null | undefined;
  discount_amount?: number | null | undefined;
  note?: string | null | undefined;
  customer_memo?: string | null | undefined;
  reference?: string | null | undefined;
  billing_address?: Address | undefined;
  shipping_address?: Address | undefined;
  department?: LinkedDepartmentInput | null | undefined;
  location?: LinkedLocationInput | null | undefined;
  tracking_categories?: Array<LinkedTrackingCategory | null> | null | undefined;
  custom_fields?: Array<CustomFieldUnion> | undefined;
  row_version?: string | null | undefined;
  pass_through?: Array<PassThroughBody> | undefined;
};

export const RefundInput$zodSchema: z.ZodType<RefundInput> = z.object({
  account: LinkedLedgerAccount$zodSchema.nullable().optional(),
  allocations: z.array(AllocationInput$zodSchema).optional().describe(
    "Allocations linking refund to existing documents (invoices, credit notes, overpayments). Used for credit_note_refund and cash_refund types where the refund is applied against prior transactions. Supported by Sage Intacct and Zoho Books.",
  ),
  billing_address: Address$zodSchema.optional(),
  company_id: z.string().nullable().optional().describe(
    "The company ID the transaction belongs to",
  ),
  currency: Currency$zodSchema.nullable().optional().describe(
    "Indicates the associated currency for an amount of money. Values correspond to [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217).",
  ),
  currency_rate: z.number().nullable().optional().describe(
    "Currency Exchange Rate at the time entity was recorded/generated.",
  ),
  custom_fields: z.array(CustomFieldUnion$zodSchema).optional(),
  customer: LinkedCustomerInput$zodSchema.nullable().optional().describe(
    "The customer this entity is linked to.",
  ),
  customer_memo: z.string().nullable().optional().describe("Customer memo"),
  department: LinkedDepartmentInput$zodSchema.nullable().optional(),
  discount_amount: z.number().nullable().optional().describe(
    "Discount amount applied to this refund.",
  ),
  discount_percentage: z.number().nullable().optional().describe(
    "Discount percentage applied to this refund.",
  ),
  line_items: z.array(InvoiceLineItemInput$zodSchema).optional().describe(
    "Line items for itemized refunds (type: refund_receipt). Used when the refund includes product/service details with quantities and pricing. Supported by QBO RefundReceipt and NetSuite CashRefund.",
  ),
  location: LinkedLocationInput$zodSchema.nullable().optional(),
  note: z.string().nullable().optional().describe(
    "Optional note to be associated with the refund.",
  ),
  number: z.string().nullable().optional().describe(
    "Reference number for the refund.",
  ),
  pass_through: z.array(PassThroughBody$zodSchema).optional().describe(
    "The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.",
  ),
  payment_method: z.string().nullable().optional().describe(
    "Payment method used for the transaction, such as cash, credit card, bank transfer, or check",
  ),
  payment_method_id: z.string().nullable().optional().describe(
    "A unique identifier for an object.",
  ),
  payment_method_reference: z.string().nullable().optional().describe(
    "Optional reference message returned by payment method on processing",
  ),
  reference: z.string().nullable().optional().describe(
    "Optional reference message for the refund.",
  ),
  refund_date: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date of the refund - YYYY-MM-DDThh:mm:ss.sTZD",
  ),
  row_version: z.string().nullable().optional().describe(
    "A binary value used to detect updates to a object and prevent data conflicts. It is incremented each time an update is made to the object.",
  ),
  shipping_address: Address$zodSchema.optional(),
  status: RefundStatus$zodSchema.optional().describe(
    "Status of refund. Maps to: QBO (limited status), NetSuite CashRefund status, Sage Intacct state (draft/posted/voided), Zoho Books vis_state.",
  ),
  sub_total: z.number().nullable().optional().describe(
    "Subtotal amount, normally before tax.",
  ),
  tax_code: z.string().nullable().optional().describe(
    "Applicable tax id/code override if tax is not supplied on a line item basis.",
  ),
  tax_inclusive: z.boolean().nullable().optional().describe(
    "Amounts are including tax",
  ),
  total_amount: z.number().nullable().describe(
    "The total amount of the transaction or record",
  ),
  total_tax: z.number().nullable().optional().describe(
    "Total tax amount applied to this transaction.",
  ),
  tracking_categories: z.array(LinkedTrackingCategory$zodSchema.nullable())
    .nullable().optional().describe("A list of linked tracking categories."),
  type: RefundType$zodSchema.optional().describe(
    "Type of refund. `refund_receipt` for itemized refunds with product/service lines and payment (QBO RefundReceipt, NetSuite CashRefund). `cash_refund` for cash-out refunds with GL distribution or allocations (Sage Intacct). `credit_note_refund` for refunds applied against a credit note (Zoho Books).",
  ),
});
