/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import {
  PassThroughBody,
  PassThroughBody$zodSchema,
} from "./passthroughbody.js";
import {
  SharedLinkTarget,
  SharedLinkTarget$zodSchema,
} from "./sharedlinktarget.js";

/**
 * The scope of the shared link.
 */
export const Scope = {
  Public: "public",
  Company: "company",
} as const;
/**
 * The scope of the shared link.
 */
export type Scope = OpenEnum<typeof Scope>;

export const Scope$zodSchema = z.union([
  z.enum([
    "public",
    "company",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("The scope of the shared link.");

export type SharedLinkOutput = {
  url?: string | null | undefined;
  download_url?: string | null | undefined;
  target?: SharedLinkTarget | undefined;
  scope?: Scope | null | undefined;
  password_protected?: boolean | null | undefined;
  expires_at?: string | null | undefined;
  updated_at?: string | null | undefined;
  created_at?: string | null | undefined;
  pass_through?: Array<PassThroughBody> | undefined;
};

export const SharedLinkOutput$zodSchema: z.ZodType<SharedLinkOutput> = z.object(
  {
    created_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
      "The date and time when the object was created.",
    ),
    download_url: z.string().nullable().optional().describe(
      "The URL that can be used to download the file.",
    ),
    expires_at: z.iso.datetime({ offset: true }).nullable().optional(),
    pass_through: z.array(PassThroughBody$zodSchema).optional().describe(
      "The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.",
    ),
    password_protected: z.boolean().nullable().optional().describe(
      "Indicated if the shared link is password protected.",
    ),
    scope: Scope$zodSchema.nullable().optional().describe(
      "The scope of the shared link.",
    ),
    target: SharedLinkTarget$zodSchema.optional(),
    updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
      "The date and time when the object was last updated.",
    ),
    url: z.string().nullable().optional().describe(
      "The URL that can be used to view the file.",
    ),
  },
);

export type SharedLinkInput = {
  download_url?: string | null | undefined;
  target_id: string | null;
  scope?: Scope | null | undefined;
  password?: string | null | undefined;
  pass_through?: Array<PassThroughBody> | undefined;
};

export const SharedLinkInput$zodSchema: z.ZodType<SharedLinkInput> = z.object({
  download_url: z.string().nullable().optional().describe(
    "The URL that can be used to download the file.",
  ),
  pass_through: z.array(PassThroughBody$zodSchema).optional().describe(
    "The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.",
  ),
  password: z.string().nullable().optional().describe(
    "Optional password for the shared link.",
  ),
  scope: Scope$zodSchema.nullable().optional().describe(
    "The scope of the shared link.",
  ),
  target_id: z.string().nullable().describe(
    "The ID of the file or folder to link.",
  ),
});
