/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestResponse,
  BadRequestResponse$zodSchema,
} from "./badrequestresponse.js";
import {
  CreateMessageResponse,
  CreateMessageResponse$zodSchema,
} from "./createmessageresponse.js";
import { MessageInput, MessageInput$zodSchema } from "./message.js";
import {
  NotFoundResponse,
  NotFoundResponse$zodSchema,
} from "./notfoundresponse.js";
import {
  PaymentRequiredResponse,
  PaymentRequiredResponse$zodSchema,
} from "./paymentrequiredresponse.js";
import {
  UnauthorizedResponse,
  UnauthorizedResponse$zodSchema,
} from "./unauthorizedresponse.js";
import {
  UnexpectedErrorResponse,
  UnexpectedErrorResponse$zodSchema,
} from "./unexpectederrorresponse.js";
import {
  UnprocessableResponse,
  UnprocessableResponse$zodSchema,
} from "./unprocessableresponse.js";

export type SmsMessagesAddGlobals = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
};

export const SmsMessagesAddGlobals$zodSchema: z.ZodType<SmsMessagesAddGlobals> =
  z.object({
    xApideckAppId: z.string().describe("The ID of your Unify application")
      .optional(),
    xApideckConsumerId: z.string().describe(
      "ID of the consumer which you want to get or push data from",
    ).optional(),
  });

export type SmsMessagesAddRequest = {
  raw?: boolean | undefined;
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
  xApideckServiceId?: string | undefined;
  body: MessageInput;
};

export const SmsMessagesAddRequest$zodSchema: z.ZodType<SmsMessagesAddRequest> =
  z.object({
    body: MessageInput$zodSchema,
    raw: z.boolean().default(false).describe(
      "Include raw response. Mostly used for debugging purposes",
    ),
    xApideckAppId: z.string().describe("The ID of your Unify application")
      .optional(),
    xApideckConsumerId: z.string().describe(
      "ID of the consumer which you want to get or push data from",
    ).optional(),
    xApideckServiceId: z.string().describe(
      "Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.",
    ).optional(),
  });

export type SmsMessagesAddResponse =
  | CreateMessageResponse
  | BadRequestResponse
  | UnauthorizedResponse
  | PaymentRequiredResponse
  | NotFoundResponse
  | UnprocessableResponse
  | UnexpectedErrorResponse;

export const SmsMessagesAddResponse$zodSchema: z.ZodType<
  SmsMessagesAddResponse
> = z.union([
  CreateMessageResponse$zodSchema,
  BadRequestResponse$zodSchema,
  UnauthorizedResponse$zodSchema,
  PaymentRequiredResponse$zodSchema,
  NotFoundResponse$zodSchema,
  UnprocessableResponse$zodSchema,
  UnexpectedErrorResponse$zodSchema,
]);
