/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";

/**
 * The direction in which to sort the results
 */
export const SortDirection = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The direction in which to sort the results
 */
export type SortDirection = OpenEnum<typeof SortDirection>;

export const SortDirection$zodSchema = z.union([
  z.enum([
    "asc",
    "desc",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("The direction in which to sort the results");
