/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";

/**
 * The status of the webhook.
 */
export const Status = {
  Enabled: "enabled",
  Disabled: "disabled",
} as const;
/**
 * The status of the webhook.
 */
export type Status = OpenEnum<typeof Status>;

export const Status$zodSchema = z.union([
  z.enum([
    "enabled",
    "disabled",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("The status of the webhook.");
