/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import { SortDirection, SortDirection$zodSchema } from "./sortdirection.js";

/**
 * The field on which to sort the Suppliers
 */
export const SuppliersSortBy = {
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
} as const;
/**
 * The field on which to sort the Suppliers
 */
export type SuppliersSortBy = OpenEnum<typeof SuppliersSortBy>;

export const SuppliersSortBy$zodSchema = z.union([
  z.enum([
    "created_at",
    "updated_at",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("The field on which to sort the Suppliers");

export type SuppliersSort = {
  by?: SuppliersSortBy | undefined;
  direction?: SortDirection | undefined;
};

export const SuppliersSort$zodSchema: z.ZodType<SuppliersSort> = z.object({
  by: SuppliersSortBy$zodSchema.optional().describe(
    "The field on which to sort the Suppliers",
  ),
  direction: SortDirection$zodSchema.default("asc").describe(
    "The direction in which to sort the results",
  ),
});
