/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import { SortDirection, SortDirection$zodSchema } from "./sortdirection.js";

/**
 * The field on which to sort the Tickets
 */
export const TicketsSortBy = {
  CreatedAt: "created_at",
  UpdatedAt: "updated_at",
} as const;
/**
 * The field on which to sort the Tickets
 */
export type TicketsSortBy = OpenEnum<typeof TicketsSortBy>;

export const TicketsSortBy$zodSchema = z.union([
  z.enum([
    "created_at",
    "updated_at",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe("The field on which to sort the Tickets");

export type TicketsSort = {
  by?: TicketsSortBy | undefined;
  direction?: SortDirection | undefined;
};

export const TicketsSort$zodSchema: z.ZodType<TicketsSort> = z.object({
  by: TicketsSortBy$zodSchema.optional().describe(
    "The field on which to sort the Tickets",
  ),
  direction: SortDirection$zodSchema.default("asc").describe(
    "The direction in which to sort the results",
  ),
});
