/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { collectExtraKeys as collectExtraKeys$ } from "../lib/schemas.js";

/**
 * HTTP request details
 */
export type UnauthorizedResponseRequest = {};

export const UnauthorizedResponseRequest$zodSchema: z.ZodType<
  UnauthorizedResponseRequest
> = z.object({}).describe("HTTP request details");

/**
 * HTTP response details
 */
export type UnauthorizedResponseResponse = {};

export const UnauthorizedResponseResponse$zodSchema: z.ZodType<
  UnauthorizedResponseResponse
> = z.object({}).describe("HTTP response details");

/**
 * Debug information including request/response details and OAuth timing metadata
 */
export type UnauthorizedResponseDebug = {
  request?: UnauthorizedResponseRequest | undefined;
  response?: UnauthorizedResponseResponse | undefined;
  message?: string | undefined;
  code?: string | undefined;
  credentials_expire_at_ms?: number | undefined;
  retry_after_ms?: number | undefined;
  cooldown_remaining_ms?: number | undefined;
};

export const UnauthorizedResponseDebug$zodSchema: z.ZodType<
  UnauthorizedResponseDebug
> = z.object({
  code: z.string().optional().describe(
    "Error code (e.g., ETIMEDOUT, ECONNREFUSED)",
  ),
  cooldown_remaining_ms: z.number().optional().describe(
    "Milliseconds remaining in cooldown period before retry is allowed.",
  ),
  credentials_expire_at_ms: z.number().optional().describe(
    "Unix timestamp (milliseconds) when credentials will be deleted if not refreshed. Only present for non-recoverable errors (401, 400). Credentials are preserved indefinitely for recoverable/network errors.",
  ),
  message: z.string().optional().describe(
    "Error message from downstream provider or network layer",
  ),
  request: z.lazy(() => UnauthorizedResponseRequest$zodSchema).optional()
    .describe("HTTP request details"),
  response: z.lazy(() => UnauthorizedResponseResponse$zodSchema).optional()
    .describe("HTTP response details"),
  retry_after_ms: z.number().optional().describe(
    "Unix timestamp (milliseconds) when token refresh retry is allowed after cooldown period expires.",
  ),
}).describe(
  "Debug information including request/response details and OAuth timing metadata",
);

export type UnauthorizedResponseDetail = {
  type?: string | undefined;
  message?: string | undefined;
  debug?: UnauthorizedResponseDebug | undefined;
  AdditionalProperties?: { [k: string]: any };
};

export const UnauthorizedResponseDetail$zodSchema: z.ZodType<
  UnauthorizedResponseDetail
> = collectExtraKeys$(
  z.object({
    debug: z.lazy(() => UnauthorizedResponseDebug$zodSchema).optional()
      .describe(
        "Debug information including request/response details and OAuth timing metadata",
      ),
    message: z.string().optional().describe("Detailed error message"),
    type: z.string().optional().describe("Error type identifier"),
  }).catchall(z.any()),
  "AdditionalProperties",
  true,
);

export const UnauthorizedResponseDetail$zodSchemaOutbound: z.ZodType<any> = z
  .object({
    AdditionalProperties: z.record(z.string(), z.any()).optional(),
    debug: z.lazy(() => UnauthorizedResponseDebug$zodSchema).optional(),
    message: z.string().optional(),
    type: z.string().optional(),
  }).transform((v) => {
    const { AdditionalProperties, ...rest } = v;
    return {
      ...rest,
      ...AdditionalProperties,
    };
  });

/**
 * Contains parameter or domain specific information related to the error and why it occurred.
 */
export type UnauthorizedResponseDetailUnion =
  | string
  | UnauthorizedResponseDetail;

export const UnauthorizedResponseDetailUnion$zodSchema: z.ZodType<
  UnauthorizedResponseDetailUnion
> = z.union([
  z.string(),
  z.lazy(() => UnauthorizedResponseDetail$zodSchema),
]).describe(
  "Contains parameter or domain specific information related to the error and why it occurred.",
);

/**
 * Unauthorized
 */
export type UnauthorizedResponse = {
  status_code?: number | undefined;
  error?: string | undefined;
  type_name?: string | undefined;
  message?: string | undefined;
  detail?: string | UnauthorizedResponseDetail | undefined;
  ref?: string | undefined;
};

export const UnauthorizedResponse$zodSchema: z.ZodType<UnauthorizedResponse> = z
  .object({
    detail: z.union([
      z.string(),
      z.lazy(() => UnauthorizedResponseDetail$zodSchema),
    ]).optional().describe(
      "Contains parameter or domain specific information related to the error and why it occurred.",
    ),
    error: z.string().optional().describe(
      "Contains an explanation of the status_code as defined in HTTP/1.1 standard (RFC 7231)",
    ),
    message: z.string().optional().describe(
      "A human-readable message providing more details about the error.",
    ),
    ref: z.string().optional().describe("Link to documentation of error type"),
    status_code: z.number().optional().describe("HTTP status code"),
    type_name: z.string().optional().describe("The type of error returned"),
  }).describe("Unauthorized");
