/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";

/**
 * Wildcard indicating all resources and fields when Data Scopes is disabled
 */
export const ResourcesEnum = {
  Wildcard: "*",
} as const;
/**
 * Wildcard indicating all resources and fields when Data Scopes is disabled
 */
export type ResourcesEnum = OpenEnum<typeof ResourcesEnum>;

export const ResourcesEnum$zodSchema = z.union([
  z.enum([
    "*",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe(
  "Wildcard indicating all resources and fields when Data Scopes is disabled",
);

export type UpdateConsentRequestResources = {
  read?: boolean | undefined;
  write?: boolean | undefined;
};

export const UpdateConsentRequestResources$zodSchema: z.ZodType<
  UpdateConsentRequestResources
> = z.object({
  read: z.boolean().optional().describe("Whether the field can be read"),
  write: z.boolean().optional().describe("Whether the field can be written to"),
});

export type Resources = {
  [k: string]: { [k: string]: UpdateConsentRequestResources };
} | ResourcesEnum;

export const Resources$zodSchema: z.ZodType<Resources> = z.union([
  z.record(
    z.string(),
    z.record(z.string(), z.lazy(() => UpdateConsentRequestResources$zodSchema)),
  ),
  ResourcesEnum$zodSchema,
]);

export type UpdateConsentRequest = {
  resources:
    | { [k: string]: { [k: string]: UpdateConsentRequestResources } }
    | ResourcesEnum;
  granted: boolean;
};

export const UpdateConsentRequest$zodSchema: z.ZodType<UpdateConsentRequest> = z
  .object({
    granted: z.boolean().describe(
      "Whether consent is being granted (true) or denied/revoked (false)",
    ),
    resources: z.union([
      z.record(
        z.string(),
        z.record(
          z.string(),
          z.lazy(() => UpdateConsentRequestResources$zodSchema),
        ),
      ),
      ResourcesEnum$zodSchema,
    ]),
  });
