/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestResponse,
  BadRequestResponse$zodSchema,
} from "./badrequestresponse.js";
import { ConnectionInput, ConnectionInput$zodSchema } from "./connection.js";
import {
  NotFoundResponse,
  NotFoundResponse$zodSchema,
} from "./notfoundresponse.js";
import {
  PaymentRequiredResponse,
  PaymentRequiredResponse$zodSchema,
} from "./paymentrequiredresponse.js";
import {
  UnauthorizedResponse,
  UnauthorizedResponse$zodSchema,
} from "./unauthorizedresponse.js";
import {
  UnexpectedErrorResponse,
  UnexpectedErrorResponse$zodSchema,
} from "./unexpectederrorresponse.js";
import {
  UnprocessableResponse,
  UnprocessableResponse$zodSchema,
} from "./unprocessableresponse.js";
import {
  UpdateConnectionResponse,
  UpdateConnectionResponse$zodSchema,
} from "./updateconnectionresponse.js";

export type VaultConnectionSettingsUpdateGlobals = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
};

export const VaultConnectionSettingsUpdateGlobals$zodSchema: z.ZodType<
  VaultConnectionSettingsUpdateGlobals
> = z.object({
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
});

export type VaultConnectionSettingsUpdateRequest = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
  service_id: string;
  unified_api: string;
  resource: string;
  body: ConnectionInput;
};

export const VaultConnectionSettingsUpdateRequest$zodSchema: z.ZodType<
  VaultConnectionSettingsUpdateRequest
> = z.object({
  body: ConnectionInput$zodSchema.describe(
    "Fields that need to be updated on the resource",
  ),
  resource: z.string().describe("Name of the resource (plural)"),
  service_id: z.string().describe("Service ID of the resource to return"),
  unified_api: z.string().describe("Unified API"),
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
});

export type VaultConnectionSettingsUpdateResponse =
  | UpdateConnectionResponse
  | BadRequestResponse
  | UnauthorizedResponse
  | PaymentRequiredResponse
  | NotFoundResponse
  | UnprocessableResponse
  | UnexpectedErrorResponse;

export const VaultConnectionSettingsUpdateResponse$zodSchema: z.ZodType<
  VaultConnectionSettingsUpdateResponse
> = z.union([
  UpdateConnectionResponse$zodSchema,
  BadRequestResponse$zodSchema,
  UnauthorizedResponse$zodSchema,
  PaymentRequiredResponse$zodSchema,
  NotFoundResponse$zodSchema,
  UnprocessableResponse$zodSchema,
  UnexpectedErrorResponse$zodSchema,
]);
