/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestResponse,
  BadRequestResponse$zodSchema,
} from "./badrequestresponse.js";
import {
  GetConnectionResponse,
  GetConnectionResponse$zodSchema,
} from "./getconnectionresponse.js";
import {
  NotFoundResponse,
  NotFoundResponse$zodSchema,
} from "./notfoundresponse.js";
import {
  PaymentRequiredResponse,
  PaymentRequiredResponse$zodSchema,
} from "./paymentrequiredresponse.js";
import {
  UnauthorizedResponse,
  UnauthorizedResponse$zodSchema,
} from "./unauthorizedresponse.js";
import {
  UnexpectedErrorResponse,
  UnexpectedErrorResponse$zodSchema,
} from "./unexpectederrorresponse.js";
import {
  UnprocessableResponse,
  UnprocessableResponse$zodSchema,
} from "./unprocessableresponse.js";

export type VaultConnectionsTokenGlobals = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
};

export const VaultConnectionsTokenGlobals$zodSchema: z.ZodType<
  VaultConnectionsTokenGlobals
> = z.object({
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
});

export type VaultConnectionsTokenRequestBody = {};

export const VaultConnectionsTokenRequestBody$zodSchema: z.ZodType<
  VaultConnectionsTokenRequestBody
> = z.object({});

export type VaultConnectionsTokenRequest = {
  xApideckConsumerId?: string | undefined;
  xApideckAppId?: string | undefined;
  service_id: string;
  unified_api: string;
  body?: VaultConnectionsTokenRequestBody | undefined;
};

export const VaultConnectionsTokenRequest$zodSchema: z.ZodType<
  VaultConnectionsTokenRequest
> = z.object({
  body: z.lazy(() => VaultConnectionsTokenRequestBody$zodSchema).optional(),
  service_id: z.string().describe("Service ID of the resource to return"),
  unified_api: z.string().describe("Unified API"),
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
  xApideckConsumerId: z.string().describe(
    "ID of the consumer which you want to get or push data from",
  ).optional(),
});

export type VaultConnectionsTokenResponse =
  | GetConnectionResponse
  | BadRequestResponse
  | UnauthorizedResponse
  | PaymentRequiredResponse
  | NotFoundResponse
  | UnprocessableResponse
  | UnexpectedErrorResponse;

export const VaultConnectionsTokenResponse$zodSchema: z.ZodType<
  VaultConnectionsTokenResponse
> = z.union([
  GetConnectionResponse$zodSchema,
  BadRequestResponse$zodSchema,
  UnauthorizedResponse$zodSchema,
  PaymentRequiredResponse$zodSchema,
  NotFoundResponse$zodSchema,
  UnprocessableResponse$zodSchema,
  UnexpectedErrorResponse$zodSchema,
]);
