/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestResponse,
  BadRequestResponse$zodSchema,
} from "./badrequestresponse.js";
import {
  GetWebhookEventLogsResponse,
  GetWebhookEventLogsResponse$zodSchema,
} from "./getwebhookeventlogsresponse.js";
import {
  NotFoundResponse,
  NotFoundResponse$zodSchema,
} from "./notfoundresponse.js";
import {
  PaymentRequiredResponse,
  PaymentRequiredResponse$zodSchema,
} from "./paymentrequiredresponse.js";
import {
  UnauthorizedResponse,
  UnauthorizedResponse$zodSchema,
} from "./unauthorizedresponse.js";
import {
  UnexpectedErrorResponse,
  UnexpectedErrorResponse$zodSchema,
} from "./unexpectederrorresponse.js";
import {
  UnprocessableResponse,
  UnprocessableResponse$zodSchema,
} from "./unprocessableresponse.js";
import {
  WebhookEventLogsFilter,
  WebhookEventLogsFilter$zodSchema,
} from "./webhookeventlogsfilter.js";

export type WebhookEventLogsAllGlobals = { xApideckAppId?: string | undefined };

export const WebhookEventLogsAllGlobals$zodSchema: z.ZodType<
  WebhookEventLogsAllGlobals
> = z.object({
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
});

export type WebhookEventLogsAllRequest = {
  xApideckAppId?: string | undefined;
  cursor?: string | null | undefined;
  limit?: number | undefined;
  filter?: WebhookEventLogsFilter | undefined;
};

export const WebhookEventLogsAllRequest$zodSchema: z.ZodType<
  WebhookEventLogsAllRequest
> = z.object({
  cursor: z.string().describe(
    "Cursor to start from. You can find cursors for next/previous pages in the meta.cursors property of the response.",
  ).nullable().optional(),
  filter: WebhookEventLogsFilter$zodSchema.optional().describe(
    "Filter results",
  ),
  limit: z.int().default(20).describe(
    "Number of results to return. Minimum 1, Maximum 200, Default 20",
  ),
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
});

export type WebhookEventLogsAllResponseResult =
  | GetWebhookEventLogsResponse
  | BadRequestResponse
  | UnauthorizedResponse
  | PaymentRequiredResponse
  | NotFoundResponse
  | UnprocessableResponse
  | UnexpectedErrorResponse;

export const WebhookEventLogsAllResponseResult$zodSchema: z.ZodType<
  WebhookEventLogsAllResponseResult
> = z.union([
  GetWebhookEventLogsResponse$zodSchema,
  BadRequestResponse$zodSchema,
  UnauthorizedResponse$zodSchema,
  PaymentRequiredResponse$zodSchema,
  NotFoundResponse$zodSchema,
  UnprocessableResponse$zodSchema,
  UnexpectedErrorResponse$zodSchema,
]);

export type WebhookEventLogsAllResponse = {
  Result:
    | GetWebhookEventLogsResponse
    | BadRequestResponse
    | UnauthorizedResponse
    | PaymentRequiredResponse
    | NotFoundResponse
    | UnprocessableResponse
    | UnexpectedErrorResponse;
};

export const WebhookEventLogsAllResponse$zodSchema: z.ZodType<
  WebhookEventLogsAllResponse
> = z.object({
  Result: z.union([
    GetWebhookEventLogsResponse$zodSchema,
    BadRequestResponse$zodSchema,
    UnauthorizedResponse$zodSchema,
    PaymentRequiredResponse$zodSchema,
    NotFoundResponse$zodSchema,
    UnprocessableResponse$zodSchema,
    UnexpectedErrorResponse$zodSchema,
  ]),
});
