/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WebhookEventLogsFilterService = { id?: string | undefined };

export const WebhookEventLogsFilterService$zodSchema: z.ZodType<
  WebhookEventLogsFilterService
> = z.object({
  id: z.string().optional(),
});

export type WebhookEventLogsFilter = {
  exclude_apis?: string | null | undefined;
  service?: WebhookEventLogsFilterService | null | undefined;
  consumer_id?: string | null | undefined;
  entity_type?: string | null | undefined;
  event_type?: string | null | undefined;
};

export const WebhookEventLogsFilter$zodSchema: z.ZodType<
  WebhookEventLogsFilter
> = z.object({
  consumer_id: z.string().nullable().optional(),
  entity_type: z.string().nullable().optional(),
  event_type: z.string().nullable().optional(),
  exclude_apis: z.string().nullable().optional(),
  service: z.lazy(() => WebhookEventLogsFilterService$zodSchema).nullable()
    .optional(),
});
