/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { catchUnrecognizedEnum, OpenEnum } from "../types/enums.js";
import { Status, Status$zodSchema } from "./status.js";
import { UnifiedApiId, UnifiedApiId$zodSchema } from "./unifiedapiid.js";
import {
  WebhookEventType,
  WebhookEventType$zodSchema,
} from "./webhookeventtype.js";

/**
 * Indicates why the webhook has been disabled. `retry_limit`: webhook reached its retry limit. `usage_limit`: account is over its usage limit. `delivery_url_validation_failed`: delivery URL failed validation during webhook creation or update.
 */
export const DisabledReason = {
  None: "none",
  RetryLimit: "retry_limit",
  UsageLimit: "usage_limit",
  DeliveryUrlValidationFailed: "delivery_url_validation_failed",
} as const;
/**
 * Indicates why the webhook has been disabled. `retry_limit`: webhook reached its retry limit. `usage_limit`: account is over its usage limit. `delivery_url_validation_failed`: delivery URL failed validation during webhook creation or update.
 */
export type DisabledReason = OpenEnum<typeof DisabledReason>;

export const DisabledReason$zodSchema = z.union([
  z.enum([
    "none",
    "retry_limit",
    "usage_limit",
    "delivery_url_validation_failed",
  ]),
  z.string().transform(catchUnrecognizedEnum),
]).describe(
  "Indicates why the webhook has been disabled. `retry_limit`: webhook reached its retry limit. `usage_limit`: account is over its usage limit. `delivery_url_validation_failed`: delivery URL failed validation during webhook creation or update.",
);

export type Webhook = {
  id?: string | undefined;
  description?: string | null | undefined;
  unified_api: UnifiedApiId;
  status: Status;
  disabled_reason?: DisabledReason | undefined;
  delivery_url: string;
  execute_base_url: string;
  events: Array<WebhookEventType>;
  updated_at?: string | null | undefined;
  created_at?: string | null | undefined;
};

export const Webhook$zodSchema: z.ZodType<Webhook> = z.object({
  created_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date and time when the object was created.",
  ),
  delivery_url: z.string().describe(
    "The delivery url of the webhook endpoint.",
  ),
  description: z.string().nullable().optional().describe(
    "A description of the object.",
  ),
  disabled_reason: DisabledReason$zodSchema.optional().describe(
    "Indicates why the webhook has been disabled. `retry_limit`: webhook reached its retry limit. `usage_limit`: account is over its usage limit. `delivery_url_validation_failed`: delivery URL failed validation during webhook creation or update.",
  ),
  events: z.array(WebhookEventType$zodSchema).describe(
    "The list of subscribed events for this webhook. [`*`] indicates that all events are enabled.",
  ),
  execute_base_url: z.string().describe(
    "The Unify Base URL events from connectors will be sent to after service id is appended.",
  ),
  id: z.string().optional(),
  status: Status$zodSchema.describe("The status of the webhook."),
  unified_api: UnifiedApiId$zodSchema.describe("Name of Apideck Unified API"),
  updated_at: z.iso.datetime({ offset: true }).nullable().optional().describe(
    "The date and time when the object was last updated.",
  ),
});
