/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BadRequestResponse,
  BadRequestResponse$zodSchema,
} from "./badrequestresponse.js";
import {
  NotFoundResponse,
  NotFoundResponse$zodSchema,
} from "./notfoundresponse.js";
import {
  PaymentRequiredResponse,
  PaymentRequiredResponse$zodSchema,
} from "./paymentrequiredresponse.js";
import {
  UnauthorizedResponse,
  UnauthorizedResponse$zodSchema,
} from "./unauthorizedresponse.js";
import {
  UnexpectedErrorResponse,
  UnexpectedErrorResponse$zodSchema,
} from "./unexpectederrorresponse.js";
import {
  UnprocessableResponse,
  UnprocessableResponse$zodSchema,
} from "./unprocessableresponse.js";
import {
  UpdateWebhookRequest,
  UpdateWebhookRequest$zodSchema,
} from "./updatewebhookrequest.js";
import {
  UpdateWebhookResponse,
  UpdateWebhookResponse$zodSchema,
} from "./updatewebhookresponse.js";

export type WebhookWebhooksUpdateGlobals = {
  xApideckAppId?: string | undefined;
};

export const WebhookWebhooksUpdateGlobals$zodSchema: z.ZodType<
  WebhookWebhooksUpdateGlobals
> = z.object({
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
});

export type WebhookWebhooksUpdateRequest = {
  id: string;
  xApideckAppId?: string | undefined;
  body: UpdateWebhookRequest;
};

export const WebhookWebhooksUpdateRequest$zodSchema: z.ZodType<
  WebhookWebhooksUpdateRequest
> = z.object({
  body: UpdateWebhookRequest$zodSchema,
  id: z.string().describe(
    "JWT Webhook token that represents the unifiedApi and applicationId associated to the event source.",
  ),
  xApideckAppId: z.string().describe("The ID of your Unify application")
    .optional(),
});

export type WebhookWebhooksUpdateResponse =
  | UpdateWebhookResponse
  | BadRequestResponse
  | UnauthorizedResponse
  | PaymentRequiredResponse
  | NotFoundResponse
  | UnprocessableResponse
  | UnexpectedErrorResponse;

export const WebhookWebhooksUpdateResponse$zodSchema: z.ZodType<
  WebhookWebhooksUpdateResponse
> = z.union([
  UpdateWebhookResponse$zodSchema,
  BadRequestResponse$zodSchema,
  UnauthorizedResponse$zodSchema,
  PaymentRequiredResponse$zodSchema,
  NotFoundResponse$zodSchema,
  UnprocessableResponse$zodSchema,
  UnexpectedErrorResponse$zodSchema,
]);
